<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_katsudon.proto

namespace App\GameProtocol\Proto\Katsudon\Taiko\SongInfoResponse;

use App\GameProtocol\Proto\Katsudon\Metadata\TaikoKatsudon;
use App\GameProtocol\Proto\Katsudon\Taiko\SongInfoResponse\GroupData\FriendData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.katsudon.SongInfoResponse.GroupData</code>
 */
class GroupData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     */
    protected $song_no = null;

    /**
     * Generated from protobuf field <code>repeated uint32 ary_high_score = 2;</code>
     */
    private $ary_high_score;

    /**
     * Generated from protobuf field <code>repeated .taiko.katsudon.SongInfoResponse.GroupData.FriendData ary_friend_score = 3;</code>
     */
    private $ary_friend_score;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $song_no
     * @type int[] $ary_high_score
     * @type \App\GameProtocol\Proto\Katsudon\Taiko\SongInfoResponse\GroupData\FriendData[] $ary_friend_score
     *                                                                                      }
     */
    public function __construct($data = null)
    {
        TaikoKatsudon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     *
     * @return int
     */
    public function getSongNo()
    {
        return isset($this->song_no) ? $this->song_no : 0;
    }

    public function hasSongNo()
    {
        return isset($this->song_no);
    }

    public function clearSongNo()
    {
        unset($this->song_no);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     *
     * @return $this
     */
    public function setSongNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->song_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ary_high_score = 2;</code>
     *
     * @return RepeatedField<int>
     */
    public function getAryHighScore()
    {
        return $this->ary_high_score;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ary_high_score = 2;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setAryHighScore(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->ary_high_score = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.katsudon.SongInfoResponse.GroupData.FriendData ary_friend_score = 3;</code>
     *
     * @return RepeatedField<FriendData>
     */
    public function getAryFriendScore()
    {
        return $this->ary_friend_score;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.katsudon.SongInfoResponse.GroupData.FriendData ary_friend_score = 3;</code>
     *
     * @param  FriendData[]  $var
     * @return $this
     */
    public function setAryFriendScore(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, FriendData::class);
        $this->ary_friend_score = $arr;

        return $this;
    }
}
