<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\White\Taiko;

use App\GameProtocol\Green\Proto\White\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.white.GettelopResponse</code>
 */
class GettelopResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     */
    protected $verup_no = null;

    /**
     * Generated from protobuf field <code>optional string start_datetime = 3;</code>
     */
    protected $start_datetime = null;

    /**
     * Generated from protobuf field <code>optional string end_datetime = 4;</code>
     */
    protected $end_datetime = null;

    /**
     * Generated from protobuf field <code>optional string telop = 5;</code>
     */
    protected $telop = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $verup_no
     * @type string $start_datetime
     * @type string $end_datetime
     * @type string $telop
     *              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     *
     * @return int
     */
    public function getVerupNo()
    {
        return isset($this->verup_no) ? $this->verup_no : 0;
    }

    public function hasVerupNo()
    {
        return isset($this->verup_no);
    }

    public function clearVerupNo()
    {
        unset($this->verup_no);
    }

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     *
     * @return $this
     */
    public function setVerupNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->verup_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string start_datetime = 3;</code>
     *
     * @return string
     */
    public function getStartDatetime()
    {
        return isset($this->start_datetime) ? $this->start_datetime : '';
    }

    public function hasStartDatetime()
    {
        return isset($this->start_datetime);
    }

    public function clearStartDatetime()
    {
        unset($this->start_datetime);
    }

    /**
     * Generated from protobuf field <code>optional string start_datetime = 3;</code>
     *
     * @return $this
     */
    public function setStartDatetime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->start_datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string end_datetime = 4;</code>
     *
     * @return string
     */
    public function getEndDatetime()
    {
        return isset($this->end_datetime) ? $this->end_datetime : '';
    }

    public function hasEndDatetime()
    {
        return isset($this->end_datetime);
    }

    public function clearEndDatetime()
    {
        unset($this->end_datetime);
    }

    /**
     * Generated from protobuf field <code>optional string end_datetime = 4;</code>
     *
     * @return $this
     */
    public function setEndDatetime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->end_datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string telop = 5;</code>
     *
     * @return string
     */
    public function getTelop()
    {
        return isset($this->telop) ? $this->telop : '';
    }

    public function hasTelop()
    {
        return isset($this->telop);
    }

    public function clearTelop()
    {
        unset($this->telop);
    }

    /**
     * Generated from protobuf field <code>optional string telop = 5;</code>
     *
     * @return $this
     */
    public function setTelop(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->telop = $var;

        return $this;
    }
}
