<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Momoiro\Taiko;

use App\GameProtocol\Green\Proto\Momoiro\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.momoiro.MydonEntryResponse</code>
 */
class MydonEntryResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_result = 2;</code>
     */
    protected $com_svr_result = null;

    /**
     * Generated from protobuf field <code>optional uint32 personal_id = 3;</code>
     */
    protected $personal_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 baid = 4;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional string access_code = 5;</code>
     */
    protected $access_code = null;

    /**
     * Generated from protobuf field <code>optional bool is_publish = 6;</code>
     */
    protected $is_publish = null;

    /**
     * Generated from protobuf field <code>optional uint32 card_own_num = 7;</code>
     */
    protected $card_own_num = null;

    /**
     * Generated from protobuf field <code>optional string reg_country_id = 8;</code>
     */
    protected $reg_country_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 purpose_id = 9;</code>
     */
    protected $purpose_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 region_id = 10;</code>
     */
    protected $region_id = null;

    /**
     * Generated from protobuf field <code>optional string mydon_name = 11;</code>
     */
    protected $mydon_name = null;

    /**
     * Generated from protobuf field <code>optional uint32 reward_ptn = 12;</code>
     */
    protected $reward_ptn = null;

    /**
     * Generated from protobuf field <code>optional string accesstoken = 13;</code>
     */
    protected $accesstoken = null;

    /**
     * Generated from protobuf field <code>optional bytes content_info = 14;</code>
     */
    protected $content_info = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $com_svr_result
     * @type int $personal_id
     * @type int $baid
     * @type string $access_code
     * @type bool $is_publish
     * @type int $card_own_num
     * @type string $reg_country_id
     * @type int $purpose_id
     * @type int $region_id
     * @type string $mydon_name
     * @type int $reward_ptn
     * @type string $accesstoken
     * @type string $content_info
     *              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_result = 2;</code>
     *
     * @return int
     */
    public function getComSvrResult()
    {
        return isset($this->com_svr_result) ? $this->com_svr_result : 0;
    }

    public function hasComSvrResult()
    {
        return isset($this->com_svr_result);
    }

    public function clearComSvrResult()
    {
        unset($this->com_svr_result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_result = 2;</code>
     *
     * @return $this
     */
    public function setComSvrResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->com_svr_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 personal_id = 3;</code>
     *
     * @return int
     */
    public function getPersonalId()
    {
        return isset($this->personal_id) ? $this->personal_id : 0;
    }

    public function hasPersonalId()
    {
        return isset($this->personal_id);
    }

    public function clearPersonalId()
    {
        unset($this->personal_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 personal_id = 3;</code>
     *
     * @return $this
     */
    public function setPersonalId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->personal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 4;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 4;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string access_code = 5;</code>
     *
     * @return string
     */
    public function getAccessCode()
    {
        return isset($this->access_code) ? $this->access_code : '';
    }

    public function hasAccessCode()
    {
        return isset($this->access_code);
    }

    public function clearAccessCode()
    {
        unset($this->access_code);
    }

    /**
     * Generated from protobuf field <code>optional string access_code = 5;</code>
     *
     * @return $this
     */
    public function setAccessCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->access_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_publish = 6;</code>
     *
     * @return bool
     */
    public function getIsPublish()
    {
        return isset($this->is_publish) ? $this->is_publish : false;
    }

    public function hasIsPublish()
    {
        return isset($this->is_publish);
    }

    public function clearIsPublish()
    {
        unset($this->is_publish);
    }

    /**
     * Generated from protobuf field <code>optional bool is_publish = 6;</code>
     *
     * @return $this
     */
    public function setIsPublish(bool $var)
    {
        $this->is_publish = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 card_own_num = 7;</code>
     *
     * @return int
     */
    public function getCardOwnNum()
    {
        return isset($this->card_own_num) ? $this->card_own_num : 0;
    }

    public function hasCardOwnNum()
    {
        return isset($this->card_own_num);
    }

    public function clearCardOwnNum()
    {
        unset($this->card_own_num);
    }

    /**
     * Generated from protobuf field <code>optional uint32 card_own_num = 7;</code>
     *
     * @return $this
     */
    public function setCardOwnNum(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->card_own_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string reg_country_id = 8;</code>
     *
     * @return string
     */
    public function getRegCountryId()
    {
        return isset($this->reg_country_id) ? $this->reg_country_id : '';
    }

    public function hasRegCountryId()
    {
        return isset($this->reg_country_id);
    }

    public function clearRegCountryId()
    {
        unset($this->reg_country_id);
    }

    /**
     * Generated from protobuf field <code>optional string reg_country_id = 8;</code>
     *
     * @return $this
     */
    public function setRegCountryId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->reg_country_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 purpose_id = 9;</code>
     *
     * @return int
     */
    public function getPurposeId()
    {
        return isset($this->purpose_id) ? $this->purpose_id : 0;
    }

    public function hasPurposeId()
    {
        return isset($this->purpose_id);
    }

    public function clearPurposeId()
    {
        unset($this->purpose_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 purpose_id = 9;</code>
     *
     * @return $this
     */
    public function setPurposeId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->purpose_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 region_id = 10;</code>
     *
     * @return int
     */
    public function getRegionId()
    {
        return isset($this->region_id) ? $this->region_id : 0;
    }

    public function hasRegionId()
    {
        return isset($this->region_id);
    }

    public function clearRegionId()
    {
        unset($this->region_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 region_id = 10;</code>
     *
     * @return $this
     */
    public function setRegionId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->region_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string mydon_name = 11;</code>
     *
     * @return string
     */
    public function getMydonName()
    {
        return isset($this->mydon_name) ? $this->mydon_name : '';
    }

    public function hasMydonName()
    {
        return isset($this->mydon_name);
    }

    public function clearMydonName()
    {
        unset($this->mydon_name);
    }

    /**
     * Generated from protobuf field <code>optional string mydon_name = 11;</code>
     *
     * @return $this
     */
    public function setMydonName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->mydon_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 reward_ptn = 12;</code>
     *
     * @return int
     */
    public function getRewardPtn()
    {
        return isset($this->reward_ptn) ? $this->reward_ptn : 0;
    }

    public function hasRewardPtn()
    {
        return isset($this->reward_ptn);
    }

    public function clearRewardPtn()
    {
        unset($this->reward_ptn);
    }

    /**
     * Generated from protobuf field <code>optional uint32 reward_ptn = 12;</code>
     *
     * @return $this
     */
    public function setRewardPtn(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->reward_ptn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string accesstoken = 13;</code>
     *
     * @return string
     */
    public function getAccesstoken()
    {
        return isset($this->accesstoken) ? $this->accesstoken : '';
    }

    public function hasAccesstoken()
    {
        return isset($this->accesstoken);
    }

    public function clearAccesstoken()
    {
        unset($this->accesstoken);
    }

    /**
     * Generated from protobuf field <code>optional string accesstoken = 13;</code>
     *
     * @return $this
     */
    public function setAccesstoken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->accesstoken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes content_info = 14;</code>
     *
     * @return string
     */
    public function getContentInfo()
    {
        return isset($this->content_info) ? $this->content_info : '';
    }

    public function hasContentInfo()
    {
        return isset($this->content_info);
    }

    public function clearContentInfo()
    {
        unset($this->content_info);
    }

    /**
     * Generated from protobuf field <code>optional bytes content_info = 14;</code>
     *
     * @return $this
     */
    public function setContentInfo(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->content_info = $var;

        return $this;
    }
}
