<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Kimidori\Taiko\PlayResultRequest;

use App\GameProtocol\Green\Proto\Kimidori\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.kimidori.PlayResultRequest.CostumeData</code>
 */
class CostumeData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 costume_1 = 1;</code>
     */
    protected $costume_1 = null;

    /**
     * Generated from protobuf field <code>optional uint32 costume_2 = 2;</code>
     */
    protected $costume_2 = null;

    /**
     * Generated from protobuf field <code>optional uint32 costume_3 = 3;</code>
     */
    protected $costume_3 = null;

    /**
     * Generated from protobuf field <code>optional uint32 costume_4 = 4;</code>
     */
    protected $costume_4 = null;

    /**
     * Generated from protobuf field <code>optional uint32 costume_5 = 5;</code>
     */
    protected $costume_5 = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $costume_1
     * @type int $costume_2
     * @type int $costume_3
     * @type int $costume_4
     * @type int $costume_5
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_1 = 1;</code>
     *
     * @return int
     */
    public function getCostume1()
    {
        return isset($this->costume_1) ? $this->costume_1 : 0;
    }

    public function hasCostume1()
    {
        return isset($this->costume_1);
    }

    public function clearCostume1()
    {
        unset($this->costume_1);
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_1 = 1;</code>
     *
     * @return $this
     */
    public function setCostume1(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->costume_1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_2 = 2;</code>
     *
     * @return int
     */
    public function getCostume2()
    {
        return isset($this->costume_2) ? $this->costume_2 : 0;
    }

    public function hasCostume2()
    {
        return isset($this->costume_2);
    }

    public function clearCostume2()
    {
        unset($this->costume_2);
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_2 = 2;</code>
     *
     * @return $this
     */
    public function setCostume2(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->costume_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_3 = 3;</code>
     *
     * @return int
     */
    public function getCostume3()
    {
        return isset($this->costume_3) ? $this->costume_3 : 0;
    }

    public function hasCostume3()
    {
        return isset($this->costume_3);
    }

    public function clearCostume3()
    {
        unset($this->costume_3);
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_3 = 3;</code>
     *
     * @return $this
     */
    public function setCostume3(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->costume_3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_4 = 4;</code>
     *
     * @return int
     */
    public function getCostume4()
    {
        return isset($this->costume_4) ? $this->costume_4 : 0;
    }

    public function hasCostume4()
    {
        return isset($this->costume_4);
    }

    public function clearCostume4()
    {
        unset($this->costume_4);
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_4 = 4;</code>
     *
     * @return $this
     */
    public function setCostume4(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->costume_4 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_5 = 5;</code>
     *
     * @return int
     */
    public function getCostume5()
    {
        return isset($this->costume_5) ? $this->costume_5 : 0;
    }

    public function hasCostume5()
    {
        return isset($this->costume_5);
    }

    public function clearCostume5()
    {
        unset($this->costume_5);
    }

    /**
     * Generated from protobuf field <code>optional uint32 costume_5 = 5;</code>
     *
     * @return $this
     */
    public function setCostume5(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->costume_5 = $var;

        return $this;
    }
}
