
services:
    laravel.test:
        build:
            context: './docker/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        expose:
            - '8080'
        ports:
            #- '${APP_PORT:-8080}:8080'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            SUPERVISOR_PHP_COMMAND: '/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=8080'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=main'
            - 'traefik.http.routers.taikonline.entrypoints=websecure'
            - 'traefik.http.routers.taikonline.rule=Host(`taiko.silvaserv.it`)'
            - 'traefik.http.routers.taikonline.tls=true'
            - 'traefik.http.routers.taikonline.tls.certresolver=lets-encrypt'
            - 'traefik.http.routers.taikonline.service=taikonline'
            - 'traefik.http.services.taikonline.loadbalancer.server.port=8080'
            # - 'traefik.http.routers.taikonline.middlewares=strip-cabinet-headers'

            # - 'traefik.http.middlewares.strip-cabinet-headers.headers.customresponseheaders.Host='
            # - 'traefik.http.middlewares.strip-cabinet-headers.headers.customresponseheaders.X-Powered-By='
            # - 'traefik.http.middlewares.strip-cabinet-headers.headers.customresponseheaders.Cache-Control='
            # - 'traefik.http.middlewares.strip-cabinet-headers.headers.customresponseheaders.Expires='
            # - 'traefik.http.middlewares.strip-cabinet-headers.headers.customresponseheaders.Pragma='

        networks:
            main:
                aliases:
                    - laravel-app
        depends_on:
            - pgsql

    pgsql:
        image: 'postgres:18-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - main
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s


networks:
    main:
        external: true
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
