<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Kimidori\Taiko;

use App\GameProtocol\Green\Proto\Kimidori\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.kimidori.BAIDRequest</code>
 */
class BAIDRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 device_type = 1;</code>
     */
    protected $device_type = null;

    /**
     * Generated from protobuf field <code>optional string access_code = 2;</code>
     */
    protected $access_code = null;

    /**
     * Generated from protobuf field <code>optional string chip_id = 3;</code>
     */
    protected $chip_id = null;

    /**
     * Generated from protobuf field <code>optional string chassis_id = 4;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 5;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional string country_id = 6;</code>
     */
    protected $country_id = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $device_type
     * @type string $access_code
     * @type string $chip_id
     * @type string $chassis_id
     * @type string $shop_id
     * @type string $country_id
     *              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 device_type = 1;</code>
     *
     * @return int
     */
    public function getDeviceType()
    {
        return isset($this->device_type) ? $this->device_type : 0;
    }

    public function hasDeviceType()
    {
        return isset($this->device_type);
    }

    public function clearDeviceType()
    {
        unset($this->device_type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 device_type = 1;</code>
     *
     * @return $this
     */
    public function setDeviceType(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->device_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string access_code = 2;</code>
     *
     * @return string
     */
    public function getAccessCode()
    {
        return isset($this->access_code) ? $this->access_code : '';
    }

    public function hasAccessCode()
    {
        return isset($this->access_code);
    }

    public function clearAccessCode()
    {
        unset($this->access_code);
    }

    /**
     * Generated from protobuf field <code>optional string access_code = 2;</code>
     *
     * @return $this
     */
    public function setAccessCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->access_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chip_id = 3;</code>
     *
     * @return string
     */
    public function getChipId()
    {
        return isset($this->chip_id) ? $this->chip_id : '';
    }

    public function hasChipId()
    {
        return isset($this->chip_id);
    }

    public function clearChipId()
    {
        unset($this->chip_id);
    }

    /**
     * Generated from protobuf field <code>optional string chip_id = 3;</code>
     *
     * @return $this
     */
    public function setChipId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chip_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 4;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 4;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 5;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 5;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string country_id = 6;</code>
     *
     * @return string
     */
    public function getCountryId()
    {
        return isset($this->country_id) ? $this->country_id : '';
    }

    public function hasCountryId()
    {
        return isset($this->country_id);
    }

    public function clearCountryId()
    {
        unset($this->country_id);
    }

    /**
     * Generated from protobuf field <code>optional string country_id = 6;</code>
     *
     * @return $this
     */
    public function setCountryId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->country_id = $var;

        return $this;
    }
}
