<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Kimidori\Taiko;

use App\GameProtocol\Green\Proto\Kimidori\Metadata\Taiko;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.kimidori.SelfBestRequest</code>
 */
class SelfBestRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 level = 3;</code>
     */
    protected $level = null;

    /**
     * Generated from protobuf field <code>repeated uint32 ary_song_no = 4;</code>
     */
    private $ary_song_no;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $baid
     * @type string $chassis_id
     * @type int $level
     * @type int[] $ary_song_no
     *             }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 3;</code>
     *
     * @return int
     */
    public function getLevel()
    {
        return isset($this->level) ? $this->level : 0;
    }

    public function hasLevel()
    {
        return isset($this->level);
    }

    public function clearLevel()
    {
        unset($this->level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 3;</code>
     *
     * @return $this
     */
    public function setLevel(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ary_song_no = 4;</code>
     *
     * @return RepeatedField<int>
     */
    public function getArySongNo()
    {
        return $this->ary_song_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ary_song_no = 4;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setArySongNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->ary_song_no = $arr;

        return $this;
    }
}
