<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Blue\Taiko\PlayResultRequest;

use App\GameProtocol\Proto\Blue\Metadata\Taiko;
use App\GameProtocol\Proto\Blue\Taiko\PlayResultRequest\ReleaseBattleData\BattleTokenData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.blue.PlayResultRequest.ReleaseBattleData</code>
 */
class ReleaseBattleData extends Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 release_info_id = 1;</code>
     */
    private $release_info_id;

    /**
     * Generated from protobuf field <code>repeated uint32 release_battle_stage_id = 2;</code>
     */
    private $release_battle_stage_id;

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_id = 3;</code>
     */
    private $release_npc_id;

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_costume_id = 4;</code>
     */
    private $release_npc_costume_id;

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_special_id = 5;</code>
     */
    private $release_npc_special_id;

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.PlayResultRequest.ReleaseBattleData.BattleTokenData ary_battletokendata = 6;</code>
     */
    private $ary_battletokendata;

    /**
     * Generated from protobuf field <code>optional uint32 assign_next_stage_id = 7;</code>
     */
    protected $assign_next_stage_id = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int[] $release_info_id
     * @type int[] $release_battle_stage_id
     * @type int[] $release_npc_id
     * @type int[] $release_npc_costume_id
     * @type int[] $release_npc_special_id
     * @type \App\GameProtocol\Proto\Blue\Taiko\PlayResultRequest\ReleaseBattleData\BattleTokenData[] $ary_battletokendata
     * @type int $assign_next_stage_id
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_info_id = 1;</code>
     *
     * @return RepeatedField<int>
     */
    public function getReleaseInfoId()
    {
        return $this->release_info_id;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_info_id = 1;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setReleaseInfoId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->release_info_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_battle_stage_id = 2;</code>
     *
     * @return RepeatedField<int>
     */
    public function getReleaseBattleStageId()
    {
        return $this->release_battle_stage_id;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_battle_stage_id = 2;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setReleaseBattleStageId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->release_battle_stage_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_id = 3;</code>
     *
     * @return RepeatedField<int>
     */
    public function getReleaseNpcId()
    {
        return $this->release_npc_id;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_id = 3;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setReleaseNpcId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->release_npc_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_costume_id = 4;</code>
     *
     * @return RepeatedField<int>
     */
    public function getReleaseNpcCostumeId()
    {
        return $this->release_npc_costume_id;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_costume_id = 4;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setReleaseNpcCostumeId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->release_npc_costume_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_special_id = 5;</code>
     *
     * @return RepeatedField<int>
     */
    public function getReleaseNpcSpecialId()
    {
        return $this->release_npc_special_id;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_npc_special_id = 5;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setReleaseNpcSpecialId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->release_npc_special_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.PlayResultRequest.ReleaseBattleData.BattleTokenData ary_battletokendata = 6;</code>
     *
     * @return RepeatedField<BattleTokenData>
     */
    public function getAryBattletokendata()
    {
        return $this->ary_battletokendata;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.PlayResultRequest.ReleaseBattleData.BattleTokenData ary_battletokendata = 6;</code>
     *
     * @param  BattleTokenData[]  $var
     * @return $this
     */
    public function setAryBattletokendata(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, BattleTokenData::class);
        $this->ary_battletokendata = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 assign_next_stage_id = 7;</code>
     *
     * @return int
     */
    public function getAssignNextStageId()
    {
        return isset($this->assign_next_stage_id) ? $this->assign_next_stage_id : 0;
    }

    public function hasAssignNextStageId()
    {
        return isset($this->assign_next_stage_id);
    }

    public function clearAssignNextStageId()
    {
        unset($this->assign_next_stage_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 assign_next_stage_id = 7;</code>
     *
     * @return $this
     */
    public function setAssignNextStageId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->assign_next_stage_id = $var;

        return $this;
    }
}
