<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Blue\Taiko\PlayResultRequest;

use App\GameProtocol\Proto\Blue\Metadata\Taiko;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.blue.PlayResultRequest.TokkunstageData</code>
 */
class TokkunstageData extends Message
{
    /**
     * Generated from protobuf field <code>optional string banacoin_datetime = 1;</code>
     */
    protected $banacoin_datetime = null;

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_song_cnt = 2;</code>
     */
    protected $tokkun_song_cnt = null;

    /**
     * Generated from protobuf field <code>repeated uint32 tookun_songno = 3;</code>
     */
    private $tookun_songno;

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_speedchange_cnt = 4;</code>
     */
    protected $tokkun_speedchange_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_autoplay_cnt = 5;</code>
     */
    protected $tokkun_autoplay_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_jump_cnt = 6;</code>
     */
    protected $tokkun_jump_cnt = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $banacoin_datetime
     * @type int $tokkun_song_cnt
     * @type int[] $tookun_songno
     * @type int $tokkun_speedchange_cnt
     * @type int $tokkun_autoplay_cnt
     * @type int $tokkun_jump_cnt
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string banacoin_datetime = 1;</code>
     *
     * @return string
     */
    public function getBanacoinDatetime()
    {
        return isset($this->banacoin_datetime) ? $this->banacoin_datetime : '';
    }

    public function hasBanacoinDatetime()
    {
        return isset($this->banacoin_datetime);
    }

    public function clearBanacoinDatetime()
    {
        unset($this->banacoin_datetime);
    }

    /**
     * Generated from protobuf field <code>optional string banacoin_datetime = 1;</code>
     *
     * @return $this
     */
    public function setBanacoinDatetime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->banacoin_datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_song_cnt = 2;</code>
     *
     * @return int
     */
    public function getTokkunSongCnt()
    {
        return isset($this->tokkun_song_cnt) ? $this->tokkun_song_cnt : 0;
    }

    public function hasTokkunSongCnt()
    {
        return isset($this->tokkun_song_cnt);
    }

    public function clearTokkunSongCnt()
    {
        unset($this->tokkun_song_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_song_cnt = 2;</code>
     *
     * @return $this
     */
    public function setTokkunSongCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->tokkun_song_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tookun_songno = 3;</code>
     *
     * @return RepeatedField<int>
     */
    public function getTookunSongno()
    {
        return $this->tookun_songno;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tookun_songno = 3;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setTookunSongno(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->tookun_songno = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_speedchange_cnt = 4;</code>
     *
     * @return int
     */
    public function getTokkunSpeedchangeCnt()
    {
        return isset($this->tokkun_speedchange_cnt) ? $this->tokkun_speedchange_cnt : 0;
    }

    public function hasTokkunSpeedchangeCnt()
    {
        return isset($this->tokkun_speedchange_cnt);
    }

    public function clearTokkunSpeedchangeCnt()
    {
        unset($this->tokkun_speedchange_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_speedchange_cnt = 4;</code>
     *
     * @return $this
     */
    public function setTokkunSpeedchangeCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->tokkun_speedchange_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_autoplay_cnt = 5;</code>
     *
     * @return int
     */
    public function getTokkunAutoplayCnt()
    {
        return isset($this->tokkun_autoplay_cnt) ? $this->tokkun_autoplay_cnt : 0;
    }

    public function hasTokkunAutoplayCnt()
    {
        return isset($this->tokkun_autoplay_cnt);
    }

    public function clearTokkunAutoplayCnt()
    {
        unset($this->tokkun_autoplay_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_autoplay_cnt = 5;</code>
     *
     * @return $this
     */
    public function setTokkunAutoplayCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->tokkun_autoplay_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_jump_cnt = 6;</code>
     *
     * @return int
     */
    public function getTokkunJumpCnt()
    {
        return isset($this->tokkun_jump_cnt) ? $this->tokkun_jump_cnt : 0;
    }

    public function hasTokkunJumpCnt()
    {
        return isset($this->tokkun_jump_cnt);
    }

    public function clearTokkunJumpCnt()
    {
        unset($this->tokkun_jump_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_jump_cnt = 6;</code>
     *
     * @return $this
     */
    public function setTokkunJumpCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->tokkun_jump_cnt = $var;

        return $this;
    }
}
