<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Momoiro\Taiko\BestScoreResponse\SongData\Best3Data;

use App\GameProtocol\Green\Proto\Momoiro\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.momoiro.BestScoreResponse.SongData.Best3Data.RankData</code>
 */
class RankData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 high_score = 1;</code>
     */
    protected $high_score = null;

    /**
     * Generated from protobuf field <code>optional string mydon_name = 2;</code>
     */
    protected $mydon_name = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $high_score
     * @type string $mydon_name
     *              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 high_score = 1;</code>
     *
     * @return int
     */
    public function getHighScore()
    {
        return isset($this->high_score) ? $this->high_score : 0;
    }

    public function hasHighScore()
    {
        return isset($this->high_score);
    }

    public function clearHighScore()
    {
        unset($this->high_score);
    }

    /**
     * Generated from protobuf field <code>optional uint32 high_score = 1;</code>
     *
     * @return $this
     */
    public function setHighScore(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->high_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string mydon_name = 2;</code>
     *
     * @return string
     */
    public function getMydonName()
    {
        return isset($this->mydon_name) ? $this->mydon_name : '';
    }

    public function hasMydonName()
    {
        return isset($this->mydon_name);
    }

    public function clearMydonName()
    {
        unset($this->mydon_name);
    }

    /**
     * Generated from protobuf field <code>optional string mydon_name = 2;</code>
     *
     * @return $this
     */
    public function setMydonName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->mydon_name = $var;

        return $this;
    }
}
