<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Green\Taiko;

use App\GameProtocol\Proto\Green\Metadata\Taiko;
use App\GameProtocol\Proto\Green\Taiko\GetghostdataResponse\GhostPerfData;
use App\GameProtocol\Proto\Green\Taiko\GetghostdataResponse\GhostRankData;
use App\GameProtocol\Proto\Green\Taiko\GetghostdataResponse\GhostTokenData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.green.GetghostdataResponse</code>
 */
class GetghostdataResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional bytes release_info_flag = 2;</code>
     */
    protected $release_info_flag = null;

    /**
     * Generated from protobuf field <code>optional bytes played_song_flag = 3;</code>
     */
    protected $played_song_flag = null;

    /**
     * Generated from protobuf field <code>optional uint32 total_winnings = 4;</code>
     */
    protected $total_winnings = null;

    /**
     * Generated from protobuf field <code>optional .taiko.green.GetghostdataResponse.GhostPerfData ghost_perf_data = 5;</code>
     */
    protected $ghost_perf_data = null;

    /**
     * Generated from protobuf field <code>optional .taiko.green.GetghostdataResponse.GhostRankData ghost_record_data = 6;</code>
     */
    protected $ghost_record_data = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.green.GetghostdataResponse.GhostTokenData ary_token_data = 7;</code>
     */
    private $ary_token_data;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type string $release_info_flag
     * @type string $played_song_flag
     * @type int $total_winnings
     * @type \App\GameProtocol\Proto\Green\Taiko\GetghostdataResponse\GhostPerfData $ghost_perf_data
     * @type \App\GameProtocol\Proto\Green\Taiko\GetghostdataResponse\GhostRankData $ghost_record_data
     * @type \App\GameProtocol\Proto\Green\Taiko\GetghostdataResponse\GhostTokenData[] $ary_token_data
     *                                                                                 }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes release_info_flag = 2;</code>
     *
     * @return string
     */
    public function getReleaseInfoFlag()
    {
        return isset($this->release_info_flag) ? $this->release_info_flag : '';
    }

    public function hasReleaseInfoFlag()
    {
        return isset($this->release_info_flag);
    }

    public function clearReleaseInfoFlag()
    {
        unset($this->release_info_flag);
    }

    /**
     * Generated from protobuf field <code>optional bytes release_info_flag = 2;</code>
     *
     * @return $this
     */
    public function setReleaseInfoFlag(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->release_info_flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes played_song_flag = 3;</code>
     *
     * @return string
     */
    public function getPlayedSongFlag()
    {
        return isset($this->played_song_flag) ? $this->played_song_flag : '';
    }

    public function hasPlayedSongFlag()
    {
        return isset($this->played_song_flag);
    }

    public function clearPlayedSongFlag()
    {
        unset($this->played_song_flag);
    }

    /**
     * Generated from protobuf field <code>optional bytes played_song_flag = 3;</code>
     *
     * @return $this
     */
    public function setPlayedSongFlag(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->played_song_flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 total_winnings = 4;</code>
     *
     * @return int
     */
    public function getTotalWinnings()
    {
        return isset($this->total_winnings) ? $this->total_winnings : 0;
    }

    public function hasTotalWinnings()
    {
        return isset($this->total_winnings);
    }

    public function clearTotalWinnings()
    {
        unset($this->total_winnings);
    }

    /**
     * Generated from protobuf field <code>optional uint32 total_winnings = 4;</code>
     *
     * @return $this
     */
    public function setTotalWinnings(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->total_winnings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .taiko.green.GetghostdataResponse.GhostPerfData ghost_perf_data = 5;</code>
     *
     * @return GhostPerfData|null
     */
    public function getGhostPerfData()
    {
        return $this->ghost_perf_data;
    }

    public function hasGhostPerfData()
    {
        return isset($this->ghost_perf_data);
    }

    public function clearGhostPerfData()
    {
        unset($this->ghost_perf_data);
    }

    /**
     * Generated from protobuf field <code>optional .taiko.green.GetghostdataResponse.GhostPerfData ghost_perf_data = 5;</code>
     *
     * @return $this
     */
    public function setGhostPerfData(?GhostPerfData $var)
    {
        $this->ghost_perf_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .taiko.green.GetghostdataResponse.GhostRankData ghost_record_data = 6;</code>
     *
     * @return GhostRankData|null
     */
    public function getGhostRecordData()
    {
        return $this->ghost_record_data;
    }

    public function hasGhostRecordData()
    {
        return isset($this->ghost_record_data);
    }

    public function clearGhostRecordData()
    {
        unset($this->ghost_record_data);
    }

    /**
     * Generated from protobuf field <code>optional .taiko.green.GetghostdataResponse.GhostRankData ghost_record_data = 6;</code>
     *
     * @return $this
     */
    public function setGhostRecordData(?GhostRankData $var)
    {
        $this->ghost_record_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.GetghostdataResponse.GhostTokenData ary_token_data = 7;</code>
     *
     * @return RepeatedField<GhostTokenData>
     */
    public function getAryTokenData()
    {
        return $this->ary_token_data;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.GetghostdataResponse.GhostTokenData ary_token_data = 7;</code>
     *
     * @param  GhostTokenData[]  $var
     * @return $this
     */
    public function setAryTokenData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, GhostTokenData::class);
        $this->ary_token_data = $arr;

        return $this;
    }
}
