<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_green.proto

namespace App\GameProtocol\Proto\Green\Taiko;

use App\GameProtocol\Proto\Green\Metadata\TaikoGreen;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.green.PlayResultResponse</code>
 */
class PlayResultResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     *           }
     */
    public function __construct($data = null)
    {
        TaikoGreen::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }
}
