<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Green\Taiko;

use App\GameProtocol\Proto\Green\Metadata\Taiko;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.green.RewardexecutionRequest</code>
 */
class RewardexecutionRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>repeated uint32 release_song_no = 4;</code>
     */
    private $release_song_no;

    /**
     * Generated from protobuf field <code>repeated uint32 get_tone_no = 5;</code>
     */
    private $get_tone_no;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_1 = 6;</code>
     */
    private $get_costume_no_1;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_2 = 7;</code>
     */
    private $get_costume_no_2;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_3 = 8;</code>
     */
    private $get_costume_no_3;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_4 = 9;</code>
     */
    private $get_costume_no_4;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_5 = 10;</code>
     */
    private $get_costume_no_5;

    /**
     * Generated from protobuf field <code>repeated uint32 get_title_no = 11;</code>
     */
    private $get_title_no;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $baid
     * @type string $chassis_id
     * @type string $shop_id
     * @type int[] $release_song_no
     * @type int[] $get_tone_no
     * @type int[] $get_costume_no_1
     * @type int[] $get_costume_no_2
     * @type int[] $get_costume_no_3
     * @type int[] $get_costume_no_4
     * @type int[] $get_costume_no_5
     * @type int[] $get_title_no
     *             }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_song_no = 4;</code>
     *
     * @return RepeatedField<int>
     */
    public function getReleaseSongNo()
    {
        return $this->release_song_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_song_no = 4;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setReleaseSongNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->release_song_no = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_tone_no = 5;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetToneNo()
    {
        return $this->get_tone_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_tone_no = 5;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetToneNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_tone_no = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_1 = 6;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo1()
    {
        return $this->get_costume_no_1;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_1 = 6;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo1(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_1 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_2 = 7;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo2()
    {
        return $this->get_costume_no_2;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_2 = 7;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo2(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_2 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_3 = 8;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo3()
    {
        return $this->get_costume_no_3;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_3 = 8;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo3(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_3 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_4 = 9;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo4()
    {
        return $this->get_costume_no_4;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_4 = 9;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo4(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_4 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_5 = 10;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo5()
    {
        return $this->get_costume_no_5;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_5 = 10;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo5(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_5 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_title_no = 11;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetTitleNo()
    {
        return $this->get_title_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_title_no = 11;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetTitleNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_title_no = $arr;

        return $this;
    }
}
