<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_green.proto

namespace App\GameProtocol\Proto\Green\Taiko;

use App\GameProtocol\Proto\Green\Metadata\TaikoGreen;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.green.TournamentcheckRequest</code>
 */
class TournamentcheckRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 kit_id = 3;</code>
     */
    protected $kit_id = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type string $shop_id
     * @type int $kit_id
     *           }
     */
    public function __construct($data = null)
    {
        TaikoGreen::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 kit_id = 3;</code>
     *
     * @return int
     */
    public function getKitId()
    {
        return isset($this->kit_id) ? $this->kit_id : 0;
    }

    public function hasKitId()
    {
        return isset($this->kit_id);
    }

    public function clearKitId()
    {
        unset($this->kit_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 kit_id = 3;</code>
     *
     * @return $this
     */
    public function setKitId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->kit_id = $var;

        return $this;
    }
}
