<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_kimidori.proto

namespace App\GameProtocol\Proto\Kimidori\Taiko\UserDataResponse;

use App\GameProtocol\Proto\Kimidori\Metadata\TaikoKimidori;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.kimidori.UserDataResponse.FriendInfo</code>
 */
class FriendInfo extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional string friend_name = 2;</code>
     */
    protected $friend_name = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $baid
     * @type string $friend_name
     *              }
     */
    public function __construct($data = null)
    {
        TaikoKimidori::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string friend_name = 2;</code>
     *
     * @return string
     */
    public function getFriendName()
    {
        return isset($this->friend_name) ? $this->friend_name : '';
    }

    public function hasFriendName()
    {
        return isset($this->friend_name);
    }

    public function clearFriendName()
    {
        unset($this->friend_name);
    }

    /**
     * Generated from protobuf field <code>optional string friend_name = 2;</code>
     *
     * @return $this
     */
    public function setFriendName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->friend_name = $var;

        return $this;
    }
}
