<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_katsudon.proto

namespace App\GameProtocol\Proto\Katsudon\Taiko\SongInfoResponse\GroupData;

use App\GameProtocol\Proto\Katsudon\Metadata\TaikoKatsudon;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.katsudon.SongInfoResponse.GroupData.FriendData</code>
 */
class FriendData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     */
    protected $level = null;

    /**
     * Generated from protobuf field <code>optional uint32 high_score = 3;</code>
     */
    protected $high_score = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $baid
     * @type int $level
     * @type int $high_score
     *           }
     */
    public function __construct($data = null)
    {
        TaikoKatsudon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     *
     * @return int
     */
    public function getLevel()
    {
        return isset($this->level) ? $this->level : 0;
    }

    public function hasLevel()
    {
        return isset($this->level);
    }

    public function clearLevel()
    {
        unset($this->level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     *
     * @return $this
     */
    public function setLevel(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 high_score = 3;</code>
     *
     * @return int
     */
    public function getHighScore()
    {
        return isset($this->high_score) ? $this->high_score : 0;
    }

    public function hasHighScore()
    {
        return isset($this->high_score);
    }

    public function clearHighScore()
    {
        unset($this->high_score);
    }

    /**
     * Generated from protobuf field <code>optional uint32 high_score = 3;</code>
     *
     * @return $this
     */
    public function setHighScore(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->high_score = $var;

        return $this;
    }
}
