<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest;

use App\GameProtocol\Proto\Green\Metadata\Taiko;
use App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData\GhostStageData;
use App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData\ResultcompeData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.green.PlayResultDataRequest.StageData</code>
 */
class StageData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     */
    protected $song_no = null;

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     */
    protected $level = null;

    /**
     * Generated from protobuf field <code>optional uint32 play_result = 3;</code>
     */
    protected $play_result = null;

    /**
     * Generated from protobuf field <code>optional uint32 play_score = 4;</code>
     */
    protected $play_score = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_challenge_id = 5;</code>
     */
    private $ary_challenge_id;

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_user_compe_id = 6;</code>
     */
    private $ary_user_compe_id;

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_bng_compe_id = 7;</code>
     */
    private $ary_bng_compe_id;

    /**
     * Generated from protobuf field <code>optional uint32 good_cnt = 8;</code>
     */
    protected $good_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 ok_cnt = 9;</code>
     */
    protected $ok_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 ng_cnt = 10;</code>
     */
    protected $ng_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 pound_cnt = 11;</code>
     */
    protected $pound_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 combo_cnt = 12;</code>
     */
    protected $combo_cnt = null;

    /**
     * Generated from protobuf field <code>optional bytes option_flg = 13;</code>
     */
    protected $option_flg = null;

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 14;</code>
     */
    protected $tone_flg = null;

    /**
     * Generated from protobuf field <code>optional uint32 music_categ = 15;</code>
     */
    protected $music_categ = null;

    /**
     * Generated from protobuf field <code>optional bool is_pushed = 16;</code>
     */
    protected $is_pushed = null;

    /**
     * Generated from protobuf field <code>optional bool is_favorite = 17;</code>
     */
    protected $is_favorite = null;

    /**
     * Generated from protobuf field <code>optional bool is_recent = 18;</code>
     */
    protected $is_recent = null;

    /**
     * Generated from protobuf field <code>optional bool is_papamama = 19;</code>
     */
    protected $is_papamama = null;

    /**
     * Generated from protobuf field <code>optional uint32 play_dan = 20;</code>
     */
    protected $play_dan = null;

    /**
     * Generated from protobuf field <code>optional uint32 soul_gauge = 21;</code>
     */
    protected $soul_gauge = null;

    /**
     * Generated from protobuf field <code>optional uint32 hit_cnt = 22;</code>
     */
    protected $hit_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 stage_mode = 23;</code>
     */
    protected $stage_mode = null;

    /**
     * Generated from protobuf field <code>optional uint32 selected_folder_id = 24;</code>
     */
    protected $selected_folder_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 waiwai_result = 25;</code>
     */
    protected $waiwai_result = null;

    /**
     * Generated from protobuf field <code>optional uint32 waiwai_gauge = 26;</code>
     */
    protected $waiwai_gauge = null;

    /**
     * Generated from protobuf field <code>optional uint32 star_level = 27;</code>
     */
    protected $star_level = null;

    /**
     * Generated from protobuf field <code>optional uint32 support_level = 28;</code>
     */
    protected $support_level = null;

    /**
     * Generated from protobuf field <code>optional .taiko.green.PlayResultDataRequest.StageData.GhostStageData ghost_stagedata = 29;</code>
     */
    protected $ghost_stagedata = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $song_no
     * @type int $level
     * @type int $play_result
     * @type int $play_score
     * @type \App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData\ResultcompeData[] $ary_challenge_id
     * @type \App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData\ResultcompeData[] $ary_user_compe_id
     * @type \App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData\ResultcompeData[] $ary_bng_compe_id
     * @type int $good_cnt
     * @type int $ok_cnt
     * @type int $ng_cnt
     * @type int $pound_cnt
     * @type int $combo_cnt
     * @type string $option_flg
     * @type string $tone_flg
     * @type int $music_categ
     * @type bool $is_pushed
     * @type bool $is_favorite
     * @type bool $is_recent
     * @type bool $is_papamama
     * @type int $play_dan
     * @type int $soul_gauge
     * @type int $hit_cnt
     * @type int $stage_mode
     * @type int $selected_folder_id
     * @type int $waiwai_result
     * @type int $waiwai_gauge
     * @type int $star_level
     * @type int $support_level
     * @type \App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData\GhostStageData $ghost_stagedata
     *                                                                                          }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     *
     * @return int
     */
    public function getSongNo()
    {
        return isset($this->song_no) ? $this->song_no : 0;
    }

    public function hasSongNo()
    {
        return isset($this->song_no);
    }

    public function clearSongNo()
    {
        unset($this->song_no);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     *
     * @return $this
     */
    public function setSongNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->song_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     *
     * @return int
     */
    public function getLevel()
    {
        return isset($this->level) ? $this->level : 0;
    }

    public function hasLevel()
    {
        return isset($this->level);
    }

    public function clearLevel()
    {
        unset($this->level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     *
     * @return $this
     */
    public function setLevel(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_result = 3;</code>
     *
     * @return int
     */
    public function getPlayResult()
    {
        return isset($this->play_result) ? $this->play_result : 0;
    }

    public function hasPlayResult()
    {
        return isset($this->play_result);
    }

    public function clearPlayResult()
    {
        unset($this->play_result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_result = 3;</code>
     *
     * @return $this
     */
    public function setPlayResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->play_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_score = 4;</code>
     *
     * @return int
     */
    public function getPlayScore()
    {
        return isset($this->play_score) ? $this->play_score : 0;
    }

    public function hasPlayScore()
    {
        return isset($this->play_score);
    }

    public function clearPlayScore()
    {
        unset($this->play_score);
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_score = 4;</code>
     *
     * @return $this
     */
    public function setPlayScore(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->play_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_challenge_id = 5;</code>
     *
     * @return RepeatedField<ResultcompeData>
     */
    public function getAryChallengeId()
    {
        return $this->ary_challenge_id;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_challenge_id = 5;</code>
     *
     * @param  ResultcompeData[]  $var
     * @return $this
     */
    public function setAryChallengeId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ResultcompeData::class);
        $this->ary_challenge_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_user_compe_id = 6;</code>
     *
     * @return RepeatedField<ResultcompeData>
     */
    public function getAryUserCompeId()
    {
        return $this->ary_user_compe_id;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_user_compe_id = 6;</code>
     *
     * @param  ResultcompeData[]  $var
     * @return $this
     */
    public function setAryUserCompeId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ResultcompeData::class);
        $this->ary_user_compe_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_bng_compe_id = 7;</code>
     *
     * @return RepeatedField<ResultcompeData>
     */
    public function getAryBngCompeId()
    {
        return $this->ary_bng_compe_id;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.ResultcompeData ary_bng_compe_id = 7;</code>
     *
     * @param  ResultcompeData[]  $var
     * @return $this
     */
    public function setAryBngCompeId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ResultcompeData::class);
        $this->ary_bng_compe_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 good_cnt = 8;</code>
     *
     * @return int
     */
    public function getGoodCnt()
    {
        return isset($this->good_cnt) ? $this->good_cnt : 0;
    }

    public function hasGoodCnt()
    {
        return isset($this->good_cnt);
    }

    public function clearGoodCnt()
    {
        unset($this->good_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 good_cnt = 8;</code>
     *
     * @return $this
     */
    public function setGoodCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->good_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 ok_cnt = 9;</code>
     *
     * @return int
     */
    public function getOkCnt()
    {
        return isset($this->ok_cnt) ? $this->ok_cnt : 0;
    }

    public function hasOkCnt()
    {
        return isset($this->ok_cnt);
    }

    public function clearOkCnt()
    {
        unset($this->ok_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 ok_cnt = 9;</code>
     *
     * @return $this
     */
    public function setOkCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->ok_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 ng_cnt = 10;</code>
     *
     * @return int
     */
    public function getNgCnt()
    {
        return isset($this->ng_cnt) ? $this->ng_cnt : 0;
    }

    public function hasNgCnt()
    {
        return isset($this->ng_cnt);
    }

    public function clearNgCnt()
    {
        unset($this->ng_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 ng_cnt = 10;</code>
     *
     * @return $this
     */
    public function setNgCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->ng_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pound_cnt = 11;</code>
     *
     * @return int
     */
    public function getPoundCnt()
    {
        return isset($this->pound_cnt) ? $this->pound_cnt : 0;
    }

    public function hasPoundCnt()
    {
        return isset($this->pound_cnt);
    }

    public function clearPoundCnt()
    {
        unset($this->pound_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pound_cnt = 11;</code>
     *
     * @return $this
     */
    public function setPoundCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->pound_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 combo_cnt = 12;</code>
     *
     * @return int
     */
    public function getComboCnt()
    {
        return isset($this->combo_cnt) ? $this->combo_cnt : 0;
    }

    public function hasComboCnt()
    {
        return isset($this->combo_cnt);
    }

    public function clearComboCnt()
    {
        unset($this->combo_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 combo_cnt = 12;</code>
     *
     * @return $this
     */
    public function setComboCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->combo_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes option_flg = 13;</code>
     *
     * @return string
     */
    public function getOptionFlg()
    {
        return isset($this->option_flg) ? $this->option_flg : '';
    }

    public function hasOptionFlg()
    {
        return isset($this->option_flg);
    }

    public function clearOptionFlg()
    {
        unset($this->option_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes option_flg = 13;</code>
     *
     * @return $this
     */
    public function setOptionFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->option_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 14;</code>
     *
     * @return string
     */
    public function getToneFlg()
    {
        return isset($this->tone_flg) ? $this->tone_flg : '';
    }

    public function hasToneFlg()
    {
        return isset($this->tone_flg);
    }

    public function clearToneFlg()
    {
        unset($this->tone_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 14;</code>
     *
     * @return $this
     */
    public function setToneFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->tone_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 music_categ = 15;</code>
     *
     * @return int
     */
    public function getMusicCateg()
    {
        return isset($this->music_categ) ? $this->music_categ : 0;
    }

    public function hasMusicCateg()
    {
        return isset($this->music_categ);
    }

    public function clearMusicCateg()
    {
        unset($this->music_categ);
    }

    /**
     * Generated from protobuf field <code>optional uint32 music_categ = 15;</code>
     *
     * @return $this
     */
    public function setMusicCateg(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->music_categ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_pushed = 16;</code>
     *
     * @return bool
     */
    public function getIsPushed()
    {
        return isset($this->is_pushed) ? $this->is_pushed : false;
    }

    public function hasIsPushed()
    {
        return isset($this->is_pushed);
    }

    public function clearIsPushed()
    {
        unset($this->is_pushed);
    }

    /**
     * Generated from protobuf field <code>optional bool is_pushed = 16;</code>
     *
     * @return $this
     */
    public function setIsPushed(bool $var)
    {
        $this->is_pushed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_favorite = 17;</code>
     *
     * @return bool
     */
    public function getIsFavorite()
    {
        return isset($this->is_favorite) ? $this->is_favorite : false;
    }

    public function hasIsFavorite()
    {
        return isset($this->is_favorite);
    }

    public function clearIsFavorite()
    {
        unset($this->is_favorite);
    }

    /**
     * Generated from protobuf field <code>optional bool is_favorite = 17;</code>
     *
     * @return $this
     */
    public function setIsFavorite(bool $var)
    {
        $this->is_favorite = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_recent = 18;</code>
     *
     * @return bool
     */
    public function getIsRecent()
    {
        return isset($this->is_recent) ? $this->is_recent : false;
    }

    public function hasIsRecent()
    {
        return isset($this->is_recent);
    }

    public function clearIsRecent()
    {
        unset($this->is_recent);
    }

    /**
     * Generated from protobuf field <code>optional bool is_recent = 18;</code>
     *
     * @return $this
     */
    public function setIsRecent(bool $var)
    {
        $this->is_recent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_papamama = 19;</code>
     *
     * @return bool
     */
    public function getIsPapamama()
    {
        return isset($this->is_papamama) ? $this->is_papamama : false;
    }

    public function hasIsPapamama()
    {
        return isset($this->is_papamama);
    }

    public function clearIsPapamama()
    {
        unset($this->is_papamama);
    }

    /**
     * Generated from protobuf field <code>optional bool is_papamama = 19;</code>
     *
     * @return $this
     */
    public function setIsPapamama(bool $var)
    {
        $this->is_papamama = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_dan = 20;</code>
     *
     * @return int
     */
    public function getPlayDan()
    {
        return isset($this->play_dan) ? $this->play_dan : 0;
    }

    public function hasPlayDan()
    {
        return isset($this->play_dan);
    }

    public function clearPlayDan()
    {
        unset($this->play_dan);
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_dan = 20;</code>
     *
     * @return $this
     */
    public function setPlayDan(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->play_dan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 soul_gauge = 21;</code>
     *
     * @return int
     */
    public function getSoulGauge()
    {
        return isset($this->soul_gauge) ? $this->soul_gauge : 0;
    }

    public function hasSoulGauge()
    {
        return isset($this->soul_gauge);
    }

    public function clearSoulGauge()
    {
        unset($this->soul_gauge);
    }

    /**
     * Generated from protobuf field <code>optional uint32 soul_gauge = 21;</code>
     *
     * @return $this
     */
    public function setSoulGauge(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->soul_gauge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 hit_cnt = 22;</code>
     *
     * @return int
     */
    public function getHitCnt()
    {
        return isset($this->hit_cnt) ? $this->hit_cnt : 0;
    }

    public function hasHitCnt()
    {
        return isset($this->hit_cnt);
    }

    public function clearHitCnt()
    {
        unset($this->hit_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 hit_cnt = 22;</code>
     *
     * @return $this
     */
    public function setHitCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->hit_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 stage_mode = 23;</code>
     *
     * @return int
     */
    public function getStageMode()
    {
        return isset($this->stage_mode) ? $this->stage_mode : 0;
    }

    public function hasStageMode()
    {
        return isset($this->stage_mode);
    }

    public function clearStageMode()
    {
        unset($this->stage_mode);
    }

    /**
     * Generated from protobuf field <code>optional uint32 stage_mode = 23;</code>
     *
     * @return $this
     */
    public function setStageMode(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->stage_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 selected_folder_id = 24;</code>
     *
     * @return int
     */
    public function getSelectedFolderId()
    {
        return isset($this->selected_folder_id) ? $this->selected_folder_id : 0;
    }

    public function hasSelectedFolderId()
    {
        return isset($this->selected_folder_id);
    }

    public function clearSelectedFolderId()
    {
        unset($this->selected_folder_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 selected_folder_id = 24;</code>
     *
     * @return $this
     */
    public function setSelectedFolderId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->selected_folder_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 waiwai_result = 25;</code>
     *
     * @return int
     */
    public function getWaiwaiResult()
    {
        return isset($this->waiwai_result) ? $this->waiwai_result : 0;
    }

    public function hasWaiwaiResult()
    {
        return isset($this->waiwai_result);
    }

    public function clearWaiwaiResult()
    {
        unset($this->waiwai_result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 waiwai_result = 25;</code>
     *
     * @return $this
     */
    public function setWaiwaiResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->waiwai_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 waiwai_gauge = 26;</code>
     *
     * @return int
     */
    public function getWaiwaiGauge()
    {
        return isset($this->waiwai_gauge) ? $this->waiwai_gauge : 0;
    }

    public function hasWaiwaiGauge()
    {
        return isset($this->waiwai_gauge);
    }

    public function clearWaiwaiGauge()
    {
        unset($this->waiwai_gauge);
    }

    /**
     * Generated from protobuf field <code>optional uint32 waiwai_gauge = 26;</code>
     *
     * @return $this
     */
    public function setWaiwaiGauge(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->waiwai_gauge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 star_level = 27;</code>
     *
     * @return int
     */
    public function getStarLevel()
    {
        return isset($this->star_level) ? $this->star_level : 0;
    }

    public function hasStarLevel()
    {
        return isset($this->star_level);
    }

    public function clearStarLevel()
    {
        unset($this->star_level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 star_level = 27;</code>
     *
     * @return $this
     */
    public function setStarLevel(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->star_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 support_level = 28;</code>
     *
     * @return int
     */
    public function getSupportLevel()
    {
        return isset($this->support_level) ? $this->support_level : 0;
    }

    public function hasSupportLevel()
    {
        return isset($this->support_level);
    }

    public function clearSupportLevel()
    {
        unset($this->support_level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 support_level = 28;</code>
     *
     * @return $this
     */
    public function setSupportLevel(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->support_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .taiko.green.PlayResultDataRequest.StageData.GhostStageData ghost_stagedata = 29;</code>
     *
     * @return GhostStageData|null
     */
    public function getGhostStagedata()
    {
        return $this->ghost_stagedata;
    }

    public function hasGhostStagedata()
    {
        return isset($this->ghost_stagedata);
    }

    public function clearGhostStagedata()
    {
        unset($this->ghost_stagedata);
    }

    /**
     * Generated from protobuf field <code>optional .taiko.green.PlayResultDataRequest.StageData.GhostStageData ghost_stagedata = 29;</code>
     *
     * @return $this
     */
    public function setGhostStagedata(?GhostStageData $var)
    {
        $this->ghost_stagedata = $var;

        return $this;
    }
}
