<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_green.proto

namespace App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest;

use App\GameProtocol\Proto\Green\Metadata\TaikoGreen;
use App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\UpdateGhostRankData\UpdateGhostWinningsData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.green.PlayResultDataRequest.UpdateGhostRankData</code>
 */
class UpdateGhostRankData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 rank_id = 1;</code>
     */
    protected $rank_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 win_point = 2;</code>
     */
    protected $win_point = null;

    /**
     * Generated from protobuf field <code>optional uint32 certified_level_id = 3;</code>
     */
    protected $certified_level_id = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.UpdateGhostRankData.UpdateGhostWinningsData ary_winnings_data = 4;</code>
     */
    private $ary_winnings_data;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $rank_id
     * @type int $win_point
     * @type int $certified_level_id
     * @type \App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\UpdateGhostRankData\UpdateGhostWinningsData[] $ary_winnings_data
     *                                                                                                               }
     */
    public function __construct($data = null)
    {
        TaikoGreen::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 rank_id = 1;</code>
     *
     * @return int
     */
    public function getRankId()
    {
        return isset($this->rank_id) ? $this->rank_id : 0;
    }

    public function hasRankId()
    {
        return isset($this->rank_id);
    }

    public function clearRankId()
    {
        unset($this->rank_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 rank_id = 1;</code>
     *
     * @return $this
     */
    public function setRankId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->rank_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 win_point = 2;</code>
     *
     * @return int
     */
    public function getWinPoint()
    {
        return isset($this->win_point) ? $this->win_point : 0;
    }

    public function hasWinPoint()
    {
        return isset($this->win_point);
    }

    public function clearWinPoint()
    {
        unset($this->win_point);
    }

    /**
     * Generated from protobuf field <code>optional uint32 win_point = 2;</code>
     *
     * @return $this
     */
    public function setWinPoint(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->win_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 certified_level_id = 3;</code>
     *
     * @return int
     */
    public function getCertifiedLevelId()
    {
        return isset($this->certified_level_id) ? $this->certified_level_id : 0;
    }

    public function hasCertifiedLevelId()
    {
        return isset($this->certified_level_id);
    }

    public function clearCertifiedLevelId()
    {
        unset($this->certified_level_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 certified_level_id = 3;</code>
     *
     * @return $this
     */
    public function setCertifiedLevelId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->certified_level_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.UpdateGhostRankData.UpdateGhostWinningsData ary_winnings_data = 4;</code>
     *
     * @return RepeatedField<UpdateGhostWinningsData>
     */
    public function getAryWinningsData()
    {
        return $this->ary_winnings_data;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.UpdateGhostRankData.UpdateGhostWinningsData ary_winnings_data = 4;</code>
     *
     * @param  UpdateGhostWinningsData[]  $var
     * @return $this
     */
    public function setAryWinningsData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, UpdateGhostWinningsData::class);
        $this->ary_winnings_data = $arr;

        return $this;
    }
}
