<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Green\Taiko;

use App\GameProtocol\Green\Proto\Green\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.green.GetghostscoreRequest</code>
 */
class GetghostscoreRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 baid = 3;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 4;</code>
     */
    protected $song_no = null;

    /**
     * Generated from protobuf field <code>optional uint32 level = 5;</code>
     */
    protected $level = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type string $shop_id
     * @type int $baid
     * @type int $song_no
     * @type int $level
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 3;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 3;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 4;</code>
     *
     * @return int
     */
    public function getSongNo()
    {
        return isset($this->song_no) ? $this->song_no : 0;
    }

    public function hasSongNo()
    {
        return isset($this->song_no);
    }

    public function clearSongNo()
    {
        unset($this->song_no);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 4;</code>
     *
     * @return $this
     */
    public function setSongNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->song_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 5;</code>
     *
     * @return int
     */
    public function getLevel()
    {
        return isset($this->level) ? $this->level : 0;
    }

    public function hasLevel()
    {
        return isset($this->level);
    }

    public function clearLevel()
    {
        unset($this->level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 5;</code>
     *
     * @return $this
     */
    public function setLevel(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }
}
