<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Murasaki\Taiko\TaikojukuResponse\JukupackData;

use App\GameProtocol\Green\Proto\Murasaki\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.murasaki.TaikojukuResponse.JukupackData.JukusongData</code>
 */
class JukusongData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     */
    protected $song_no = null;

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     */
    protected $level = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $song_no
     * @type int $level
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     *
     * @return int
     */
    public function getSongNo()
    {
        return isset($this->song_no) ? $this->song_no : 0;
    }

    public function hasSongNo()
    {
        return isset($this->song_no);
    }

    public function clearSongNo()
    {
        unset($this->song_no);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_no = 1;</code>
     *
     * @return $this
     */
    public function setSongNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->song_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     *
     * @return int
     */
    public function getLevel()
    {
        return isset($this->level) ? $this->level : 0;
    }

    public function hasLevel()
    {
        return isset($this->level);
    }

    public function clearLevel()
    {
        unset($this->level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     *
     * @return $this
     */
    public function setLevel(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }
}
