<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Yellow\Taiko;

use App\GameProtocol\Green\Proto\Yellow\Metadata\Taiko;
use App\GameProtocol\Green\Proto\Yellow\Taiko\GetitemshopinfoResponse\ItemshopData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.yellow.GetitemshopinfoResponse</code>
 */
class GetitemshopinfoResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     */
    protected $verup_no = null;

    /**
     * Generated from protobuf field <code>optional uint32 season_id = 3;</code>
     */
    protected $season_id = null;

    /**
     * Generated from protobuf field <code>optional string telop = 4;</code>
     */
    protected $telop = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.GetitemshopinfoResponse.ItemshopData ary_itemshop_data = 5;</code>
     */
    private $ary_itemshop_data;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $verup_no
     * @type int $season_id
     * @type string $telop
     * @type \App\GameProtocol\Green\Proto\Yellow\Taiko\GetitemshopinfoResponse\ItemshopData[] $ary_itemshop_data
     *                                                                                         }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     *
     * @return int
     */
    public function getVerupNo()
    {
        return isset($this->verup_no) ? $this->verup_no : 0;
    }

    public function hasVerupNo()
    {
        return isset($this->verup_no);
    }

    public function clearVerupNo()
    {
        unset($this->verup_no);
    }

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     *
     * @return $this
     */
    public function setVerupNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->verup_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 season_id = 3;</code>
     *
     * @return int
     */
    public function getSeasonId()
    {
        return isset($this->season_id) ? $this->season_id : 0;
    }

    public function hasSeasonId()
    {
        return isset($this->season_id);
    }

    public function clearSeasonId()
    {
        unset($this->season_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 season_id = 3;</code>
     *
     * @return $this
     */
    public function setSeasonId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->season_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string telop = 4;</code>
     *
     * @return string
     */
    public function getTelop()
    {
        return isset($this->telop) ? $this->telop : '';
    }

    public function hasTelop()
    {
        return isset($this->telop);
    }

    public function clearTelop()
    {
        unset($this->telop);
    }

    /**
     * Generated from protobuf field <code>optional string telop = 4;</code>
     *
     * @return $this
     */
    public function setTelop(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->telop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.GetitemshopinfoResponse.ItemshopData ary_itemshop_data = 5;</code>
     *
     * @return RepeatedField<ItemshopData>
     */
    public function getAryItemshopData()
    {
        return $this->ary_itemshop_data;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.GetitemshopinfoResponse.ItemshopData ary_itemshop_data = 5;</code>
     *
     * @param  ItemshopData[]  $var
     * @return $this
     */
    public function setAryItemshopData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ItemshopData::class);
        $this->ary_itemshop_data = $arr;

        return $this;
    }
}
