<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData;

use App\GameProtocol\Proto\Green\Metadata\Taiko;
use App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData\GhostStageData\GhostStageSectionData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.green.PlayResultDataRequest.StageData.GhostStageData</code>
 */
class GhostStageData extends Message
{
    /**
     * Generated from protobuf field <code>optional bool is_win = 1;</code>
     */
    protected $is_win = null;

    /**
     * Generated from protobuf field <code>optional uint32 sd_certified_level_id = 2;</code>
     */
    protected $sd_certified_level_id = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.GhostStageData.GhostStageSectionData ary_section_data = 3;</code>
     */
    private $ary_section_data;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type bool $is_win
     * @type int $sd_certified_level_id
     * @type \App\GameProtocol\Proto\Green\Taiko\PlayResultDataRequest\StageData\GhostStageData\GhostStageSectionData[] $ary_section_data
     *                                                                                                                  }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool is_win = 1;</code>
     *
     * @return bool
     */
    public function getIsWin()
    {
        return isset($this->is_win) ? $this->is_win : false;
    }

    public function hasIsWin()
    {
        return isset($this->is_win);
    }

    public function clearIsWin()
    {
        unset($this->is_win);
    }

    /**
     * Generated from protobuf field <code>optional bool is_win = 1;</code>
     *
     * @return $this
     */
    public function setIsWin(bool $var)
    {
        $this->is_win = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 sd_certified_level_id = 2;</code>
     *
     * @return int
     */
    public function getSdCertifiedLevelId()
    {
        return isset($this->sd_certified_level_id) ? $this->sd_certified_level_id : 0;
    }

    public function hasSdCertifiedLevelId()
    {
        return isset($this->sd_certified_level_id);
    }

    public function clearSdCertifiedLevelId()
    {
        unset($this->sd_certified_level_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 sd_certified_level_id = 2;</code>
     *
     * @return $this
     */
    public function setSdCertifiedLevelId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->sd_certified_level_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.GhostStageData.GhostStageSectionData ary_section_data = 3;</code>
     *
     * @return RepeatedField<GhostStageSectionData>
     */
    public function getArySectionData()
    {
        return $this->ary_section_data;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.StageData.GhostStageData.GhostStageSectionData ary_section_data = 3;</code>
     *
     * @param  GhostStageSectionData[]  $var
     * @return $this
     */
    public function setArySectionData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, GhostStageSectionData::class);
        $this->ary_section_data = $arr;

        return $this;
    }
}
