<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_white.proto

namespace App\GameProtocol\Proto\White\Taiko\InitialdatacheckResponse;

use App\GameProtocol\Proto\White\Metadata\TaikoWhite;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.white.InitialdatacheckResponse.InformationData</code>
 */
class InformationData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 info_id = 1;</code>
     */
    protected $info_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     */
    protected $verup_no = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $info_id
     * @type int $verup_no
     *           }
     */
    public function __construct($data = null)
    {
        TaikoWhite::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 info_id = 1;</code>
     *
     * @return int
     */
    public function getInfoId()
    {
        return isset($this->info_id) ? $this->info_id : 0;
    }

    public function hasInfoId()
    {
        return isset($this->info_id);
    }

    public function clearInfoId()
    {
        unset($this->info_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 info_id = 1;</code>
     *
     * @return $this
     */
    public function setInfoId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->info_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     *
     * @return int
     */
    public function getVerupNo()
    {
        return isset($this->verup_no) ? $this->verup_no : 0;
    }

    public function hasVerupNo()
    {
        return isset($this->verup_no);
    }

    public function clearVerupNo()
    {
        unset($this->verup_no);
    }

    /**
     * Generated from protobuf field <code>optional uint32 verup_no = 2;</code>
     *
     * @return $this
     */
    public function setVerupNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->verup_no = $var;

        return $this;
    }
}
