<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_blue.proto

namespace App\GameProtocol\Proto\Blue\Taiko;

use App\GameProtocol\Proto\Blue\Metadata\TaikoBlue;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.blue.BanacoinpaymentRequest</code>
 */
class BanacoinpaymentRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_name = 3;</code>
     */
    protected $shop_name = null;

    /**
     * Generated from protobuf field <code>optional string personid = 4;</code>
     */
    protected $personid = null;

    /**
     * Generated from protobuf field <code>optional uint32 mode = 5;</code>
     */
    protected $mode = null;

    /**
     * Generated from protobuf field <code>optional uint32 banacoin_price = 6;</code>
     */
    protected $banacoin_price = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type string $shop_id
     * @type string $shop_name
     * @type string $personid
     * @type int $mode
     * @type int $banacoin_price
     *           }
     */
    public function __construct($data = null)
    {
        TaikoBlue::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_name = 3;</code>
     *
     * @return string
     */
    public function getShopName()
    {
        return isset($this->shop_name) ? $this->shop_name : '';
    }

    public function hasShopName()
    {
        return isset($this->shop_name);
    }

    public function clearShopName()
    {
        unset($this->shop_name);
    }

    /**
     * Generated from protobuf field <code>optional string shop_name = 3;</code>
     *
     * @return $this
     */
    public function setShopName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string personid = 4;</code>
     *
     * @return string
     */
    public function getPersonid()
    {
        return isset($this->personid) ? $this->personid : '';
    }

    public function hasPersonid()
    {
        return isset($this->personid);
    }

    public function clearPersonid()
    {
        unset($this->personid);
    }

    /**
     * Generated from protobuf field <code>optional string personid = 4;</code>
     *
     * @return $this
     */
    public function setPersonid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->personid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 mode = 5;</code>
     *
     * @return int
     */
    public function getMode()
    {
        return isset($this->mode) ? $this->mode : 0;
    }

    public function hasMode()
    {
        return isset($this->mode);
    }

    public function clearMode()
    {
        unset($this->mode);
    }

    /**
     * Generated from protobuf field <code>optional uint32 mode = 5;</code>
     *
     * @return $this
     */
    public function setMode(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 banacoin_price = 6;</code>
     *
     * @return int
     */
    public function getBanacoinPrice()
    {
        return isset($this->banacoin_price) ? $this->banacoin_price : 0;
    }

    public function hasBanacoinPrice()
    {
        return isset($this->banacoin_price);
    }

    public function clearBanacoinPrice()
    {
        unset($this->banacoin_price);
    }

    /**
     * Generated from protobuf field <code>optional uint32 banacoin_price = 6;</code>
     *
     * @return $this
     */
    public function setBanacoinPrice(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->banacoin_price = $var;

        return $this;
    }
}
