<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Blue\Taiko;

use App\GameProtocol\Proto\Blue\Metadata\Taiko;
use App\GameProtocol\Proto\Blue\Taiko\BattleUserDataResponse\BattleUserNpcData;
use App\GameProtocol\Proto\Blue\Taiko\BattleUserDataResponse\BattleUserTokenData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.blue.BattleUserDataResponse</code>
 */
class BattleUserDataResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional bytes release_info_flg = 2;</code>
     */
    protected $release_info_flg = null;

    /**
     * Generated from protobuf field <code>optional bytes release_battle_stage_flg = 3;</code>
     */
    protected $release_battle_stage_flg = null;

    /**
     * Generated from protobuf field <code>optional uint32 last_battle_stage_id = 4;</code>
     */
    protected $last_battle_stage_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 last_boss_life = 5;</code>
     */
    protected $last_boss_life = null;

    /**
     * Generated from protobuf field <code>optional uint32 last_npc_id = 6;</code>
     */
    protected $last_npc_id = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.BattleUserDataResponse.BattleUserNpcData npc_data = 7;</code>
     */
    private $npc_data;

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.BattleUserDataResponse.BattleUserTokenData ary_token_data = 8;</code>
     */
    private $ary_token_data;

    /**
     * Generated from protobuf field <code>optional uint32 assign_stage_id = 9;</code>
     */
    protected $assign_stage_id = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type string $release_info_flg
     * @type string $release_battle_stage_flg
     * @type int $last_battle_stage_id
     * @type int $last_boss_life
     * @type int $last_npc_id
     * @type \App\GameProtocol\Proto\Blue\Taiko\BattleUserDataResponse\BattleUserNpcData[] $npc_data
     * @type \App\GameProtocol\Proto\Blue\Taiko\BattleUserDataResponse\BattleUserTokenData[] $ary_token_data
     * @type int $assign_stage_id
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes release_info_flg = 2;</code>
     *
     * @return string
     */
    public function getReleaseInfoFlg()
    {
        return isset($this->release_info_flg) ? $this->release_info_flg : '';
    }

    public function hasReleaseInfoFlg()
    {
        return isset($this->release_info_flg);
    }

    public function clearReleaseInfoFlg()
    {
        unset($this->release_info_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes release_info_flg = 2;</code>
     *
     * @return $this
     */
    public function setReleaseInfoFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->release_info_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes release_battle_stage_flg = 3;</code>
     *
     * @return string
     */
    public function getReleaseBattleStageFlg()
    {
        return isset($this->release_battle_stage_flg) ? $this->release_battle_stage_flg : '';
    }

    public function hasReleaseBattleStageFlg()
    {
        return isset($this->release_battle_stage_flg);
    }

    public function clearReleaseBattleStageFlg()
    {
        unset($this->release_battle_stage_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes release_battle_stage_flg = 3;</code>
     *
     * @return $this
     */
    public function setReleaseBattleStageFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->release_battle_stage_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_battle_stage_id = 4;</code>
     *
     * @return int
     */
    public function getLastBattleStageId()
    {
        return isset($this->last_battle_stage_id) ? $this->last_battle_stage_id : 0;
    }

    public function hasLastBattleStageId()
    {
        return isset($this->last_battle_stage_id);
    }

    public function clearLastBattleStageId()
    {
        unset($this->last_battle_stage_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_battle_stage_id = 4;</code>
     *
     * @return $this
     */
    public function setLastBattleStageId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_battle_stage_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_boss_life = 5;</code>
     *
     * @return int
     */
    public function getLastBossLife()
    {
        return isset($this->last_boss_life) ? $this->last_boss_life : 0;
    }

    public function hasLastBossLife()
    {
        return isset($this->last_boss_life);
    }

    public function clearLastBossLife()
    {
        unset($this->last_boss_life);
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_boss_life = 5;</code>
     *
     * @return $this
     */
    public function setLastBossLife(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_boss_life = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_npc_id = 6;</code>
     *
     * @return int
     */
    public function getLastNpcId()
    {
        return isset($this->last_npc_id) ? $this->last_npc_id : 0;
    }

    public function hasLastNpcId()
    {
        return isset($this->last_npc_id);
    }

    public function clearLastNpcId()
    {
        unset($this->last_npc_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_npc_id = 6;</code>
     *
     * @return $this
     */
    public function setLastNpcId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_npc_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.BattleUserDataResponse.BattleUserNpcData npc_data = 7;</code>
     *
     * @return RepeatedField<BattleUserNpcData>
     */
    public function getNpcData()
    {
        return $this->npc_data;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.BattleUserDataResponse.BattleUserNpcData npc_data = 7;</code>
     *
     * @param  BattleUserNpcData[]  $var
     * @return $this
     */
    public function setNpcData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, BattleUserNpcData::class);
        $this->npc_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.BattleUserDataResponse.BattleUserTokenData ary_token_data = 8;</code>
     *
     * @return RepeatedField<BattleUserTokenData>
     */
    public function getAryTokenData()
    {
        return $this->ary_token_data;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.blue.BattleUserDataResponse.BattleUserTokenData ary_token_data = 8;</code>
     *
     * @param  BattleUserTokenData[]  $var
     * @return $this
     */
    public function setAryTokenData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, BattleUserTokenData::class);
        $this->ary_token_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 assign_stage_id = 9;</code>
     *
     * @return int
     */
    public function getAssignStageId()
    {
        return isset($this->assign_stage_id) ? $this->assign_stage_id : 0;
    }

    public function hasAssignStageId()
    {
        return isset($this->assign_stage_id);
    }

    public function clearAssignStageId()
    {
        unset($this->assign_stage_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 assign_stage_id = 9;</code>
     *
     * @return $this
     */
    public function setAssignStageId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->assign_stage_id = $var;

        return $this;
    }
}
