<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_blue.proto

namespace App\GameProtocol\Proto\Blue\Taiko;

use App\GameProtocol\Proto\Blue\Metadata\TaikoBlue;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.blue.RecommendRequest</code>
 */
class RecommendRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 gender_type = 3;</code>
     */
    protected $gender_type = null;

    /**
     * Generated from protobuf field <code>optional uint32 player_age = 4;</code>
     */
    protected $player_age = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type string $shop_id
     * @type int $gender_type
     * @type int $player_age
     *           }
     */
    public function __construct($data = null)
    {
        TaikoBlue::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 gender_type = 3;</code>
     *
     * @return int
     */
    public function getGenderType()
    {
        return isset($this->gender_type) ? $this->gender_type : 0;
    }

    public function hasGenderType()
    {
        return isset($this->gender_type);
    }

    public function clearGenderType()
    {
        unset($this->gender_type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 gender_type = 3;</code>
     *
     * @return $this
     */
    public function setGenderType(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->gender_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 player_age = 4;</code>
     *
     * @return int
     */
    public function getPlayerAge()
    {
        return isset($this->player_age) ? $this->player_age : 0;
    }

    public function hasPlayerAge()
    {
        return isset($this->player_age);
    }

    public function clearPlayerAge()
    {
        unset($this->player_age);
    }

    /**
     * Generated from protobuf field <code>optional uint32 player_age = 4;</code>
     *
     * @return $this
     */
    public function setPlayerAge(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->player_age = $var;

        return $this;
    }
}
