<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Taiko\PlayResultDataRequest\UpdateGhostRankData;

use App\GameProtocol\Green\Proto\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.green.PlayResultDataRequest.UpdateGhostRankData.UpdateGhostWinningsData</code>
 */
class UpdateGhostWinningsData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 level_id = 1;</code>
     */
    protected $level_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 winnings = 2;</code>
     */
    protected $winnings = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $level_id
     * @type int $winnings
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 level_id = 1;</code>
     *
     * @return int
     */
    public function getLevelId()
    {
        return isset($this->level_id) ? $this->level_id : 0;
    }

    public function hasLevelId()
    {
        return isset($this->level_id);
    }

    public function clearLevelId()
    {
        unset($this->level_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 level_id = 1;</code>
     *
     * @return $this
     */
    public function setLevelId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->level_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 winnings = 2;</code>
     *
     * @return int
     */
    public function getWinnings()
    {
        return isset($this->winnings) ? $this->winnings : 0;
    }

    public function hasWinnings()
    {
        return isset($this->winnings);
    }

    public function clearWinnings()
    {
        unset($this->winnings);
    }

    /**
     * Generated from protobuf field <code>optional uint32 winnings = 2;</code>
     *
     * @return $this
     */
    public function setWinnings(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->winnings = $var;

        return $this;
    }
}
