<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Green\Taiko\GetghostdataResponse;

use App\GameProtocol\Green\Proto\Green\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.green.GetghostdataResponse.GhostPerfData</code>
 */
class GhostPerfData extends Message
{
    /**
     * Generated from protobuf field <code>optional sint32 input_median = 1;</code>
     */
    protected $input_median = null;

    /**
     * Generated from protobuf field <code>optional uint32 input_variance = 2;</code>
     */
    protected $input_variance = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $input_median
     * @type int $input_variance
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional sint32 input_median = 1;</code>
     *
     * @return int
     */
    public function getInputMedian()
    {
        return isset($this->input_median) ? $this->input_median : 0;
    }

    public function hasInputMedian()
    {
        return isset($this->input_median);
    }

    public function clearInputMedian()
    {
        unset($this->input_median);
    }

    /**
     * Generated from protobuf field <code>optional sint32 input_median = 1;</code>
     *
     * @return $this
     */
    public function setInputMedian(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->input_median = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 input_variance = 2;</code>
     *
     * @return int
     */
    public function getInputVariance()
    {
        return isset($this->input_variance) ? $this->input_variance : 0;
    }

    public function hasInputVariance()
    {
        return isset($this->input_variance);
    }

    public function clearInputVariance()
    {
        unset($this->input_variance);
    }

    /**
     * Generated from protobuf field <code>optional uint32 input_variance = 2;</code>
     *
     * @return $this
     */
    public function setInputVariance(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->input_variance = $var;

        return $this;
    }
}
