<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Murasaki\Taiko\TaikojukuResponse;

use App\GameProtocol\Proto\Murasaki\Metadata\Taiko;
use App\GameProtocol\Proto\Murasaki\Taiko\TaikojukuResponse\JukupackData\JukusongData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.murasaki.TaikojukuResponse.JukupackData</code>
 */
class JukupackData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 get_dan = 1;</code>
     */
    protected $get_dan = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.TaikojukuResponse.JukupackData.JukusongData ary_jukusong_data = 2;</code>
     */
    private $ary_jukusong_data;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $get_dan
     * @type \App\GameProtocol\Proto\Murasaki\Taiko\TaikojukuResponse\JukupackData\JukusongData[] $ary_jukusong_data
     *                                                                                            }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 get_dan = 1;</code>
     *
     * @return int
     */
    public function getGetDan()
    {
        return isset($this->get_dan) ? $this->get_dan : 0;
    }

    public function hasGetDan()
    {
        return isset($this->get_dan);
    }

    public function clearGetDan()
    {
        unset($this->get_dan);
    }

    /**
     * Generated from protobuf field <code>optional uint32 get_dan = 1;</code>
     *
     * @return $this
     */
    public function setGetDan(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->get_dan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.TaikojukuResponse.JukupackData.JukusongData ary_jukusong_data = 2;</code>
     *
     * @return RepeatedField<JukusongData>
     */
    public function getAryJukusongData()
    {
        return $this->ary_jukusong_data;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.TaikojukuResponse.JukupackData.JukusongData ary_jukusong_data = 2;</code>
     *
     * @param  JukusongData[]  $var
     * @return $this
     */
    public function setAryJukusongData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, JukusongData::class);
        $this->ary_jukusong_data = $arr;

        return $this;
    }
}
