<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_kimidori.proto

namespace App\GameProtocol\Proto\Kimidori\Taiko;

use App\GameProtocol\Proto\Kimidori\Metadata\TaikoKimidori;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.kimidori.TelopcheckRequest</code>
 */
class TelopcheckRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     *              }
     */
    public function __construct($data = null)
    {
        TaikoKimidori::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }
}
