<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Taiko\PlayResultDataRequest;

use App\GameProtocol\Green\Proto\Metadata\Taiko;
use App\GameProtocol\Green\Proto\Taiko\PlayResultDataRequest\UpdateGhostInfoData\GhostTokenData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.green.PlayResultDataRequest.UpdateGhostInfoData</code>
 */
class UpdateGhostInfoData extends Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 release_info_id = 1;</code>
     */
    private $release_info_id;

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.UpdateGhostInfoData.GhostTokenData ary_tokendata = 2;</code>
     */
    private $ary_tokendata;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int[] $release_info_id
     * @type \App\GameProtocol\Green\Proto\Taiko\PlayResultDataRequest\UpdateGhostInfoData\GhostTokenData[] $ary_tokendata
     *                                                                                                      }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_info_id = 1;</code>
     *
     * @return RepeatedField<int>
     */
    public function getReleaseInfoId()
    {
        return $this->release_info_id;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_info_id = 1;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setReleaseInfoId(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->release_info_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.UpdateGhostInfoData.GhostTokenData ary_tokendata = 2;</code>
     *
     * @return RepeatedField<GhostTokenData>
     */
    public function getAryTokendata()
    {
        return $this->ary_tokendata;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.green.PlayResultDataRequest.UpdateGhostInfoData.GhostTokenData ary_tokendata = 2;</code>
     *
     * @param  GhostTokenData[]  $var
     * @return $this
     */
    public function setAryTokendata(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, GhostTokenData::class);
        $this->ary_tokendata = $arr;

        return $this;
    }
}
