<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_red.proto

namespace App\GameProtocol\Proto\Red\Taiko;

use App\GameProtocol\Proto\Red\Metadata\TaikoRed;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.red.BalancecheckResponse</code>
 */
class BalancecheckResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional string personid = 2;</code>
     */
    protected $personid = null;

    /**
     * Generated from protobuf field <code>optional string bnid_result = 3;</code>
     */
    protected $bnid_result = null;

    /**
     * Generated from protobuf field <code>optional uint32 coin_coupon = 4;</code>
     */
    protected $coin_coupon = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type string $personid
     * @type string $bnid_result
     * @type int $coin_coupon
     *           }
     */
    public function __construct($data = null)
    {
        TaikoRed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string personid = 2;</code>
     *
     * @return string
     */
    public function getPersonid()
    {
        return isset($this->personid) ? $this->personid : '';
    }

    public function hasPersonid()
    {
        return isset($this->personid);
    }

    public function clearPersonid()
    {
        unset($this->personid);
    }

    /**
     * Generated from protobuf field <code>optional string personid = 2;</code>
     *
     * @return $this
     */
    public function setPersonid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->personid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string bnid_result = 3;</code>
     *
     * @return string
     */
    public function getBnidResult()
    {
        return isset($this->bnid_result) ? $this->bnid_result : '';
    }

    public function hasBnidResult()
    {
        return isset($this->bnid_result);
    }

    public function clearBnidResult()
    {
        unset($this->bnid_result);
    }

    /**
     * Generated from protobuf field <code>optional string bnid_result = 3;</code>
     *
     * @return $this
     */
    public function setBnidResult(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->bnid_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 coin_coupon = 4;</code>
     *
     * @return int
     */
    public function getCoinCoupon()
    {
        return isset($this->coin_coupon) ? $this->coin_coupon : 0;
    }

    public function hasCoinCoupon()
    {
        return isset($this->coin_coupon);
    }

    public function clearCoinCoupon()
    {
        unset($this->coin_coupon);
    }

    /**
     * Generated from protobuf field <code>optional uint32 coin_coupon = 4;</code>
     *
     * @return $this
     */
    public function setCoinCoupon(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->coin_coupon = $var;

        return $this;
    }
}
