<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_red.proto

namespace App\GameProtocol\Proto\Red\Taiko;

use App\GameProtocol\Proto\Red\Metadata\TaikoRed;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.red.CoinsettingRequest</code>
 */
class CoinsettingRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional string setting_datetime = 3;</code>
     */
    protected $setting_datetime = null;

    /**
     * Generated from protobuf field <code>optional uint32 play_rates = 4;</code>
     */
    protected $play_rates = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type string $shop_id
     * @type string $setting_datetime
     * @type int $play_rates
     *           }
     */
    public function __construct($data = null)
    {
        TaikoRed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string setting_datetime = 3;</code>
     *
     * @return string
     */
    public function getSettingDatetime()
    {
        return isset($this->setting_datetime) ? $this->setting_datetime : '';
    }

    public function hasSettingDatetime()
    {
        return isset($this->setting_datetime);
    }

    public function clearSettingDatetime()
    {
        unset($this->setting_datetime);
    }

    /**
     * Generated from protobuf field <code>optional string setting_datetime = 3;</code>
     *
     * @return $this
     */
    public function setSettingDatetime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->setting_datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_rates = 4;</code>
     *
     * @return int
     */
    public function getPlayRates()
    {
        return isset($this->play_rates) ? $this->play_rates : 0;
    }

    public function hasPlayRates()
    {
        return isset($this->play_rates);
    }

    public function clearPlayRates()
    {
        unset($this->play_rates);
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_rates = 4;</code>
     *
     * @return $this
     */
    public function setPlayRates(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->play_rates = $var;

        return $this;
    }
}
