<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Red\Taiko;

use App\GameProtocol\Proto\Red\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.red.CrownsDataResponse</code>
 */
class CrownsDataResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 2;</code>
     */
    protected $song_hash_ver = null;

    /**
     * Generated from protobuf field <code>optional bytes hash_crown_flg = 3;</code>
     */
    protected $hash_crown_flg = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $song_hash_ver
     * @type string $hash_crown_flg
     *              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 2;</code>
     *
     * @return int
     */
    public function getSongHashVer()
    {
        return isset($this->song_hash_ver) ? $this->song_hash_ver : 0;
    }

    public function hasSongHashVer()
    {
        return isset($this->song_hash_ver);
    }

    public function clearSongHashVer()
    {
        unset($this->song_hash_ver);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 2;</code>
     *
     * @return $this
     */
    public function setSongHashVer(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->song_hash_ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes hash_crown_flg = 3;</code>
     *
     * @return string
     */
    public function getHashCrownFlg()
    {
        return isset($this->hash_crown_flg) ? $this->hash_crown_flg : '';
    }

    public function hasHashCrownFlg()
    {
        return isset($this->hash_crown_flg);
    }

    public function clearHashCrownFlg()
    {
        unset($this->hash_crown_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes hash_crown_flg = 3;</code>
     *
     * @return $this
     */
    public function setHashCrownFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->hash_crown_flg = $var;

        return $this;
    }
}
