<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Red\Taiko;

use App\GameProtocol\Proto\Red\Metadata\Taiko;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.red.RecommendResponse</code>
 */
class RecommendResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 recommend_song = 2;</code>
     */
    protected $recommend_song = null;

    /**
     * Generated from protobuf field <code>repeated uint32 recommend_best_song = 3;</code>
     */
    private $recommend_best_song;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $recommend_song
     * @type int[] $recommend_best_song
     *             }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 recommend_song = 2;</code>
     *
     * @return int
     */
    public function getRecommendSong()
    {
        return isset($this->recommend_song) ? $this->recommend_song : 0;
    }

    public function hasRecommendSong()
    {
        return isset($this->recommend_song);
    }

    public function clearRecommendSong()
    {
        unset($this->recommend_song);
    }

    /**
     * Generated from protobuf field <code>optional uint32 recommend_song = 2;</code>
     *
     * @return $this
     */
    public function setRecommendSong(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->recommend_song = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 recommend_best_song = 3;</code>
     *
     * @return RepeatedField<int>
     */
    public function getRecommendBestSong()
    {
        return $this->recommend_best_song;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 recommend_best_song = 3;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setRecommendBestSong(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->recommend_best_song = $arr;

        return $this;
    }
}
