<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vsinterface.proto

namespace App\GameProtocol\Proto\Yellow\VsInterface;

use App\GameProtocol\Proto\Yellow\Metadata\Vsinterface;
use App\GameProtocol\Proto\Yellow\VsInterface\StartupAuthRequest\OperationData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>vsinterface.yellow.StartupAuthRequest</code>
 */
class StartupAuthRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string usbmem_key = 2;</code>
     */
    protected $usbmem_key = null;

    /**
     * Generated from protobuf field <code>optional uint32 hdd_ver = 3;</code>
     */
    protected $hdd_ver = null;

    /**
     * Generated from protobuf field <code>optional uint32 usbmem_ver = 4;</code>
     */
    protected $usbmem_ver = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 5;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional string rack_id = 6;</code>
     */
    protected $rack_id = null;

    /**
     * Generated from protobuf field <code>optional string country_id = 7;</code>
     */
    protected $country_id = null;

    /**
     * Generated from protobuf field <code>repeated .vsinterface.yellow.StartupAuthRequest.OperationData ary_operation_info = 8;</code>
     */
    private $ary_operation_info;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type string $usbmem_key
     * @type int $hdd_ver
     * @type int $usbmem_ver
     * @type string $shop_id
     * @type string $rack_id
     * @type string $country_id
     * @type \App\GameProtocol\Proto\Yellow\VsInterface\StartupAuthRequest\OperationData[] $ary_operation_info
     *                                                                                     }
     */
    public function __construct($data = null)
    {
        Vsinterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string usbmem_key = 2;</code>
     *
     * @return string
     */
    public function getUsbmemKey()
    {
        return isset($this->usbmem_key) ? $this->usbmem_key : '';
    }

    public function hasUsbmemKey()
    {
        return isset($this->usbmem_key);
    }

    public function clearUsbmemKey()
    {
        unset($this->usbmem_key);
    }

    /**
     * Generated from protobuf field <code>optional string usbmem_key = 2;</code>
     *
     * @return $this
     */
    public function setUsbmemKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->usbmem_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 hdd_ver = 3;</code>
     *
     * @return int
     */
    public function getHddVer()
    {
        return isset($this->hdd_ver) ? $this->hdd_ver : 0;
    }

    public function hasHddVer()
    {
        return isset($this->hdd_ver);
    }

    public function clearHddVer()
    {
        unset($this->hdd_ver);
    }

    /**
     * Generated from protobuf field <code>optional uint32 hdd_ver = 3;</code>
     *
     * @return $this
     */
    public function setHddVer(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->hdd_ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 usbmem_ver = 4;</code>
     *
     * @return int
     */
    public function getUsbmemVer()
    {
        return isset($this->usbmem_ver) ? $this->usbmem_ver : 0;
    }

    public function hasUsbmemVer()
    {
        return isset($this->usbmem_ver);
    }

    public function clearUsbmemVer()
    {
        unset($this->usbmem_ver);
    }

    /**
     * Generated from protobuf field <code>optional uint32 usbmem_ver = 4;</code>
     *
     * @return $this
     */
    public function setUsbmemVer(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->usbmem_ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 5;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 5;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string rack_id = 6;</code>
     *
     * @return string
     */
    public function getRackId()
    {
        return isset($this->rack_id) ? $this->rack_id : '';
    }

    public function hasRackId()
    {
        return isset($this->rack_id);
    }

    public function clearRackId()
    {
        unset($this->rack_id);
    }

    /**
     * Generated from protobuf field <code>optional string rack_id = 6;</code>
     *
     * @return $this
     */
    public function setRackId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->rack_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string country_id = 7;</code>
     *
     * @return string
     */
    public function getCountryId()
    {
        return isset($this->country_id) ? $this->country_id : '';
    }

    public function hasCountryId()
    {
        return isset($this->country_id);
    }

    public function clearCountryId()
    {
        unset($this->country_id);
    }

    /**
     * Generated from protobuf field <code>optional string country_id = 7;</code>
     *
     * @return $this
     */
    public function setCountryId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->country_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vsinterface.yellow.StartupAuthRequest.OperationData ary_operation_info = 8;</code>
     *
     * @return RepeatedField<OperationData>
     */
    public function getAryOperationInfo()
    {
        return $this->ary_operation_info;
    }

    /**
     * Generated from protobuf field <code>repeated .vsinterface.yellow.StartupAuthRequest.OperationData ary_operation_info = 8;</code>
     *
     * @param  OperationData[]  $var
     * @return $this
     */
    public function setAryOperationInfo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, OperationData::class);
        $this->ary_operation_info = $arr;

        return $this;
    }
}
