<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Green\Taiko\PlayResultDataRequest\StageData\GhostStageData;

use App\GameProtocol\Green\Proto\Green\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.green.PlayResultDataRequest.StageData.GhostStageData.GhostStageSectionData</code>
 */
class GhostStageSectionData extends Message
{
    /**
     * Generated from protobuf field <code>optional bool is_win = 1;</code>
     */
    protected $is_win = null;

    /**
     * Generated from protobuf field <code>optional uint32 good_cnt = 2;</code>
     */
    protected $good_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 ok_cnt = 3;</code>
     */
    protected $ok_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 ng_cnt = 4;</code>
     */
    protected $ng_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 pound_cnt = 5;</code>
     */
    protected $pound_cnt = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type bool $is_win
     * @type int $good_cnt
     * @type int $ok_cnt
     * @type int $ng_cnt
     * @type int $pound_cnt
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool is_win = 1;</code>
     *
     * @return bool
     */
    public function getIsWin()
    {
        return isset($this->is_win) ? $this->is_win : false;
    }

    public function hasIsWin()
    {
        return isset($this->is_win);
    }

    public function clearIsWin()
    {
        unset($this->is_win);
    }

    /**
     * Generated from protobuf field <code>optional bool is_win = 1;</code>
     *
     * @return $this
     */
    public function setIsWin(bool $var)
    {
        $this->is_win = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 good_cnt = 2;</code>
     *
     * @return int
     */
    public function getGoodCnt()
    {
        return isset($this->good_cnt) ? $this->good_cnt : 0;
    }

    public function hasGoodCnt()
    {
        return isset($this->good_cnt);
    }

    public function clearGoodCnt()
    {
        unset($this->good_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 good_cnt = 2;</code>
     *
     * @return $this
     */
    public function setGoodCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->good_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 ok_cnt = 3;</code>
     *
     * @return int
     */
    public function getOkCnt()
    {
        return isset($this->ok_cnt) ? $this->ok_cnt : 0;
    }

    public function hasOkCnt()
    {
        return isset($this->ok_cnt);
    }

    public function clearOkCnt()
    {
        unset($this->ok_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 ok_cnt = 3;</code>
     *
     * @return $this
     */
    public function setOkCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->ok_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 ng_cnt = 4;</code>
     *
     * @return int
     */
    public function getNgCnt()
    {
        return isset($this->ng_cnt) ? $this->ng_cnt : 0;
    }

    public function hasNgCnt()
    {
        return isset($this->ng_cnt);
    }

    public function clearNgCnt()
    {
        unset($this->ng_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 ng_cnt = 4;</code>
     *
     * @return $this
     */
    public function setNgCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->ng_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pound_cnt = 5;</code>
     *
     * @return int
     */
    public function getPoundCnt()
    {
        return isset($this->pound_cnt) ? $this->pound_cnt : 0;
    }

    public function hasPoundCnt()
    {
        return isset($this->pound_cnt);
    }

    public function clearPoundCnt()
    {
        unset($this->pound_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pound_cnt = 5;</code>
     *
     * @return $this
     */
    public function setPoundCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->pound_cnt = $var;

        return $this;
    }
}
