<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Taiko\PlayResultDataRequest\UpdateGhostInfoData;

use App\GameProtocol\Green\Proto\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.green.PlayResultDataRequest.UpdateGhostInfoData.GhostTokenData</code>
 */
class GhostTokenData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 token_id = 1;</code>
     */
    protected $token_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 token_value = 2;</code>
     */
    protected $token_value = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $token_id
     * @type int $token_value
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 token_id = 1;</code>
     *
     * @return int
     */
    public function getTokenId()
    {
        return isset($this->token_id) ? $this->token_id : 0;
    }

    public function hasTokenId()
    {
        return isset($this->token_id);
    }

    public function clearTokenId()
    {
        unset($this->token_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 token_id = 1;</code>
     *
     * @return $this
     */
    public function setTokenId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->token_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 token_value = 2;</code>
     *
     * @return int
     */
    public function getTokenValue()
    {
        return isset($this->token_value) ? $this->token_value : 0;
    }

    public function hasTokenValue()
    {
        return isset($this->token_value);
    }

    public function clearTokenValue()
    {
        unset($this->token_value);
    }

    /**
     * Generated from protobuf field <code>optional uint32 token_value = 2;</code>
     *
     * @return $this
     */
    public function setTokenValue(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->token_value = $var;

        return $this;
    }
}
