<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vsinterface.proto

namespace App\GameProtocol\Green\Proto\Red\VsInterface;

use App\GameProtocol\Green\Proto\Red\Metadata\Vsinterface;
use App\GameProtocol\Green\Proto\Red\VsInterface\StartupAuthResponse\MovieData;
use App\GameProtocol\Green\Proto\Red\VsInterface\StartupAuthResponse\OperationData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>vsinterface.red.StartupAuthResponse</code>
 */
class StartupAuthResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>repeated .vsinterface.red.StartupAuthResponse.MovieData ary_movie_info = 2;</code>
     */
    private $ary_movie_info;

    /**
     * Generated from protobuf field <code>repeated .vsinterface.red.StartupAuthResponse.OperationData ary_operation_info = 3;</code>
     */
    private $ary_operation_info;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type \App\GameProtocol\Green\Proto\Red\VsInterface\StartupAuthResponse\MovieData[] $ary_movie_info
     * @type \App\GameProtocol\Green\Proto\Red\VsInterface\StartupAuthResponse\OperationData[] $ary_operation_info
     *                                                                                         }
     */
    public function __construct($data = null)
    {
        Vsinterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vsinterface.red.StartupAuthResponse.MovieData ary_movie_info = 2;</code>
     *
     * @return RepeatedField<MovieData>
     */
    public function getAryMovieInfo()
    {
        return $this->ary_movie_info;
    }

    /**
     * Generated from protobuf field <code>repeated .vsinterface.red.StartupAuthResponse.MovieData ary_movie_info = 2;</code>
     *
     * @param  MovieData[]  $var
     * @return $this
     */
    public function setAryMovieInfo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, MovieData::class);
        $this->ary_movie_info = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vsinterface.red.StartupAuthResponse.OperationData ary_operation_info = 3;</code>
     *
     * @return RepeatedField<OperationData>
     */
    public function getAryOperationInfo()
    {
        return $this->ary_operation_info;
    }

    /**
     * Generated from protobuf field <code>repeated .vsinterface.red.StartupAuthResponse.OperationData ary_operation_info = 3;</code>
     *
     * @param  OperationData[]  $var
     * @return $this
     */
    public function setAryOperationInfo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, OperationData::class);
        $this->ary_operation_info = $arr;

        return $this;
    }
}
