<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_kimidori.proto

namespace App\GameProtocol\Proto\Kimidori\Taiko\BestScoreResponse\SongData;

use App\GameProtocol\Proto\Kimidori\Metadata\TaikoKimidori;
use App\GameProtocol\Proto\Kimidori\Taiko\BestScoreResponse\SongData\Best3Data\RankData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.kimidori.BestScoreResponse.SongData.Best3Data</code>
 */
class Best3Data extends Message
{
    /**
     * Generated from protobuf field <code>repeated .taiko.kimidori.BestScoreResponse.SongData.Best3Data.RankData ary_rank_score = 1;</code>
     */
    private $ary_rank_score;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type \App\GameProtocol\Proto\Kimidori\Taiko\BestScoreResponse\SongData\Best3Data\RankData[] $ary_rank_score
     *                                                                                              }
     */
    public function __construct($data = null)
    {
        TaikoKimidori::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.kimidori.BestScoreResponse.SongData.Best3Data.RankData ary_rank_score = 1;</code>
     *
     * @return RepeatedField<RankData>
     */
    public function getAryRankScore()
    {
        return $this->ary_rank_score;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.kimidori.BestScoreResponse.SongData.Best3Data.RankData ary_rank_score = 1;</code>
     *
     * @param  RankData[]  $var
     * @return $this
     */
    public function setAryRankScore(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, RankData::class);
        $this->ary_rank_score = $arr;

        return $this;
    }
}
