<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Momoiro\Taiko;

use App\GameProtocol\Proto\Momoiro\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.momoiro.CommunicationLogRequest</code>
 */
class CommunicationLogRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string update_datetime = 1;</code>
     */
    protected $update_datetime = null;

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 network_type = 4;</code>
     */
    protected $network_type = null;

    /**
     * Generated from protobuf field <code>optional uint32 sent_cnt = 5;</code>
     */
    protected $sent_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 fail_cnt = 6;</code>
     */
    protected $fail_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_min = 7;</code>
     */
    protected $trans_time_min = null;

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_max = 8;</code>
     */
    protected $trans_time_max = null;

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_ave = 9;</code>
     */
    protected $trans_time_ave = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $update_datetime
     * @type string $chassis_id
     * @type string $shop_id
     * @type int $network_type
     * @type int $sent_cnt
     * @type int $fail_cnt
     * @type int $trans_time_min
     * @type int $trans_time_max
     * @type int $trans_time_ave
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string update_datetime = 1;</code>
     *
     * @return string
     */
    public function getUpdateDatetime()
    {
        return isset($this->update_datetime) ? $this->update_datetime : '';
    }

    public function hasUpdateDatetime()
    {
        return isset($this->update_datetime);
    }

    public function clearUpdateDatetime()
    {
        unset($this->update_datetime);
    }

    /**
     * Generated from protobuf field <code>optional string update_datetime = 1;</code>
     *
     * @return $this
     */
    public function setUpdateDatetime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->update_datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 network_type = 4;</code>
     *
     * @return int
     */
    public function getNetworkType()
    {
        return isset($this->network_type) ? $this->network_type : 0;
    }

    public function hasNetworkType()
    {
        return isset($this->network_type);
    }

    public function clearNetworkType()
    {
        unset($this->network_type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 network_type = 4;</code>
     *
     * @return $this
     */
    public function setNetworkType(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->network_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 sent_cnt = 5;</code>
     *
     * @return int
     */
    public function getSentCnt()
    {
        return isset($this->sent_cnt) ? $this->sent_cnt : 0;
    }

    public function hasSentCnt()
    {
        return isset($this->sent_cnt);
    }

    public function clearSentCnt()
    {
        unset($this->sent_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 sent_cnt = 5;</code>
     *
     * @return $this
     */
    public function setSentCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->sent_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 fail_cnt = 6;</code>
     *
     * @return int
     */
    public function getFailCnt()
    {
        return isset($this->fail_cnt) ? $this->fail_cnt : 0;
    }

    public function hasFailCnt()
    {
        return isset($this->fail_cnt);
    }

    public function clearFailCnt()
    {
        unset($this->fail_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 fail_cnt = 6;</code>
     *
     * @return $this
     */
    public function setFailCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->fail_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_min = 7;</code>
     *
     * @return int
     */
    public function getTransTimeMin()
    {
        return isset($this->trans_time_min) ? $this->trans_time_min : 0;
    }

    public function hasTransTimeMin()
    {
        return isset($this->trans_time_min);
    }

    public function clearTransTimeMin()
    {
        unset($this->trans_time_min);
    }

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_min = 7;</code>
     *
     * @return $this
     */
    public function setTransTimeMin(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->trans_time_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_max = 8;</code>
     *
     * @return int
     */
    public function getTransTimeMax()
    {
        return isset($this->trans_time_max) ? $this->trans_time_max : 0;
    }

    public function hasTransTimeMax()
    {
        return isset($this->trans_time_max);
    }

    public function clearTransTimeMax()
    {
        unset($this->trans_time_max);
    }

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_max = 8;</code>
     *
     * @return $this
     */
    public function setTransTimeMax(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->trans_time_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_ave = 9;</code>
     *
     * @return int
     */
    public function getTransTimeAve()
    {
        return isset($this->trans_time_ave) ? $this->trans_time_ave : 0;
    }

    public function hasTransTimeAve()
    {
        return isset($this->trans_time_ave);
    }

    public function clearTransTimeAve()
    {
        unset($this->trans_time_ave);
    }

    /**
     * Generated from protobuf field <code>optional uint32 trans_time_ave = 9;</code>
     *
     * @return $this
     */
    public function setTransTimeAve(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->trans_time_ave = $var;

        return $this;
    }
}
