<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Momoiro\Taiko;

use App\GameProtocol\Proto\Momoiro\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.momoiro.HeartBeatResponse</code>
 */
class HeartBeatResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_stat = 2;</code>
     */
    protected $com_svr_stat = null;

    /**
     * Generated from protobuf field <code>optional uint32 game_svr_stat = 3;</code>
     */
    protected $game_svr_stat = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $com_svr_stat
     * @type int $game_svr_stat
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_stat = 2;</code>
     *
     * @return int
     */
    public function getComSvrStat()
    {
        return isset($this->com_svr_stat) ? $this->com_svr_stat : 0;
    }

    public function hasComSvrStat()
    {
        return isset($this->com_svr_stat);
    }

    public function clearComSvrStat()
    {
        unset($this->com_svr_stat);
    }

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_stat = 2;</code>
     *
     * @return $this
     */
    public function setComSvrStat(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->com_svr_stat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 game_svr_stat = 3;</code>
     *
     * @return int
     */
    public function getGameSvrStat()
    {
        return isset($this->game_svr_stat) ? $this->game_svr_stat : 0;
    }

    public function hasGameSvrStat()
    {
        return isset($this->game_svr_stat);
    }

    public function clearGameSvrStat()
    {
        unset($this->game_svr_stat);
    }

    /**
     * Generated from protobuf field <code>optional uint32 game_svr_stat = 3;</code>
     *
     * @return $this
     */
    public function setGameSvrStat(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->game_svr_stat = $var;

        return $this;
    }
}
