<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_blue.proto

namespace App\GameProtocol\Proto\Blue\Taiko\PlayResultRequest\StageData\BattleStageData;

use App\GameProtocol\Proto\Blue\Metadata\TaikoBlue;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.blue.PlayResultRequest.StageData.BattleStageData.BattleNpcData</code>
 */
class BattleNpcData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 npc_id = 1;</code>
     */
    protected $npc_id = null;

    /**
     * Generated from protobuf field <code>optional string acquired_exp = 2;</code>
     */
    protected $acquired_exp = null;

    /**
     * Generated from protobuf field <code>optional string total_exp = 3;</code>
     */
    protected $total_exp = null;

    /**
     * Generated from protobuf field <code>optional uint32 dpn = 4;</code>
     */
    protected $dpn = null;

    /**
     * Generated from protobuf field <code>optional uint32 npc_costume_id = 5;</code>
     */
    protected $npc_costume_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 special_id_1 = 6;</code>
     */
    protected $special_id_1 = null;

    /**
     * Generated from protobuf field <code>optional uint32 special_id_2 = 7;</code>
     */
    protected $special_id_2 = null;

    /**
     * Generated from protobuf field <code>optional uint32 special_id_3 = 8;</code>
     */
    protected $special_id_3 = null;

    /**
     * Generated from protobuf field <code>optional uint32 bonds_lv = 9;</code>
     */
    protected $bonds_lv = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $npc_id
     * @type string $acquired_exp
     * @type string $total_exp
     * @type int $dpn
     * @type int $npc_costume_id
     * @type int $special_id_1
     * @type int $special_id_2
     * @type int $special_id_3
     * @type int $bonds_lv
     *           }
     */
    public function __construct($data = null)
    {
        TaikoBlue::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 npc_id = 1;</code>
     *
     * @return int
     */
    public function getNpcId()
    {
        return isset($this->npc_id) ? $this->npc_id : 0;
    }

    public function hasNpcId()
    {
        return isset($this->npc_id);
    }

    public function clearNpcId()
    {
        unset($this->npc_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 npc_id = 1;</code>
     *
     * @return $this
     */
    public function setNpcId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->npc_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string acquired_exp = 2;</code>
     *
     * @return string
     */
    public function getAcquiredExp()
    {
        return isset($this->acquired_exp) ? $this->acquired_exp : '';
    }

    public function hasAcquiredExp()
    {
        return isset($this->acquired_exp);
    }

    public function clearAcquiredExp()
    {
        unset($this->acquired_exp);
    }

    /**
     * Generated from protobuf field <code>optional string acquired_exp = 2;</code>
     *
     * @return $this
     */
    public function setAcquiredExp(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->acquired_exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string total_exp = 3;</code>
     *
     * @return string
     */
    public function getTotalExp()
    {
        return isset($this->total_exp) ? $this->total_exp : '';
    }

    public function hasTotalExp()
    {
        return isset($this->total_exp);
    }

    public function clearTotalExp()
    {
        unset($this->total_exp);
    }

    /**
     * Generated from protobuf field <code>optional string total_exp = 3;</code>
     *
     * @return $this
     */
    public function setTotalExp(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->total_exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 dpn = 4;</code>
     *
     * @return int
     */
    public function getDpn()
    {
        return isset($this->dpn) ? $this->dpn : 0;
    }

    public function hasDpn()
    {
        return isset($this->dpn);
    }

    public function clearDpn()
    {
        unset($this->dpn);
    }

    /**
     * Generated from protobuf field <code>optional uint32 dpn = 4;</code>
     *
     * @return $this
     */
    public function setDpn(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->dpn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 npc_costume_id = 5;</code>
     *
     * @return int
     */
    public function getNpcCostumeId()
    {
        return isset($this->npc_costume_id) ? $this->npc_costume_id : 0;
    }

    public function hasNpcCostumeId()
    {
        return isset($this->npc_costume_id);
    }

    public function clearNpcCostumeId()
    {
        unset($this->npc_costume_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 npc_costume_id = 5;</code>
     *
     * @return $this
     */
    public function setNpcCostumeId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->npc_costume_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 special_id_1 = 6;</code>
     *
     * @return int
     */
    public function getSpecialId1()
    {
        return isset($this->special_id_1) ? $this->special_id_1 : 0;
    }

    public function hasSpecialId1()
    {
        return isset($this->special_id_1);
    }

    public function clearSpecialId1()
    {
        unset($this->special_id_1);
    }

    /**
     * Generated from protobuf field <code>optional uint32 special_id_1 = 6;</code>
     *
     * @return $this
     */
    public function setSpecialId1(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->special_id_1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 special_id_2 = 7;</code>
     *
     * @return int
     */
    public function getSpecialId2()
    {
        return isset($this->special_id_2) ? $this->special_id_2 : 0;
    }

    public function hasSpecialId2()
    {
        return isset($this->special_id_2);
    }

    public function clearSpecialId2()
    {
        unset($this->special_id_2);
    }

    /**
     * Generated from protobuf field <code>optional uint32 special_id_2 = 7;</code>
     *
     * @return $this
     */
    public function setSpecialId2(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->special_id_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 special_id_3 = 8;</code>
     *
     * @return int
     */
    public function getSpecialId3()
    {
        return isset($this->special_id_3) ? $this->special_id_3 : 0;
    }

    public function hasSpecialId3()
    {
        return isset($this->special_id_3);
    }

    public function clearSpecialId3()
    {
        unset($this->special_id_3);
    }

    /**
     * Generated from protobuf field <code>optional uint32 special_id_3 = 8;</code>
     *
     * @return $this
     */
    public function setSpecialId3(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->special_id_3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 bonds_lv = 9;</code>
     *
     * @return int
     */
    public function getBondsLv()
    {
        return isset($this->bonds_lv) ? $this->bonds_lv : 0;
    }

    public function hasBondsLv()
    {
        return isset($this->bonds_lv);
    }

    public function clearBondsLv()
    {
        unset($this->bonds_lv);
    }

    /**
     * Generated from protobuf field <code>optional uint32 bonds_lv = 9;</code>
     *
     * @return $this
     */
    public function setBondsLv(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->bonds_lv = $var;

        return $this;
    }
}
