<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Blue\Taiko\PlayResultRequest\StageData;

use App\GameProtocol\Green\Proto\Blue\Metadata\Taiko;
use App\GameProtocol\Green\Proto\Blue\Taiko\PlayResultRequest\StageData\BattleStageData\BattleNpcData;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.blue.PlayResultRequest.StageData.BattleStageData</code>
 */
class BattleStageData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 support_lv = 1;</code>
     */
    protected $support_lv = null;

    /**
     * Generated from protobuf field <code>optional uint32 battle_stage_id = 2;</code>
     */
    protected $battle_stage_id = null;

    /**
     * Generated from protobuf field <code>optional .taiko.blue.PlayResultRequest.StageData.BattleStageData.BattleNpcData npc_data = 3;</code>
     */
    protected $npc_data = null;

    /**
     * Generated from protobuf field <code>optional uint32 kill_cnt = 4;</code>
     */
    protected $kill_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 boss_life = 5;</code>
     */
    protected $boss_life = null;

    /**
     * Generated from protobuf field <code>optional uint32 total_damage = 6;</code>
     */
    protected $total_damage = null;

    /**
     * Generated from protobuf field <code>optional uint32 critical_cnt = 7;</code>
     */
    protected $critical_cnt = null;

    /**
     * Generated from protobuf field <code>optional uint32 special_move_cnt = 8;</code>
     */
    protected $special_move_cnt = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $support_lv
     * @type int $battle_stage_id
     * @type \App\GameProtocol\Green\Proto\Blue\Taiko\PlayResultRequest\StageData\BattleStageData\BattleNpcData $npc_data
     * @type int $kill_cnt
     * @type int $boss_life
     * @type int $total_damage
     * @type int $critical_cnt
     * @type int $special_move_cnt
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 support_lv = 1;</code>
     *
     * @return int
     */
    public function getSupportLv()
    {
        return isset($this->support_lv) ? $this->support_lv : 0;
    }

    public function hasSupportLv()
    {
        return isset($this->support_lv);
    }

    public function clearSupportLv()
    {
        unset($this->support_lv);
    }

    /**
     * Generated from protobuf field <code>optional uint32 support_lv = 1;</code>
     *
     * @return $this
     */
    public function setSupportLv(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->support_lv = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 battle_stage_id = 2;</code>
     *
     * @return int
     */
    public function getBattleStageId()
    {
        return isset($this->battle_stage_id) ? $this->battle_stage_id : 0;
    }

    public function hasBattleStageId()
    {
        return isset($this->battle_stage_id);
    }

    public function clearBattleStageId()
    {
        unset($this->battle_stage_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 battle_stage_id = 2;</code>
     *
     * @return $this
     */
    public function setBattleStageId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->battle_stage_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .taiko.blue.PlayResultRequest.StageData.BattleStageData.BattleNpcData npc_data = 3;</code>
     *
     * @return BattleNpcData|null
     */
    public function getNpcData()
    {
        return $this->npc_data;
    }

    public function hasNpcData()
    {
        return isset($this->npc_data);
    }

    public function clearNpcData()
    {
        unset($this->npc_data);
    }

    /**
     * Generated from protobuf field <code>optional .taiko.blue.PlayResultRequest.StageData.BattleStageData.BattleNpcData npc_data = 3;</code>
     *
     * @return $this
     */
    public function setNpcData(?BattleNpcData $var)
    {
        $this->npc_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 kill_cnt = 4;</code>
     *
     * @return int
     */
    public function getKillCnt()
    {
        return isset($this->kill_cnt) ? $this->kill_cnt : 0;
    }

    public function hasKillCnt()
    {
        return isset($this->kill_cnt);
    }

    public function clearKillCnt()
    {
        unset($this->kill_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 kill_cnt = 4;</code>
     *
     * @return $this
     */
    public function setKillCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->kill_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 boss_life = 5;</code>
     *
     * @return int
     */
    public function getBossLife()
    {
        return isset($this->boss_life) ? $this->boss_life : 0;
    }

    public function hasBossLife()
    {
        return isset($this->boss_life);
    }

    public function clearBossLife()
    {
        unset($this->boss_life);
    }

    /**
     * Generated from protobuf field <code>optional uint32 boss_life = 5;</code>
     *
     * @return $this
     */
    public function setBossLife(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->boss_life = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 total_damage = 6;</code>
     *
     * @return int
     */
    public function getTotalDamage()
    {
        return isset($this->total_damage) ? $this->total_damage : 0;
    }

    public function hasTotalDamage()
    {
        return isset($this->total_damage);
    }

    public function clearTotalDamage()
    {
        unset($this->total_damage);
    }

    /**
     * Generated from protobuf field <code>optional uint32 total_damage = 6;</code>
     *
     * @return $this
     */
    public function setTotalDamage(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->total_damage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 critical_cnt = 7;</code>
     *
     * @return int
     */
    public function getCriticalCnt()
    {
        return isset($this->critical_cnt) ? $this->critical_cnt : 0;
    }

    public function hasCriticalCnt()
    {
        return isset($this->critical_cnt);
    }

    public function clearCriticalCnt()
    {
        unset($this->critical_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 critical_cnt = 7;</code>
     *
     * @return $this
     */
    public function setCriticalCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->critical_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 special_move_cnt = 8;</code>
     *
     * @return int
     */
    public function getSpecialMoveCnt()
    {
        return isset($this->special_move_cnt) ? $this->special_move_cnt : 0;
    }

    public function hasSpecialMoveCnt()
    {
        return isset($this->special_move_cnt);
    }

    public function clearSpecialMoveCnt()
    {
        unset($this->special_move_cnt);
    }

    /**
     * Generated from protobuf field <code>optional uint32 special_move_cnt = 8;</code>
     *
     * @return $this
     */
    public function setSpecialMoveCnt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->special_move_cnt = $var;

        return $this;
    }
}
