<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Murasaki\Taiko\HeadClerk2Request;

use App\GameProtocol\Proto\Murasaki\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.murasaki.HeadClerk2Request.PlayData</code>
 */
class PlayData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional string net_id = 2;</code>
     */
    protected $net_id = null;

    /**
     * Generated from protobuf field <code>optional string played_at = 3;</code>
     */
    protected $played_at = null;

    /**
     * Generated from protobuf field <code>optional bool is_right = 4;</code>
     */
    protected $is_right = null;

    /**
     * Generated from protobuf field <code>optional string place_id = 5;</code>
     */
    protected $place_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 type = 6;</code>
     */
    protected $type = null;

    /**
     * Generated from protobuf field <code>optional uint32 amount = 7;</code>
     */
    protected $amount = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $baid
     * @type string $net_id
     * @type string $played_at
     * @type bool $is_right
     * @type string $place_id
     * @type int $type
     * @type int $amount
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string net_id = 2;</code>
     *
     * @return string
     */
    public function getNetId()
    {
        return isset($this->net_id) ? $this->net_id : '';
    }

    public function hasNetId()
    {
        return isset($this->net_id);
    }

    public function clearNetId()
    {
        unset($this->net_id);
    }

    /**
     * Generated from protobuf field <code>optional string net_id = 2;</code>
     *
     * @return $this
     */
    public function setNetId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->net_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string played_at = 3;</code>
     *
     * @return string
     */
    public function getPlayedAt()
    {
        return isset($this->played_at) ? $this->played_at : '';
    }

    public function hasPlayedAt()
    {
        return isset($this->played_at);
    }

    public function clearPlayedAt()
    {
        unset($this->played_at);
    }

    /**
     * Generated from protobuf field <code>optional string played_at = 3;</code>
     *
     * @return $this
     */
    public function setPlayedAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->played_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_right = 4;</code>
     *
     * @return bool
     */
    public function getIsRight()
    {
        return isset($this->is_right) ? $this->is_right : false;
    }

    public function hasIsRight()
    {
        return isset($this->is_right);
    }

    public function clearIsRight()
    {
        unset($this->is_right);
    }

    /**
     * Generated from protobuf field <code>optional bool is_right = 4;</code>
     *
     * @return $this
     */
    public function setIsRight(bool $var)
    {
        $this->is_right = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string place_id = 5;</code>
     *
     * @return string
     */
    public function getPlaceId()
    {
        return isset($this->place_id) ? $this->place_id : '';
    }

    public function hasPlaceId()
    {
        return isset($this->place_id);
    }

    public function clearPlaceId()
    {
        unset($this->place_id);
    }

    /**
     * Generated from protobuf field <code>optional string place_id = 5;</code>
     *
     * @return $this
     */
    public function setPlaceId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->place_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 type = 6;</code>
     *
     * @return int
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : 0;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 type = 6;</code>
     *
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 amount = 7;</code>
     *
     * @return int
     */
    public function getAmount()
    {
        return isset($this->amount) ? $this->amount : 0;
    }

    public function hasAmount()
    {
        return isset($this->amount);
    }

    public function clearAmount()
    {
        unset($this->amount);
    }

    /**
     * Generated from protobuf field <code>optional uint32 amount = 7;</code>
     *
     * @return $this
     */
    public function setAmount(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->amount = $var;

        return $this;
    }
}
