<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Yellow\Taiko;

use App\GameProtocol\Proto\Yellow\Metadata\Taiko;
use App\GameProtocol\Proto\Yellow\Taiko\ChallengeCompeResponse\CompeData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.yellow.ChallengeCompeResponse</code>
 */
class ChallengeCompeResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_challenge_stat = 2;</code>
     */
    private $ary_challenge_stat;

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_user_compe_stat = 3;</code>
     */
    private $ary_user_compe_stat;

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_bng_compe_stat = 4;</code>
     */
    private $ary_bng_compe_stat;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type \App\GameProtocol\Proto\Yellow\Taiko\ChallengeCompeResponse\CompeData[] $ary_challenge_stat
     * @type \App\GameProtocol\Proto\Yellow\Taiko\ChallengeCompeResponse\CompeData[] $ary_user_compe_stat
     * @type \App\GameProtocol\Proto\Yellow\Taiko\ChallengeCompeResponse\CompeData[] $ary_bng_compe_stat
     *                                                                               }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_challenge_stat = 2;</code>
     *
     * @return RepeatedField<CompeData>
     */
    public function getAryChallengeStat()
    {
        return $this->ary_challenge_stat;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_challenge_stat = 2;</code>
     *
     * @param  CompeData[]  $var
     * @return $this
     */
    public function setAryChallengeStat(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, CompeData::class);
        $this->ary_challenge_stat = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_user_compe_stat = 3;</code>
     *
     * @return RepeatedField<CompeData>
     */
    public function getAryUserCompeStat()
    {
        return $this->ary_user_compe_stat;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_user_compe_stat = 3;</code>
     *
     * @param  CompeData[]  $var
     * @return $this
     */
    public function setAryUserCompeStat(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, CompeData::class);
        $this->ary_user_compe_stat = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_bng_compe_stat = 4;</code>
     *
     * @return RepeatedField<CompeData>
     */
    public function getAryBngCompeStat()
    {
        return $this->ary_bng_compe_stat;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.ChallengeCompeResponse.CompeData ary_bng_compe_stat = 4;</code>
     *
     * @param  CompeData[]  $var
     * @return $this
     */
    public function setAryBngCompeStat(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, CompeData::class);
        $this->ary_bng_compe_stat = $arr;

        return $this;
    }
}
