<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Yellow\Taiko;

use App\GameProtocol\Proto\Yellow\Metadata\Taiko;
use App\GameProtocol\Proto\Yellow\Taiko\HeadClerk2Request\PlayData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.yellow.HeadClerk2Request</code>
 */
class HeadClerk2Request extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional string current_place_id = 3;</code>
     */
    protected $current_place_id = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.HeadClerk2Request.PlayData ary_play_info = 4;</code>
     */
    private $ary_play_info;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type string $shop_id
     * @type string $current_place_id
     * @type \App\GameProtocol\Proto\Yellow\Taiko\HeadClerk2Request\PlayData[] $ary_play_info
     *                                                                         }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 2;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string current_place_id = 3;</code>
     *
     * @return string
     */
    public function getCurrentPlaceId()
    {
        return isset($this->current_place_id) ? $this->current_place_id : '';
    }

    public function hasCurrentPlaceId()
    {
        return isset($this->current_place_id);
    }

    public function clearCurrentPlaceId()
    {
        unset($this->current_place_id);
    }

    /**
     * Generated from protobuf field <code>optional string current_place_id = 3;</code>
     *
     * @return $this
     */
    public function setCurrentPlaceId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->current_place_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.HeadClerk2Request.PlayData ary_play_info = 4;</code>
     *
     * @return RepeatedField<PlayData>
     */
    public function getAryPlayInfo()
    {
        return $this->ary_play_info;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.HeadClerk2Request.PlayData ary_play_info = 4;</code>
     *
     * @param  PlayData[]  $var
     * @return $this
     */
    public function setAryPlayInfo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, PlayData::class);
        $this->ary_play_info = $arr;

        return $this;
    }
}
