<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Yellow\Taiko;

use App\GameProtocol\Proto\Yellow\Metadata\Taiko;
use App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\CollaboData;
use App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\CostumeData;
use App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\StageData;
use App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\TokkunstageData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.yellow.PlayResultRequest</code>
 */
class PlayResultRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional string play_datetime = 4;</code>
     */
    protected $play_datetime = null;

    /**
     * Generated from protobuf field <code>optional bool is_right = 5;</code>
     */
    protected $is_right = null;

    /**
     * Generated from protobuf field <code>optional uint32 card_type = 6;</code>
     */
    protected $card_type = null;

    /**
     * Generated from protobuf field <code>optional bool is_two_players = 7;</code>
     */
    protected $is_two_players = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.PlayResultRequest.StageData ary_stage_info = 8;</code>
     */
    private $ary_stage_info;

    /**
     * Generated from protobuf field <code>repeated uint32 release_song_no = 9;</code>
     */
    private $release_song_no;

    /**
     * Generated from protobuf field <code>repeated uint32 get_tone_no = 10;</code>
     */
    private $get_tone_no;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_1 = 11;</code>
     */
    private $get_costume_no_1;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_2 = 12;</code>
     */
    private $get_costume_no_2;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_3 = 13;</code>
     */
    private $get_costume_no_3;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_4 = 14;</code>
     */
    private $get_costume_no_4;

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_5 = 15;</code>
     */
    private $get_costume_no_5;

    /**
     * Generated from protobuf field <code>repeated uint32 get_title_no = 16;</code>
     */
    private $get_title_no;

    /**
     * Generated from protobuf field <code>optional bool bonus_daily_flg = 17;</code>
     */
    protected $bonus_daily_flg = null;

    /**
     * Generated from protobuf field <code>optional bool bonus_weekly_flg = 18;</code>
     */
    protected $bonus_weekly_flg = null;

    /**
     * Generated from protobuf field <code>optional bool bonus_monthly_flg = 19;</code>
     */
    protected $bonus_monthly_flg = null;

    /**
     * Generated from protobuf field <code>optional uint32 get_donmedal = 20;</code>
     */
    protected $get_donmedal = null;

    /**
     * Generated from protobuf field <code>optional uint32 get_katsumedal = 21;</code>
     */
    protected $get_katsumedal = null;

    /**
     * Generated from protobuf field <code>optional uint32 itemshop_tutorial_flg = 22;</code>
     */
    protected $itemshop_tutorial_flg = null;

    /**
     * Generated from protobuf field <code>optional bool is_devil = 23;</code>
     */
    protected $is_devil = null;

    /**
     * Generated from protobuf field <code>optional bool is_explain = 24;</code>
     */
    protected $is_explain = null;

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.CostumeData ary_play_costume = 25;</code>
     */
    protected $ary_play_costume = null;

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.CostumeData ary_current_costume = 26;</code>
     */
    protected $ary_current_costume = null;

    /**
     * Generated from protobuf field <code>optional uint32 gender_type = 27;</code>
     */
    protected $gender_type = null;

    /**
     * Generated from protobuf field <code>optional uint32 player_age = 28;</code>
     */
    protected $player_age = null;

    /**
     * Generated from protobuf field <code>optional uint32 play_mode = 29;</code>
     */
    protected $play_mode = null;

    /**
     * Generated from protobuf field <code>optional uint32 area_code = 30;</code>
     */
    protected $area_code = null;

    /**
     * Generated from protobuf field <code>optional bytes reserved = 31;</code>
     */
    protected $reserved = null;

    /**
     * Generated from protobuf field <code>optional uint32 lowerlimit_age = 32;</code>
     */
    protected $lowerlimit_age = null;

    /**
     * Generated from protobuf field <code>optional uint32 upperlimit_age = 33;</code>
     */
    protected $upperlimit_age = null;

    /**
     * Generated from protobuf field <code>optional uint32 age_score = 34;</code>
     */
    protected $age_score = null;

    /**
     * Generated from protobuf field <code>optional uint32 estimation_count = 35;</code>
     */
    protected $estimation_count = null;

    /**
     * Generated from protobuf field <code>optional uint32 dan_result = 36;</code>
     */
    protected $dan_result = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.PlayResultRequest.CollaboData ary_collabo_info = 37;</code>
     */
    private $ary_collabo_info;

    /**
     * Generated from protobuf field <code>optional uint32 tournament_mode = 38;</code>
     */
    protected $tournament_mode = null;

    /**
     * Generated from protobuf field <code>optional string accesstoken = 39;</code>
     */
    protected $accesstoken = null;

    /**
     * Generated from protobuf field <code>optional bytes content_info = 40;</code>
     */
    protected $content_info = null;

    /**
     * Generated from protobuf field <code>optional uint32 difficulty_played_course = 41;</code>
     */
    protected $difficulty_played_course = null;

    /**
     * Generated from protobuf field <code>optional uint32 difficulty_played_star = 42;</code>
     */
    protected $difficulty_played_star = null;

    /**
     * Generated from protobuf field <code>optional uint32 payment_method = 43;</code>
     */
    protected $payment_method = null;

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_tutorial_flg = 44;</code>
     */
    protected $tokkun_tutorial_flg = null;

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.TokkunstageData ary_tokkunstage_info = 45;</code>
     */
    protected $ary_tokkunstage_info = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $baid
     * @type string $chassis_id
     * @type string $shop_id
     * @type string $play_datetime
     * @type bool $is_right
     * @type int $card_type
     * @type bool $is_two_players
     * @type \App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\StageData[] $ary_stage_info
     * @type int[] $release_song_no
     * @type int[] $get_tone_no
     * @type int[] $get_costume_no_1
     * @type int[] $get_costume_no_2
     * @type int[] $get_costume_no_3
     * @type int[] $get_costume_no_4
     * @type int[] $get_costume_no_5
     * @type int[] $get_title_no
     * @type bool $bonus_daily_flg
     * @type bool $bonus_weekly_flg
     * @type bool $bonus_monthly_flg
     * @type int $get_donmedal
     * @type int $get_katsumedal
     * @type int $itemshop_tutorial_flg
     * @type bool $is_devil
     * @type bool $is_explain
     * @type \App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\CostumeData $ary_play_costume
     * @type \App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\CostumeData $ary_current_costume
     * @type int $gender_type
     * @type int $player_age
     * @type int $play_mode
     * @type int $area_code
     * @type string $reserved
     * @type int $lowerlimit_age
     * @type int $upperlimit_age
     * @type int $age_score
     * @type int $estimation_count
     * @type int $dan_result
     * @type \App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\CollaboData[] $ary_collabo_info
     * @type int $tournament_mode
     * @type string $accesstoken
     * @type string $content_info
     * @type int $difficulty_played_course
     * @type int $difficulty_played_star
     * @type int $payment_method
     * @type int $tokkun_tutorial_flg
     * @type \App\GameProtocol\Proto\Yellow\Taiko\PlayResultRequest\TokkunstageData $ary_tokkunstage_info
     *                                                                              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 2;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 3;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string play_datetime = 4;</code>
     *
     * @return string
     */
    public function getPlayDatetime()
    {
        return isset($this->play_datetime) ? $this->play_datetime : '';
    }

    public function hasPlayDatetime()
    {
        return isset($this->play_datetime);
    }

    public function clearPlayDatetime()
    {
        unset($this->play_datetime);
    }

    /**
     * Generated from protobuf field <code>optional string play_datetime = 4;</code>
     *
     * @return $this
     */
    public function setPlayDatetime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->play_datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_right = 5;</code>
     *
     * @return bool
     */
    public function getIsRight()
    {
        return isset($this->is_right) ? $this->is_right : false;
    }

    public function hasIsRight()
    {
        return isset($this->is_right);
    }

    public function clearIsRight()
    {
        unset($this->is_right);
    }

    /**
     * Generated from protobuf field <code>optional bool is_right = 5;</code>
     *
     * @return $this
     */
    public function setIsRight(bool $var)
    {
        $this->is_right = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 card_type = 6;</code>
     *
     * @return int
     */
    public function getCardType()
    {
        return isset($this->card_type) ? $this->card_type : 0;
    }

    public function hasCardType()
    {
        return isset($this->card_type);
    }

    public function clearCardType()
    {
        unset($this->card_type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 card_type = 6;</code>
     *
     * @return $this
     */
    public function setCardType(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->card_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_two_players = 7;</code>
     *
     * @return bool
     */
    public function getIsTwoPlayers()
    {
        return isset($this->is_two_players) ? $this->is_two_players : false;
    }

    public function hasIsTwoPlayers()
    {
        return isset($this->is_two_players);
    }

    public function clearIsTwoPlayers()
    {
        unset($this->is_two_players);
    }

    /**
     * Generated from protobuf field <code>optional bool is_two_players = 7;</code>
     *
     * @return $this
     */
    public function setIsTwoPlayers(bool $var)
    {
        $this->is_two_players = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.PlayResultRequest.StageData ary_stage_info = 8;</code>
     *
     * @return RepeatedField<StageData>
     */
    public function getAryStageInfo()
    {
        return $this->ary_stage_info;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.PlayResultRequest.StageData ary_stage_info = 8;</code>
     *
     * @param  StageData[]  $var
     * @return $this
     */
    public function setAryStageInfo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, StageData::class);
        $this->ary_stage_info = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_song_no = 9;</code>
     *
     * @return RepeatedField<int>
     */
    public function getReleaseSongNo()
    {
        return $this->release_song_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 release_song_no = 9;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setReleaseSongNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->release_song_no = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_tone_no = 10;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetToneNo()
    {
        return $this->get_tone_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_tone_no = 10;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetToneNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_tone_no = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_1 = 11;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo1()
    {
        return $this->get_costume_no_1;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_1 = 11;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo1(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_1 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_2 = 12;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo2()
    {
        return $this->get_costume_no_2;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_2 = 12;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo2(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_2 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_3 = 13;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo3()
    {
        return $this->get_costume_no_3;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_3 = 13;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo3(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_3 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_4 = 14;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo4()
    {
        return $this->get_costume_no_4;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_4 = 14;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo4(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_4 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_5 = 15;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetCostumeNo5()
    {
        return $this->get_costume_no_5;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_costume_no_5 = 15;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetCostumeNo5(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_costume_no_5 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_title_no = 16;</code>
     *
     * @return RepeatedField<int>
     */
    public function getGetTitleNo()
    {
        return $this->get_title_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 get_title_no = 16;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setGetTitleNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->get_title_no = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool bonus_daily_flg = 17;</code>
     *
     * @return bool
     */
    public function getBonusDailyFlg()
    {
        return isset($this->bonus_daily_flg) ? $this->bonus_daily_flg : false;
    }

    public function hasBonusDailyFlg()
    {
        return isset($this->bonus_daily_flg);
    }

    public function clearBonusDailyFlg()
    {
        unset($this->bonus_daily_flg);
    }

    /**
     * Generated from protobuf field <code>optional bool bonus_daily_flg = 17;</code>
     *
     * @return $this
     */
    public function setBonusDailyFlg(bool $var)
    {
        $this->bonus_daily_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool bonus_weekly_flg = 18;</code>
     *
     * @return bool
     */
    public function getBonusWeeklyFlg()
    {
        return isset($this->bonus_weekly_flg) ? $this->bonus_weekly_flg : false;
    }

    public function hasBonusWeeklyFlg()
    {
        return isset($this->bonus_weekly_flg);
    }

    public function clearBonusWeeklyFlg()
    {
        unset($this->bonus_weekly_flg);
    }

    /**
     * Generated from protobuf field <code>optional bool bonus_weekly_flg = 18;</code>
     *
     * @return $this
     */
    public function setBonusWeeklyFlg(bool $var)
    {
        $this->bonus_weekly_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool bonus_monthly_flg = 19;</code>
     *
     * @return bool
     */
    public function getBonusMonthlyFlg()
    {
        return isset($this->bonus_monthly_flg) ? $this->bonus_monthly_flg : false;
    }

    public function hasBonusMonthlyFlg()
    {
        return isset($this->bonus_monthly_flg);
    }

    public function clearBonusMonthlyFlg()
    {
        unset($this->bonus_monthly_flg);
    }

    /**
     * Generated from protobuf field <code>optional bool bonus_monthly_flg = 19;</code>
     *
     * @return $this
     */
    public function setBonusMonthlyFlg(bool $var)
    {
        $this->bonus_monthly_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 get_donmedal = 20;</code>
     *
     * @return int
     */
    public function getGetDonmedal()
    {
        return isset($this->get_donmedal) ? $this->get_donmedal : 0;
    }

    public function hasGetDonmedal()
    {
        return isset($this->get_donmedal);
    }

    public function clearGetDonmedal()
    {
        unset($this->get_donmedal);
    }

    /**
     * Generated from protobuf field <code>optional uint32 get_donmedal = 20;</code>
     *
     * @return $this
     */
    public function setGetDonmedal(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->get_donmedal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 get_katsumedal = 21;</code>
     *
     * @return int
     */
    public function getGetKatsumedal()
    {
        return isset($this->get_katsumedal) ? $this->get_katsumedal : 0;
    }

    public function hasGetKatsumedal()
    {
        return isset($this->get_katsumedal);
    }

    public function clearGetKatsumedal()
    {
        unset($this->get_katsumedal);
    }

    /**
     * Generated from protobuf field <code>optional uint32 get_katsumedal = 21;</code>
     *
     * @return $this
     */
    public function setGetKatsumedal(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->get_katsumedal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 itemshop_tutorial_flg = 22;</code>
     *
     * @return int
     */
    public function getItemshopTutorialFlg()
    {
        return isset($this->itemshop_tutorial_flg) ? $this->itemshop_tutorial_flg : 0;
    }

    public function hasItemshopTutorialFlg()
    {
        return isset($this->itemshop_tutorial_flg);
    }

    public function clearItemshopTutorialFlg()
    {
        unset($this->itemshop_tutorial_flg);
    }

    /**
     * Generated from protobuf field <code>optional uint32 itemshop_tutorial_flg = 22;</code>
     *
     * @return $this
     */
    public function setItemshopTutorialFlg(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->itemshop_tutorial_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_devil = 23;</code>
     *
     * @return bool
     */
    public function getIsDevil()
    {
        return isset($this->is_devil) ? $this->is_devil : false;
    }

    public function hasIsDevil()
    {
        return isset($this->is_devil);
    }

    public function clearIsDevil()
    {
        unset($this->is_devil);
    }

    /**
     * Generated from protobuf field <code>optional bool is_devil = 23;</code>
     *
     * @return $this
     */
    public function setIsDevil(bool $var)
    {
        $this->is_devil = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_explain = 24;</code>
     *
     * @return bool
     */
    public function getIsExplain()
    {
        return isset($this->is_explain) ? $this->is_explain : false;
    }

    public function hasIsExplain()
    {
        return isset($this->is_explain);
    }

    public function clearIsExplain()
    {
        unset($this->is_explain);
    }

    /**
     * Generated from protobuf field <code>optional bool is_explain = 24;</code>
     *
     * @return $this
     */
    public function setIsExplain(bool $var)
    {
        $this->is_explain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.CostumeData ary_play_costume = 25;</code>
     *
     * @return CostumeData|null
     */
    public function getAryPlayCostume()
    {
        return $this->ary_play_costume;
    }

    public function hasAryPlayCostume()
    {
        return isset($this->ary_play_costume);
    }

    public function clearAryPlayCostume()
    {
        unset($this->ary_play_costume);
    }

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.CostumeData ary_play_costume = 25;</code>
     *
     * @return $this
     */
    public function setAryPlayCostume(?CostumeData $var)
    {
        $this->ary_play_costume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.CostumeData ary_current_costume = 26;</code>
     *
     * @return CostumeData|null
     */
    public function getAryCurrentCostume()
    {
        return $this->ary_current_costume;
    }

    public function hasAryCurrentCostume()
    {
        return isset($this->ary_current_costume);
    }

    public function clearAryCurrentCostume()
    {
        unset($this->ary_current_costume);
    }

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.CostumeData ary_current_costume = 26;</code>
     *
     * @return $this
     */
    public function setAryCurrentCostume(?CostumeData $var)
    {
        $this->ary_current_costume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 gender_type = 27;</code>
     *
     * @return int
     */
    public function getGenderType()
    {
        return isset($this->gender_type) ? $this->gender_type : 0;
    }

    public function hasGenderType()
    {
        return isset($this->gender_type);
    }

    public function clearGenderType()
    {
        unset($this->gender_type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 gender_type = 27;</code>
     *
     * @return $this
     */
    public function setGenderType(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->gender_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 player_age = 28;</code>
     *
     * @return int
     */
    public function getPlayerAge()
    {
        return isset($this->player_age) ? $this->player_age : 0;
    }

    public function hasPlayerAge()
    {
        return isset($this->player_age);
    }

    public function clearPlayerAge()
    {
        unset($this->player_age);
    }

    /**
     * Generated from protobuf field <code>optional uint32 player_age = 28;</code>
     *
     * @return $this
     */
    public function setPlayerAge(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->player_age = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_mode = 29;</code>
     *
     * @return int
     */
    public function getPlayMode()
    {
        return isset($this->play_mode) ? $this->play_mode : 0;
    }

    public function hasPlayMode()
    {
        return isset($this->play_mode);
    }

    public function clearPlayMode()
    {
        unset($this->play_mode);
    }

    /**
     * Generated from protobuf field <code>optional uint32 play_mode = 29;</code>
     *
     * @return $this
     */
    public function setPlayMode(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->play_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 area_code = 30;</code>
     *
     * @return int
     */
    public function getAreaCode()
    {
        return isset($this->area_code) ? $this->area_code : 0;
    }

    public function hasAreaCode()
    {
        return isset($this->area_code);
    }

    public function clearAreaCode()
    {
        unset($this->area_code);
    }

    /**
     * Generated from protobuf field <code>optional uint32 area_code = 30;</code>
     *
     * @return $this
     */
    public function setAreaCode(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->area_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes reserved = 31;</code>
     *
     * @return string
     */
    public function getReserved()
    {
        return isset($this->reserved) ? $this->reserved : '';
    }

    public function hasReserved()
    {
        return isset($this->reserved);
    }

    public function clearReserved()
    {
        unset($this->reserved);
    }

    /**
     * Generated from protobuf field <code>optional bytes reserved = 31;</code>
     *
     * @return $this
     */
    public function setReserved(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->reserved = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 lowerlimit_age = 32;</code>
     *
     * @return int
     */
    public function getLowerlimitAge()
    {
        return isset($this->lowerlimit_age) ? $this->lowerlimit_age : 0;
    }

    public function hasLowerlimitAge()
    {
        return isset($this->lowerlimit_age);
    }

    public function clearLowerlimitAge()
    {
        unset($this->lowerlimit_age);
    }

    /**
     * Generated from protobuf field <code>optional uint32 lowerlimit_age = 32;</code>
     *
     * @return $this
     */
    public function setLowerlimitAge(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->lowerlimit_age = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 upperlimit_age = 33;</code>
     *
     * @return int
     */
    public function getUpperlimitAge()
    {
        return isset($this->upperlimit_age) ? $this->upperlimit_age : 0;
    }

    public function hasUpperlimitAge()
    {
        return isset($this->upperlimit_age);
    }

    public function clearUpperlimitAge()
    {
        unset($this->upperlimit_age);
    }

    /**
     * Generated from protobuf field <code>optional uint32 upperlimit_age = 33;</code>
     *
     * @return $this
     */
    public function setUpperlimitAge(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->upperlimit_age = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 age_score = 34;</code>
     *
     * @return int
     */
    public function getAgeScore()
    {
        return isset($this->age_score) ? $this->age_score : 0;
    }

    public function hasAgeScore()
    {
        return isset($this->age_score);
    }

    public function clearAgeScore()
    {
        unset($this->age_score);
    }

    /**
     * Generated from protobuf field <code>optional uint32 age_score = 34;</code>
     *
     * @return $this
     */
    public function setAgeScore(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->age_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 estimation_count = 35;</code>
     *
     * @return int
     */
    public function getEstimationCount()
    {
        return isset($this->estimation_count) ? $this->estimation_count : 0;
    }

    public function hasEstimationCount()
    {
        return isset($this->estimation_count);
    }

    public function clearEstimationCount()
    {
        unset($this->estimation_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 estimation_count = 35;</code>
     *
     * @return $this
     */
    public function setEstimationCount(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->estimation_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 dan_result = 36;</code>
     *
     * @return int
     */
    public function getDanResult()
    {
        return isset($this->dan_result) ? $this->dan_result : 0;
    }

    public function hasDanResult()
    {
        return isset($this->dan_result);
    }

    public function clearDanResult()
    {
        unset($this->dan_result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 dan_result = 36;</code>
     *
     * @return $this
     */
    public function setDanResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->dan_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.PlayResultRequest.CollaboData ary_collabo_info = 37;</code>
     *
     * @return RepeatedField<CollaboData>
     */
    public function getAryCollaboInfo()
    {
        return $this->ary_collabo_info;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.yellow.PlayResultRequest.CollaboData ary_collabo_info = 37;</code>
     *
     * @param  CollaboData[]  $var
     * @return $this
     */
    public function setAryCollaboInfo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, CollaboData::class);
        $this->ary_collabo_info = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tournament_mode = 38;</code>
     *
     * @return int
     */
    public function getTournamentMode()
    {
        return isset($this->tournament_mode) ? $this->tournament_mode : 0;
    }

    public function hasTournamentMode()
    {
        return isset($this->tournament_mode);
    }

    public function clearTournamentMode()
    {
        unset($this->tournament_mode);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tournament_mode = 38;</code>
     *
     * @return $this
     */
    public function setTournamentMode(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->tournament_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string accesstoken = 39;</code>
     *
     * @return string
     */
    public function getAccesstoken()
    {
        return isset($this->accesstoken) ? $this->accesstoken : '';
    }

    public function hasAccesstoken()
    {
        return isset($this->accesstoken);
    }

    public function clearAccesstoken()
    {
        unset($this->accesstoken);
    }

    /**
     * Generated from protobuf field <code>optional string accesstoken = 39;</code>
     *
     * @return $this
     */
    public function setAccesstoken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->accesstoken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes content_info = 40;</code>
     *
     * @return string
     */
    public function getContentInfo()
    {
        return isset($this->content_info) ? $this->content_info : '';
    }

    public function hasContentInfo()
    {
        return isset($this->content_info);
    }

    public function clearContentInfo()
    {
        unset($this->content_info);
    }

    /**
     * Generated from protobuf field <code>optional bytes content_info = 40;</code>
     *
     * @return $this
     */
    public function setContentInfo(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->content_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 difficulty_played_course = 41;</code>
     *
     * @return int
     */
    public function getDifficultyPlayedCourse()
    {
        return isset($this->difficulty_played_course) ? $this->difficulty_played_course : 0;
    }

    public function hasDifficultyPlayedCourse()
    {
        return isset($this->difficulty_played_course);
    }

    public function clearDifficultyPlayedCourse()
    {
        unset($this->difficulty_played_course);
    }

    /**
     * Generated from protobuf field <code>optional uint32 difficulty_played_course = 41;</code>
     *
     * @return $this
     */
    public function setDifficultyPlayedCourse(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->difficulty_played_course = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 difficulty_played_star = 42;</code>
     *
     * @return int
     */
    public function getDifficultyPlayedStar()
    {
        return isset($this->difficulty_played_star) ? $this->difficulty_played_star : 0;
    }

    public function hasDifficultyPlayedStar()
    {
        return isset($this->difficulty_played_star);
    }

    public function clearDifficultyPlayedStar()
    {
        unset($this->difficulty_played_star);
    }

    /**
     * Generated from protobuf field <code>optional uint32 difficulty_played_star = 42;</code>
     *
     * @return $this
     */
    public function setDifficultyPlayedStar(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->difficulty_played_star = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 payment_method = 43;</code>
     *
     * @return int
     */
    public function getPaymentMethod()
    {
        return isset($this->payment_method) ? $this->payment_method : 0;
    }

    public function hasPaymentMethod()
    {
        return isset($this->payment_method);
    }

    public function clearPaymentMethod()
    {
        unset($this->payment_method);
    }

    /**
     * Generated from protobuf field <code>optional uint32 payment_method = 43;</code>
     *
     * @return $this
     */
    public function setPaymentMethod(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->payment_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_tutorial_flg = 44;</code>
     *
     * @return int
     */
    public function getTokkunTutorialFlg()
    {
        return isset($this->tokkun_tutorial_flg) ? $this->tokkun_tutorial_flg : 0;
    }

    public function hasTokkunTutorialFlg()
    {
        return isset($this->tokkun_tutorial_flg);
    }

    public function clearTokkunTutorialFlg()
    {
        unset($this->tokkun_tutorial_flg);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tokkun_tutorial_flg = 44;</code>
     *
     * @return $this
     */
    public function setTokkunTutorialFlg(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->tokkun_tutorial_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.TokkunstageData ary_tokkunstage_info = 45;</code>
     *
     * @return TokkunstageData|null
     */
    public function getAryTokkunstageInfo()
    {
        return $this->ary_tokkunstage_info;
    }

    public function hasAryTokkunstageInfo()
    {
        return isset($this->ary_tokkunstage_info);
    }

    public function clearAryTokkunstageInfo()
    {
        unset($this->ary_tokkunstage_info);
    }

    /**
     * Generated from protobuf field <code>optional .taiko.yellow.PlayResultRequest.TokkunstageData ary_tokkunstage_info = 45;</code>
     *
     * @return $this
     */
    public function setAryTokkunstageInfo(?TokkunstageData $var)
    {
        $this->ary_tokkunstage_info = $var;

        return $this;
    }
}
