<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Red\Taiko;

use App\GameProtocol\Green\Proto\Red\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.red.BanacoinpaymentResponse</code>
 */
class BanacoinpaymentResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional string personid = 2;</code>
     */
    protected $personid = null;

    /**
     * Generated from protobuf field <code>optional string bnid_result = 3;</code>
     */
    protected $bnid_result = null;

    /**
     * Generated from protobuf field <code>optional string chid = 4;</code>
     */
    protected $chid = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type string $personid
     * @type string $bnid_result
     * @type string $chid
     *              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string personid = 2;</code>
     *
     * @return string
     */
    public function getPersonid()
    {
        return isset($this->personid) ? $this->personid : '';
    }

    public function hasPersonid()
    {
        return isset($this->personid);
    }

    public function clearPersonid()
    {
        unset($this->personid);
    }

    /**
     * Generated from protobuf field <code>optional string personid = 2;</code>
     *
     * @return $this
     */
    public function setPersonid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->personid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string bnid_result = 3;</code>
     *
     * @return string
     */
    public function getBnidResult()
    {
        return isset($this->bnid_result) ? $this->bnid_result : '';
    }

    public function hasBnidResult()
    {
        return isset($this->bnid_result);
    }

    public function clearBnidResult()
    {
        unset($this->bnid_result);
    }

    /**
     * Generated from protobuf field <code>optional string bnid_result = 3;</code>
     *
     * @return $this
     */
    public function setBnidResult(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->bnid_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chid = 4;</code>
     *
     * @return string
     */
    public function getChid()
    {
        return isset($this->chid) ? $this->chid : '';
    }

    public function hasChid()
    {
        return isset($this->chid);
    }

    public function clearChid()
    {
        unset($this->chid);
    }

    /**
     * Generated from protobuf field <code>optional string chid = 4;</code>
     *
     * @return $this
     */
    public function setChid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chid = $var;

        return $this;
    }
}
