<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_blue.proto

namespace App\GameProtocol\Proto\Blue\Taiko\PlayResultRequest\StageData;

use App\GameProtocol\Proto\Blue\Metadata\TaikoBlue;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.blue.PlayResultRequest.StageData.ResultcompeData</code>
 */
class ResultcompeData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 compe_id = 1;</code>
     */
    protected $compe_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 track_no = 2;</code>
     */
    protected $track_no = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $compe_id
     * @type int $track_no
     *           }
     */
    public function __construct($data = null)
    {
        TaikoBlue::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 compe_id = 1;</code>
     *
     * @return int
     */
    public function getCompeId()
    {
        return isset($this->compe_id) ? $this->compe_id : 0;
    }

    public function hasCompeId()
    {
        return isset($this->compe_id);
    }

    public function clearCompeId()
    {
        unset($this->compe_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 compe_id = 1;</code>
     *
     * @return $this
     */
    public function setCompeId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->compe_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 track_no = 2;</code>
     *
     * @return int
     */
    public function getTrackNo()
    {
        return isset($this->track_no) ? $this->track_no : 0;
    }

    public function hasTrackNo()
    {
        return isset($this->track_no);
    }

    public function clearTrackNo()
    {
        unset($this->track_no);
    }

    /**
     * Generated from protobuf field <code>optional uint32 track_no = 2;</code>
     *
     * @return $this
     */
    public function setTrackNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->track_no = $var;

        return $this;
    }
}
