<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_murasaki.proto

namespace App\GameProtocol\Proto\Murasaki\Taiko;

use App\GameProtocol\Proto\Murasaki\Metadata\TaikoMurasaki;
use App\GameProtocol\Proto\Murasaki\Taiko\BAIDResponse\CostumeData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.murasaki.BAIDResponse</code>
 */
class BAIDResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 player_type = 2;</code>
     */
    protected $player_type = null;

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_result = 3;</code>
     */
    protected $com_svr_result = null;

    /**
     * Generated from protobuf field <code>optional uint32 mb_id = 4;</code>
     */
    protected $mb_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 baid = 5;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional string access_code = 6;</code>
     */
    protected $access_code = null;

    /**
     * Generated from protobuf field <code>optional bool is_publish = 7;</code>
     */
    protected $is_publish = null;

    /**
     * Generated from protobuf field <code>optional uint32 card_own_num = 8;</code>
     */
    protected $card_own_num = null;

    /**
     * Generated from protobuf field <code>optional string reg_country_id = 9;</code>
     */
    protected $reg_country_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 purpose_id = 10;</code>
     */
    protected $purpose_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 region_id = 11;</code>
     */
    protected $region_id = null;

    /**
     * Generated from protobuf field <code>optional string mydon_name = 12;</code>
     */
    protected $mydon_name = null;

    /**
     * Generated from protobuf field <code>optional string title = 13;</code>
     */
    protected $title = null;

    /**
     * Generated from protobuf field <code>optional uint32 color_face = 14;</code>
     */
    protected $color_face = null;

    /**
     * Generated from protobuf field <code>optional uint32 color_body = 15;</code>
     */
    protected $color_body = null;

    /**
     * Generated from protobuf field <code>optional uint32 color_limb = 16;</code>
     */
    protected $color_limb = null;

    /**
     * Generated from protobuf field <code>optional .taiko.murasaki.BAIDResponse.CostumeData ary_costumedata = 17;</code>
     */
    protected $ary_costumedata = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.BAIDResponse.CostumeData ary_favorite_costumedata = 18;</code>
     */
    private $ary_favorite_costumedata;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 19;</code>
     */
    protected $costume_flg_1 = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 20;</code>
     */
    protected $costume_flg_2 = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 21;</code>
     */
    protected $costume_flg_3 = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_4 = 22;</code>
     */
    protected $costume_flg_4 = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_5 = 23;</code>
     */
    protected $costume_flg_5 = null;

    /**
     * Generated from protobuf field <code>optional uint32 reward_ptn = 24;</code>
     */
    protected $reward_ptn = null;

    /**
     * Generated from protobuf field <code>optional string update_datetime = 25;</code>
     */
    protected $update_datetime = null;

    /**
     * Generated from protobuf field <code>optional uint32 disp_dan_type = 26;</code>
     */
    protected $disp_dan_type = null;

    /**
     * Generated from protobuf field <code>optional uint32 got_dan_max = 27;</code>
     */
    protected $got_dan_max = null;

    /**
     * Generated from protobuf field <code>optional bytes got_dan_flg = 28;</code>
     */
    protected $got_dan_flg = null;

    /**
     * Generated from protobuf field <code>optional string accesstoken = 29;</code>
     */
    protected $accesstoken = null;

    /**
     * Generated from protobuf field <code>optional bytes content_info = 30;</code>
     */
    protected $content_info = null;

    /**
     * Generated from protobuf field <code>optional uint32 default_tone_setting = 31;</code>
     */
    protected $default_tone_setting = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $player_type
     * @type int $com_svr_result
     * @type int $mb_id
     * @type int $baid
     * @type string $access_code
     * @type bool $is_publish
     * @type int $card_own_num
     * @type string $reg_country_id
     * @type int $purpose_id
     * @type int $region_id
     * @type string $mydon_name
     * @type string $title
     * @type int $color_face
     * @type int $color_body
     * @type int $color_limb
     * @type \App\GameProtocol\Proto\Murasaki\Taiko\BAIDResponse\CostumeData $ary_costumedata
     * @type \App\GameProtocol\Proto\Murasaki\Taiko\BAIDResponse\CostumeData[] $ary_favorite_costumedata
     * @type string $costume_flg_1
     * @type string $costume_flg_2
     * @type string $costume_flg_3
     * @type string $costume_flg_4
     * @type string $costume_flg_5
     * @type int $reward_ptn
     * @type string $update_datetime
     * @type int $disp_dan_type
     * @type int $got_dan_max
     * @type string $got_dan_flg
     * @type string $accesstoken
     * @type string $content_info
     * @type int $default_tone_setting
     *           }
     */
    public function __construct($data = null)
    {
        TaikoMurasaki::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 player_type = 2;</code>
     *
     * @return int
     */
    public function getPlayerType()
    {
        return isset($this->player_type) ? $this->player_type : 0;
    }

    public function hasPlayerType()
    {
        return isset($this->player_type);
    }

    public function clearPlayerType()
    {
        unset($this->player_type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 player_type = 2;</code>
     *
     * @return $this
     */
    public function setPlayerType(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->player_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_result = 3;</code>
     *
     * @return int
     */
    public function getComSvrResult()
    {
        return isset($this->com_svr_result) ? $this->com_svr_result : 0;
    }

    public function hasComSvrResult()
    {
        return isset($this->com_svr_result);
    }

    public function clearComSvrResult()
    {
        unset($this->com_svr_result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 com_svr_result = 3;</code>
     *
     * @return $this
     */
    public function setComSvrResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->com_svr_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 mb_id = 4;</code>
     *
     * @return int
     */
    public function getMbId()
    {
        return isset($this->mb_id) ? $this->mb_id : 0;
    }

    public function hasMbId()
    {
        return isset($this->mb_id);
    }

    public function clearMbId()
    {
        unset($this->mb_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 mb_id = 4;</code>
     *
     * @return $this
     */
    public function setMbId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->mb_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 5;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 5;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string access_code = 6;</code>
     *
     * @return string
     */
    public function getAccessCode()
    {
        return isset($this->access_code) ? $this->access_code : '';
    }

    public function hasAccessCode()
    {
        return isset($this->access_code);
    }

    public function clearAccessCode()
    {
        unset($this->access_code);
    }

    /**
     * Generated from protobuf field <code>optional string access_code = 6;</code>
     *
     * @return $this
     */
    public function setAccessCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->access_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_publish = 7;</code>
     *
     * @return bool
     */
    public function getIsPublish()
    {
        return isset($this->is_publish) ? $this->is_publish : false;
    }

    public function hasIsPublish()
    {
        return isset($this->is_publish);
    }

    public function clearIsPublish()
    {
        unset($this->is_publish);
    }

    /**
     * Generated from protobuf field <code>optional bool is_publish = 7;</code>
     *
     * @return $this
     */
    public function setIsPublish(bool $var)
    {
        $this->is_publish = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 card_own_num = 8;</code>
     *
     * @return int
     */
    public function getCardOwnNum()
    {
        return isset($this->card_own_num) ? $this->card_own_num : 0;
    }

    public function hasCardOwnNum()
    {
        return isset($this->card_own_num);
    }

    public function clearCardOwnNum()
    {
        unset($this->card_own_num);
    }

    /**
     * Generated from protobuf field <code>optional uint32 card_own_num = 8;</code>
     *
     * @return $this
     */
    public function setCardOwnNum(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->card_own_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string reg_country_id = 9;</code>
     *
     * @return string
     */
    public function getRegCountryId()
    {
        return isset($this->reg_country_id) ? $this->reg_country_id : '';
    }

    public function hasRegCountryId()
    {
        return isset($this->reg_country_id);
    }

    public function clearRegCountryId()
    {
        unset($this->reg_country_id);
    }

    /**
     * Generated from protobuf field <code>optional string reg_country_id = 9;</code>
     *
     * @return $this
     */
    public function setRegCountryId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->reg_country_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 purpose_id = 10;</code>
     *
     * @return int
     */
    public function getPurposeId()
    {
        return isset($this->purpose_id) ? $this->purpose_id : 0;
    }

    public function hasPurposeId()
    {
        return isset($this->purpose_id);
    }

    public function clearPurposeId()
    {
        unset($this->purpose_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 purpose_id = 10;</code>
     *
     * @return $this
     */
    public function setPurposeId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->purpose_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 region_id = 11;</code>
     *
     * @return int
     */
    public function getRegionId()
    {
        return isset($this->region_id) ? $this->region_id : 0;
    }

    public function hasRegionId()
    {
        return isset($this->region_id);
    }

    public function clearRegionId()
    {
        unset($this->region_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 region_id = 11;</code>
     *
     * @return $this
     */
    public function setRegionId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->region_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string mydon_name = 12;</code>
     *
     * @return string
     */
    public function getMydonName()
    {
        return isset($this->mydon_name) ? $this->mydon_name : '';
    }

    public function hasMydonName()
    {
        return isset($this->mydon_name);
    }

    public function clearMydonName()
    {
        unset($this->mydon_name);
    }

    /**
     * Generated from protobuf field <code>optional string mydon_name = 12;</code>
     *
     * @return $this
     */
    public function setMydonName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->mydon_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string title = 13;</code>
     *
     * @return string
     */
    public function getTitle()
    {
        return isset($this->title) ? $this->title : '';
    }

    public function hasTitle()
    {
        return isset($this->title);
    }

    public function clearTitle()
    {
        unset($this->title);
    }

    /**
     * Generated from protobuf field <code>optional string title = 13;</code>
     *
     * @return $this
     */
    public function setTitle(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 color_face = 14;</code>
     *
     * @return int
     */
    public function getColorFace()
    {
        return isset($this->color_face) ? $this->color_face : 0;
    }

    public function hasColorFace()
    {
        return isset($this->color_face);
    }

    public function clearColorFace()
    {
        unset($this->color_face);
    }

    /**
     * Generated from protobuf field <code>optional uint32 color_face = 14;</code>
     *
     * @return $this
     */
    public function setColorFace(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->color_face = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 color_body = 15;</code>
     *
     * @return int
     */
    public function getColorBody()
    {
        return isset($this->color_body) ? $this->color_body : 0;
    }

    public function hasColorBody()
    {
        return isset($this->color_body);
    }

    public function clearColorBody()
    {
        unset($this->color_body);
    }

    /**
     * Generated from protobuf field <code>optional uint32 color_body = 15;</code>
     *
     * @return $this
     */
    public function setColorBody(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->color_body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 color_limb = 16;</code>
     *
     * @return int
     */
    public function getColorLimb()
    {
        return isset($this->color_limb) ? $this->color_limb : 0;
    }

    public function hasColorLimb()
    {
        return isset($this->color_limb);
    }

    public function clearColorLimb()
    {
        unset($this->color_limb);
    }

    /**
     * Generated from protobuf field <code>optional uint32 color_limb = 16;</code>
     *
     * @return $this
     */
    public function setColorLimb(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->color_limb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .taiko.murasaki.BAIDResponse.CostumeData ary_costumedata = 17;</code>
     *
     * @return CostumeData|null
     */
    public function getAryCostumedata()
    {
        return $this->ary_costumedata;
    }

    public function hasAryCostumedata()
    {
        return isset($this->ary_costumedata);
    }

    public function clearAryCostumedata()
    {
        unset($this->ary_costumedata);
    }

    /**
     * Generated from protobuf field <code>optional .taiko.murasaki.BAIDResponse.CostumeData ary_costumedata = 17;</code>
     *
     * @return $this
     */
    public function setAryCostumedata(?CostumeData $var)
    {
        $this->ary_costumedata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.BAIDResponse.CostumeData ary_favorite_costumedata = 18;</code>
     *
     * @return RepeatedField<CostumeData>
     */
    public function getAryFavoriteCostumedata()
    {
        return $this->ary_favorite_costumedata;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.BAIDResponse.CostumeData ary_favorite_costumedata = 18;</code>
     *
     * @param  CostumeData[]  $var
     * @return $this
     */
    public function setAryFavoriteCostumedata(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, CostumeData::class);
        $this->ary_favorite_costumedata = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 19;</code>
     *
     * @return string
     */
    public function getCostumeFlg1()
    {
        return isset($this->costume_flg_1) ? $this->costume_flg_1 : '';
    }

    public function hasCostumeFlg1()
    {
        return isset($this->costume_flg_1);
    }

    public function clearCostumeFlg1()
    {
        unset($this->costume_flg_1);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 19;</code>
     *
     * @return $this
     */
    public function setCostumeFlg1(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 20;</code>
     *
     * @return string
     */
    public function getCostumeFlg2()
    {
        return isset($this->costume_flg_2) ? $this->costume_flg_2 : '';
    }

    public function hasCostumeFlg2()
    {
        return isset($this->costume_flg_2);
    }

    public function clearCostumeFlg2()
    {
        unset($this->costume_flg_2);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 20;</code>
     *
     * @return $this
     */
    public function setCostumeFlg2(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 21;</code>
     *
     * @return string
     */
    public function getCostumeFlg3()
    {
        return isset($this->costume_flg_3) ? $this->costume_flg_3 : '';
    }

    public function hasCostumeFlg3()
    {
        return isset($this->costume_flg_3);
    }

    public function clearCostumeFlg3()
    {
        unset($this->costume_flg_3);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 21;</code>
     *
     * @return $this
     */
    public function setCostumeFlg3(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_4 = 22;</code>
     *
     * @return string
     */
    public function getCostumeFlg4()
    {
        return isset($this->costume_flg_4) ? $this->costume_flg_4 : '';
    }

    public function hasCostumeFlg4()
    {
        return isset($this->costume_flg_4);
    }

    public function clearCostumeFlg4()
    {
        unset($this->costume_flg_4);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_4 = 22;</code>
     *
     * @return $this
     */
    public function setCostumeFlg4(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_4 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_5 = 23;</code>
     *
     * @return string
     */
    public function getCostumeFlg5()
    {
        return isset($this->costume_flg_5) ? $this->costume_flg_5 : '';
    }

    public function hasCostumeFlg5()
    {
        return isset($this->costume_flg_5);
    }

    public function clearCostumeFlg5()
    {
        unset($this->costume_flg_5);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_5 = 23;</code>
     *
     * @return $this
     */
    public function setCostumeFlg5(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_5 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 reward_ptn = 24;</code>
     *
     * @return int
     */
    public function getRewardPtn()
    {
        return isset($this->reward_ptn) ? $this->reward_ptn : 0;
    }

    public function hasRewardPtn()
    {
        return isset($this->reward_ptn);
    }

    public function clearRewardPtn()
    {
        unset($this->reward_ptn);
    }

    /**
     * Generated from protobuf field <code>optional uint32 reward_ptn = 24;</code>
     *
     * @return $this
     */
    public function setRewardPtn(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->reward_ptn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string update_datetime = 25;</code>
     *
     * @return string
     */
    public function getUpdateDatetime()
    {
        return isset($this->update_datetime) ? $this->update_datetime : '';
    }

    public function hasUpdateDatetime()
    {
        return isset($this->update_datetime);
    }

    public function clearUpdateDatetime()
    {
        unset($this->update_datetime);
    }

    /**
     * Generated from protobuf field <code>optional string update_datetime = 25;</code>
     *
     * @return $this
     */
    public function setUpdateDatetime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->update_datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 disp_dan_type = 26;</code>
     *
     * @return int
     */
    public function getDispDanType()
    {
        return isset($this->disp_dan_type) ? $this->disp_dan_type : 0;
    }

    public function hasDispDanType()
    {
        return isset($this->disp_dan_type);
    }

    public function clearDispDanType()
    {
        unset($this->disp_dan_type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 disp_dan_type = 26;</code>
     *
     * @return $this
     */
    public function setDispDanType(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->disp_dan_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 got_dan_max = 27;</code>
     *
     * @return int
     */
    public function getGotDanMax()
    {
        return isset($this->got_dan_max) ? $this->got_dan_max : 0;
    }

    public function hasGotDanMax()
    {
        return isset($this->got_dan_max);
    }

    public function clearGotDanMax()
    {
        unset($this->got_dan_max);
    }

    /**
     * Generated from protobuf field <code>optional uint32 got_dan_max = 27;</code>
     *
     * @return $this
     */
    public function setGotDanMax(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->got_dan_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes got_dan_flg = 28;</code>
     *
     * @return string
     */
    public function getGotDanFlg()
    {
        return isset($this->got_dan_flg) ? $this->got_dan_flg : '';
    }

    public function hasGotDanFlg()
    {
        return isset($this->got_dan_flg);
    }

    public function clearGotDanFlg()
    {
        unset($this->got_dan_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes got_dan_flg = 28;</code>
     *
     * @return $this
     */
    public function setGotDanFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->got_dan_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string accesstoken = 29;</code>
     *
     * @return string
     */
    public function getAccesstoken()
    {
        return isset($this->accesstoken) ? $this->accesstoken : '';
    }

    public function hasAccesstoken()
    {
        return isset($this->accesstoken);
    }

    public function clearAccesstoken()
    {
        unset($this->accesstoken);
    }

    /**
     * Generated from protobuf field <code>optional string accesstoken = 29;</code>
     *
     * @return $this
     */
    public function setAccesstoken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->accesstoken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes content_info = 30;</code>
     *
     * @return string
     */
    public function getContentInfo()
    {
        return isset($this->content_info) ? $this->content_info : '';
    }

    public function hasContentInfo()
    {
        return isset($this->content_info);
    }

    public function clearContentInfo()
    {
        unset($this->content_info);
    }

    /**
     * Generated from protobuf field <code>optional bytes content_info = 30;</code>
     *
     * @return $this
     */
    public function setContentInfo(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->content_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 default_tone_setting = 31;</code>
     *
     * @return int
     */
    public function getDefaultToneSetting()
    {
        return isset($this->default_tone_setting) ? $this->default_tone_setting : 0;
    }

    public function hasDefaultToneSetting()
    {
        return isset($this->default_tone_setting);
    }

    public function clearDefaultToneSetting()
    {
        unset($this->default_tone_setting);
    }

    /**
     * Generated from protobuf field <code>optional uint32 default_tone_setting = 31;</code>
     *
     * @return $this
     */
    public function setDefaultToneSetting(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->default_tone_setting = $var;

        return $this;
    }
}
