<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Murasaki\Taiko;

use App\GameProtocol\Proto\Murasaki\Metadata\Taiko;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.murasaki.GetfolderResponse</code>
 */
class GetfolderResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 folder_id = 2;</code>
     */
    protected $folder_id = null;

    /**
     * Generated from protobuf field <code>repeated uint32 song_no = 3;</code>
     */
    private $song_no;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $folder_id
     * @type int[] $song_no
     *             }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 folder_id = 2;</code>
     *
     * @return int
     */
    public function getFolderId()
    {
        return isset($this->folder_id) ? $this->folder_id : 0;
    }

    public function hasFolderId()
    {
        return isset($this->folder_id);
    }

    public function clearFolderId()
    {
        unset($this->folder_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 folder_id = 2;</code>
     *
     * @return $this
     */
    public function setFolderId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->folder_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 song_no = 3;</code>
     *
     * @return RepeatedField<int>
     */
    public function getSongNo()
    {
        return $this->song_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 song_no = 3;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setSongNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->song_no = $arr;

        return $this;
    }
}
