<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_murasaki.proto

namespace App\GameProtocol\Proto\Murasaki\Taiko;

use App\GameProtocol\Proto\Murasaki\Metadata\TaikoMurasaki;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.murasaki.ShoppingResultRequest</code>
 */
class ShoppingResultRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     */
    protected $baid = null;

    /**
     * Generated from protobuf field <code>optional string shopping_datetime = 2;</code>
     */
    protected $shopping_datetime = null;

    /**
     * Generated from protobuf field <code>optional string chassis_id = 3;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional string shop_id = 4;</code>
     */
    protected $shop_id = null;

    /**
     * Generated from protobuf field <code>optional bool is_right = 5;</code>
     */
    protected $is_right = null;

    /**
     * Generated from protobuf field <code>optional uint32 use_donpoint = 6;</code>
     */
    protected $use_donpoint = null;

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 7;</code>
     */
    protected $tone_flg = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 8;</code>
     */
    protected $costume_flg_1 = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 9;</code>
     */
    protected $costume_flg_2 = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 10;</code>
     */
    protected $costume_flg_3 = null;

    /**
     * Generated from protobuf field <code>repeated uint32 ary_shopping_song_no = 11;</code>
     */
    private $ary_shopping_song_no;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $baid
     * @type string $shopping_datetime
     * @type string $chassis_id
     * @type string $shop_id
     * @type bool $is_right
     * @type int $use_donpoint
     * @type string $tone_flg
     * @type string $costume_flg_1
     * @type string $costume_flg_2
     * @type string $costume_flg_3
     * @type int[] $ary_shopping_song_no
     *             }
     */
    public function __construct($data = null)
    {
        TaikoMurasaki::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return int
     */
    public function getBaid()
    {
        return isset($this->baid) ? $this->baid : 0;
    }

    public function hasBaid()
    {
        return isset($this->baid);
    }

    public function clearBaid()
    {
        unset($this->baid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 baid = 1;</code>
     *
     * @return $this
     */
    public function setBaid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->baid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shopping_datetime = 2;</code>
     *
     * @return string
     */
    public function getShoppingDatetime()
    {
        return isset($this->shopping_datetime) ? $this->shopping_datetime : '';
    }

    public function hasShoppingDatetime()
    {
        return isset($this->shopping_datetime);
    }

    public function clearShoppingDatetime()
    {
        unset($this->shopping_datetime);
    }

    /**
     * Generated from protobuf field <code>optional string shopping_datetime = 2;</code>
     *
     * @return $this
     */
    public function setShoppingDatetime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shopping_datetime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 3;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 3;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 4;</code>
     *
     * @return string
     */
    public function getShopId()
    {
        return isset($this->shop_id) ? $this->shop_id : '';
    }

    public function hasShopId()
    {
        return isset($this->shop_id);
    }

    public function clearShopId()
    {
        unset($this->shop_id);
    }

    /**
     * Generated from protobuf field <code>optional string shop_id = 4;</code>
     *
     * @return $this
     */
    public function setShopId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_right = 5;</code>
     *
     * @return bool
     */
    public function getIsRight()
    {
        return isset($this->is_right) ? $this->is_right : false;
    }

    public function hasIsRight()
    {
        return isset($this->is_right);
    }

    public function clearIsRight()
    {
        unset($this->is_right);
    }

    /**
     * Generated from protobuf field <code>optional bool is_right = 5;</code>
     *
     * @return $this
     */
    public function setIsRight(bool $var)
    {
        $this->is_right = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 use_donpoint = 6;</code>
     *
     * @return int
     */
    public function getUseDonpoint()
    {
        return isset($this->use_donpoint) ? $this->use_donpoint : 0;
    }

    public function hasUseDonpoint()
    {
        return isset($this->use_donpoint);
    }

    public function clearUseDonpoint()
    {
        unset($this->use_donpoint);
    }

    /**
     * Generated from protobuf field <code>optional uint32 use_donpoint = 6;</code>
     *
     * @return $this
     */
    public function setUseDonpoint(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->use_donpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 7;</code>
     *
     * @return string
     */
    public function getToneFlg()
    {
        return isset($this->tone_flg) ? $this->tone_flg : '';
    }

    public function hasToneFlg()
    {
        return isset($this->tone_flg);
    }

    public function clearToneFlg()
    {
        unset($this->tone_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 7;</code>
     *
     * @return $this
     */
    public function setToneFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->tone_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 8;</code>
     *
     * @return string
     */
    public function getCostumeFlg1()
    {
        return isset($this->costume_flg_1) ? $this->costume_flg_1 : '';
    }

    public function hasCostumeFlg1()
    {
        return isset($this->costume_flg_1);
    }

    public function clearCostumeFlg1()
    {
        unset($this->costume_flg_1);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 8;</code>
     *
     * @return $this
     */
    public function setCostumeFlg1(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 9;</code>
     *
     * @return string
     */
    public function getCostumeFlg2()
    {
        return isset($this->costume_flg_2) ? $this->costume_flg_2 : '';
    }

    public function hasCostumeFlg2()
    {
        return isset($this->costume_flg_2);
    }

    public function clearCostumeFlg2()
    {
        unset($this->costume_flg_2);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 9;</code>
     *
     * @return $this
     */
    public function setCostumeFlg2(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 10;</code>
     *
     * @return string
     */
    public function getCostumeFlg3()
    {
        return isset($this->costume_flg_3) ? $this->costume_flg_3 : '';
    }

    public function hasCostumeFlg3()
    {
        return isset($this->costume_flg_3);
    }

    public function clearCostumeFlg3()
    {
        unset($this->costume_flg_3);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 10;</code>
     *
     * @return $this
     */
    public function setCostumeFlg3(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ary_shopping_song_no = 11;</code>
     *
     * @return RepeatedField<int>
     */
    public function getAryShoppingSongNo()
    {
        return $this->ary_shopping_song_no;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ary_shopping_song_no = 11;</code>
     *
     * @param  int[]  $var
     * @return $this
     */
    public function setAryShoppingSongNo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->ary_shopping_song_no = $arr;

        return $this;
    }
}
