<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vsinterface_red.proto

namespace App\GameProtocol\Proto\Red\VsInterface\StartupAuthResponse;

use App\GameProtocol\Proto\Red\Metadata\VsinterfaceRed;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>vsinterface.red.StartupAuthResponse.OperationData</code>
 */
class OperationData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 key_data = 1;</code>
     */
    protected $key_data = null;

    /**
     * Generated from protobuf field <code>optional bytes value_data = 2;</code>
     */
    protected $value_data = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $key_data
     * @type string $value_data
     *              }
     */
    public function __construct($data = null)
    {
        VsinterfaceRed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 key_data = 1;</code>
     *
     * @return int
     */
    public function getKeyData()
    {
        return isset($this->key_data) ? $this->key_data : 0;
    }

    public function hasKeyData()
    {
        return isset($this->key_data);
    }

    public function clearKeyData()
    {
        unset($this->key_data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 key_data = 1;</code>
     *
     * @return $this
     */
    public function setKeyData(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->key_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes value_data = 2;</code>
     *
     * @return string
     */
    public function getValueData()
    {
        return isset($this->value_data) ? $this->value_data : '';
    }

    public function hasValueData()
    {
        return isset($this->value_data);
    }

    public function clearValueData()
    {
        unset($this->value_data);
    }

    /**
     * Generated from protobuf field <code>optional bytes value_data = 2;</code>
     *
     * @return $this
     */
    public function setValueData(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->value_data = $var;

        return $this;
    }
}
