<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_katsudon.proto

namespace App\GameProtocol\Proto\Katsudon\Taiko;

use App\GameProtocol\Proto\Katsudon\Metadata\TaikoKatsudon;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.katsudon.DefaultsongResponse</code>
 */
class DefaultsongResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional bytes default_song_flg = 2;</code>
     */
    protected $default_song_flg = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type string $default_song_flg
     *              }
     */
    public function __construct($data = null)
    {
        TaikoKatsudon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes default_song_flg = 2;</code>
     *
     * @return string
     */
    public function getDefaultSongFlg()
    {
        return isset($this->default_song_flg) ? $this->default_song_flg : '';
    }

    public function hasDefaultSongFlg()
    {
        return isset($this->default_song_flg);
    }

    public function clearDefaultSongFlg()
    {
        unset($this->default_song_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes default_song_flg = 2;</code>
     *
     * @return $this
     */
    public function setDefaultSongFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->default_song_flg = $var;

        return $this;
    }
}
