<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_katsudon.proto

namespace App\GameProtocol\Proto\Katsudon\Taiko;

use App\GameProtocol\Proto\Katsudon\Metadata\TaikoKatsudon;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.katsudon.GetTelopRequest</code>
 */
class GetTelopRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 telop_id = 2;</code>
     */
    protected $telop_id = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type int $telop_id
     *           }
     */
    public function __construct($data = null)
    {
        TaikoKatsudon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 telop_id = 2;</code>
     *
     * @return int
     */
    public function getTelopId()
    {
        return isset($this->telop_id) ? $this->telop_id : 0;
    }

    public function hasTelopId()
    {
        return isset($this->telop_id);
    }

    public function clearTelopId()
    {
        unset($this->telop_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 telop_id = 2;</code>
     *
     * @return $this
     */
    public function setTelopId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->telop_id = $var;

        return $this;
    }
}
