<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_katsudon.proto

namespace App\GameProtocol\Proto\Katsudon\Taiko;

use App\GameProtocol\Proto\Katsudon\Metadata\TaikoKatsudon;
use App\GameProtocol\Proto\Katsudon\Taiko\SongInfoResponse\GroupData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.katsudon.SongInfoResponse</code>
 */
class SongInfoResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.katsudon.SongInfoResponse.GroupData ary_group_score = 2;</code>
     */
    private $ary_group_score;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type \App\GameProtocol\Proto\Katsudon\Taiko\SongInfoResponse\GroupData[] $ary_group_score
     *                                                                           }
     */
    public function __construct($data = null)
    {
        TaikoKatsudon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.katsudon.SongInfoResponse.GroupData ary_group_score = 2;</code>
     *
     * @return RepeatedField<GroupData>
     */
    public function getAryGroupScore()
    {
        return $this->ary_group_score;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.katsudon.SongInfoResponse.GroupData ary_group_score = 2;</code>
     *
     * @param  GroupData[]  $var
     * @return $this
     */
    public function setAryGroupScore(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, GroupData::class);
        $this->ary_group_score = $arr;

        return $this;
    }
}
