<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Murasaki\Taiko;

use App\GameProtocol\Green\Proto\Murasaki\Metadata\Taiko;
use App\GameProtocol\Green\Proto\Murasaki\Taiko\BestScoreResponse\SongData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.murasaki.BestScoreResponse</code>
 */
class BestScoreResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 seq_id = 2;</code>
     */
    protected $seq_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 last_seq_id = 3;</code>
     */
    protected $last_seq_id = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.BestScoreResponse.SongData ary_song_score = 4;</code>
     */
    private $ary_song_score;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $seq_id
     * @type int $last_seq_id
     * @type \App\GameProtocol\Green\Proto\Murasaki\Taiko\BestScoreResponse\SongData[] $ary_song_score
     *                                                                                 }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 seq_id = 2;</code>
     *
     * @return int
     */
    public function getSeqId()
    {
        return isset($this->seq_id) ? $this->seq_id : 0;
    }

    public function hasSeqId()
    {
        return isset($this->seq_id);
    }

    public function clearSeqId()
    {
        unset($this->seq_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 seq_id = 2;</code>
     *
     * @return $this
     */
    public function setSeqId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->seq_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_seq_id = 3;</code>
     *
     * @return int
     */
    public function getLastSeqId()
    {
        return isset($this->last_seq_id) ? $this->last_seq_id : 0;
    }

    public function hasLastSeqId()
    {
        return isset($this->last_seq_id);
    }

    public function clearLastSeqId()
    {
        unset($this->last_seq_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_seq_id = 3;</code>
     *
     * @return $this
     */
    public function setLastSeqId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_seq_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.BestScoreResponse.SongData ary_song_score = 4;</code>
     *
     * @return RepeatedField<SongData>
     */
    public function getArySongScore()
    {
        return $this->ary_song_score;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.murasaki.BestScoreResponse.SongData ary_song_score = 4;</code>
     *
     * @param  SongData[]  $var
     * @return $this
     */
    public function setArySongScore(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, SongData::class);
        $this->ary_song_score = $arr;

        return $this;
    }
}
