<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Murasaki\Taiko;

use App\GameProtocol\Green\Proto\Murasaki\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.murasaki.BestScoreRequest</code>
 */
class BestScoreRequest extends Message
{
    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     */
    protected $chassis_id = null;

    /**
     * Generated from protobuf field <code>optional uint32 seq_id = 2;</code>
     */
    protected $seq_id = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $chassis_id
     * @type int $seq_id
     *           }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return string
     */
    public function getChassisId()
    {
        return isset($this->chassis_id) ? $this->chassis_id : '';
    }

    public function hasChassisId()
    {
        return isset($this->chassis_id);
    }

    public function clearChassisId()
    {
        unset($this->chassis_id);
    }

    /**
     * Generated from protobuf field <code>optional string chassis_id = 1;</code>
     *
     * @return $this
     */
    public function setChassisId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->chassis_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 seq_id = 2;</code>
     *
     * @return int
     */
    public function getSeqId()
    {
        return isset($this->seq_id) ? $this->seq_id : 0;
    }

    public function hasSeqId()
    {
        return isset($this->seq_id);
    }

    public function clearSeqId()
    {
        unset($this->seq_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 seq_id = 2;</code>
     *
     * @return $this
     */
    public function setSeqId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->seq_id = $var;

        return $this;
    }
}
