<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Murasaki\Taiko;

use App\GameProtocol\Green\Proto\Murasaki\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.murasaki.ShoppingResultResponse</code>
 */
class ShoppingResultResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 total_get_donpoint = 2;</code>
     */
    protected $total_get_donpoint = null;

    /**
     * Generated from protobuf field <code>optional uint32 total_use_donpoint = 3;</code>
     */
    protected $total_use_donpoint = null;

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 4;</code>
     */
    protected $tone_flg = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 5;</code>
     */
    protected $costume_flg_1 = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 6;</code>
     */
    protected $costume_flg_2 = null;

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 7;</code>
     */
    protected $costume_flg_3 = null;

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 8;</code>
     */
    protected $song_hash_ver = null;

    /**
     * Generated from protobuf field <code>optional bytes hash_release_song_flg = 9;</code>
     */
    protected $hash_release_song_flg = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $total_get_donpoint
     * @type int $total_use_donpoint
     * @type string $tone_flg
     * @type string $costume_flg_1
     * @type string $costume_flg_2
     * @type string $costume_flg_3
     * @type int $song_hash_ver
     * @type string $hash_release_song_flg
     *              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 total_get_donpoint = 2;</code>
     *
     * @return int
     */
    public function getTotalGetDonpoint()
    {
        return isset($this->total_get_donpoint) ? $this->total_get_donpoint : 0;
    }

    public function hasTotalGetDonpoint()
    {
        return isset($this->total_get_donpoint);
    }

    public function clearTotalGetDonpoint()
    {
        unset($this->total_get_donpoint);
    }

    /**
     * Generated from protobuf field <code>optional uint32 total_get_donpoint = 2;</code>
     *
     * @return $this
     */
    public function setTotalGetDonpoint(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->total_get_donpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 total_use_donpoint = 3;</code>
     *
     * @return int
     */
    public function getTotalUseDonpoint()
    {
        return isset($this->total_use_donpoint) ? $this->total_use_donpoint : 0;
    }

    public function hasTotalUseDonpoint()
    {
        return isset($this->total_use_donpoint);
    }

    public function clearTotalUseDonpoint()
    {
        unset($this->total_use_donpoint);
    }

    /**
     * Generated from protobuf field <code>optional uint32 total_use_donpoint = 3;</code>
     *
     * @return $this
     */
    public function setTotalUseDonpoint(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->total_use_donpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 4;</code>
     *
     * @return string
     */
    public function getToneFlg()
    {
        return isset($this->tone_flg) ? $this->tone_flg : '';
    }

    public function hasToneFlg()
    {
        return isset($this->tone_flg);
    }

    public function clearToneFlg()
    {
        unset($this->tone_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes tone_flg = 4;</code>
     *
     * @return $this
     */
    public function setToneFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->tone_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 5;</code>
     *
     * @return string
     */
    public function getCostumeFlg1()
    {
        return isset($this->costume_flg_1) ? $this->costume_flg_1 : '';
    }

    public function hasCostumeFlg1()
    {
        return isset($this->costume_flg_1);
    }

    public function clearCostumeFlg1()
    {
        unset($this->costume_flg_1);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_1 = 5;</code>
     *
     * @return $this
     */
    public function setCostumeFlg1(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 6;</code>
     *
     * @return string
     */
    public function getCostumeFlg2()
    {
        return isset($this->costume_flg_2) ? $this->costume_flg_2 : '';
    }

    public function hasCostumeFlg2()
    {
        return isset($this->costume_flg_2);
    }

    public function clearCostumeFlg2()
    {
        unset($this->costume_flg_2);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_2 = 6;</code>
     *
     * @return $this
     */
    public function setCostumeFlg2(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 7;</code>
     *
     * @return string
     */
    public function getCostumeFlg3()
    {
        return isset($this->costume_flg_3) ? $this->costume_flg_3 : '';
    }

    public function hasCostumeFlg3()
    {
        return isset($this->costume_flg_3);
    }

    public function clearCostumeFlg3()
    {
        unset($this->costume_flg_3);
    }

    /**
     * Generated from protobuf field <code>optional bytes costume_flg_3 = 7;</code>
     *
     * @return $this
     */
    public function setCostumeFlg3(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->costume_flg_3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 8;</code>
     *
     * @return int
     */
    public function getSongHashVer()
    {
        return isset($this->song_hash_ver) ? $this->song_hash_ver : 0;
    }

    public function hasSongHashVer()
    {
        return isset($this->song_hash_ver);
    }

    public function clearSongHashVer()
    {
        unset($this->song_hash_ver);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 8;</code>
     *
     * @return $this
     */
    public function setSongHashVer(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->song_hash_ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes hash_release_song_flg = 9;</code>
     *
     * @return string
     */
    public function getHashReleaseSongFlg()
    {
        return isset($this->hash_release_song_flg) ? $this->hash_release_song_flg : '';
    }

    public function hasHashReleaseSongFlg()
    {
        return isset($this->hash_release_song_flg);
    }

    public function clearHashReleaseSongFlg()
    {
        unset($this->hash_release_song_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes hash_release_song_flg = 9;</code>
     *
     * @return $this
     */
    public function setHashReleaseSongFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->hash_release_song_flg = $var;

        return $this;
    }
}
