<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Green\Proto\Blue\Taiko\BattleUserDataResponse;

use App\GameProtocol\Green\Proto\Blue\Metadata\Taiko;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.blue.BattleUserDataResponse.BattleUserNpcData</code>
 */
class BattleUserNpcData extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 npc_id = 1;</code>
     */
    protected $npc_id = null;

    /**
     * Generated from protobuf field <code>optional string total_exp = 2;</code>
     */
    protected $total_exp = null;

    /**
     * Generated from protobuf field <code>optional uint32 max_dpn = 3;</code>
     */
    protected $max_dpn = null;

    /**
     * Generated from protobuf field <code>optional uint32 npc_costume_id = 4;</code>
     */
    protected $npc_costume_id = null;

    /**
     * Generated from protobuf field <code>optional bytes npc_costume_flg = 5;</code>
     */
    protected $npc_costume_flg = null;

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_1 = 6;</code>
     */
    protected $last_select_special_1 = null;

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_2 = 7;</code>
     */
    protected $last_select_special_2 = null;

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_3 = 8;</code>
     */
    protected $last_select_special_3 = null;

    /**
     * Generated from protobuf field <code>optional bytes release_special_flg = 9;</code>
     */
    protected $release_special_flg = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $npc_id
     * @type string $total_exp
     * @type int $max_dpn
     * @type int $npc_costume_id
     * @type string $npc_costume_flg
     * @type int $last_select_special_1
     * @type int $last_select_special_2
     * @type int $last_select_special_3
     * @type string $release_special_flg
     *              }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 npc_id = 1;</code>
     *
     * @return int
     */
    public function getNpcId()
    {
        return isset($this->npc_id) ? $this->npc_id : 0;
    }

    public function hasNpcId()
    {
        return isset($this->npc_id);
    }

    public function clearNpcId()
    {
        unset($this->npc_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 npc_id = 1;</code>
     *
     * @return $this
     */
    public function setNpcId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->npc_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string total_exp = 2;</code>
     *
     * @return string
     */
    public function getTotalExp()
    {
        return isset($this->total_exp) ? $this->total_exp : '';
    }

    public function hasTotalExp()
    {
        return isset($this->total_exp);
    }

    public function clearTotalExp()
    {
        unset($this->total_exp);
    }

    /**
     * Generated from protobuf field <code>optional string total_exp = 2;</code>
     *
     * @return $this
     */
    public function setTotalExp(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->total_exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 max_dpn = 3;</code>
     *
     * @return int
     */
    public function getMaxDpn()
    {
        return isset($this->max_dpn) ? $this->max_dpn : 0;
    }

    public function hasMaxDpn()
    {
        return isset($this->max_dpn);
    }

    public function clearMaxDpn()
    {
        unset($this->max_dpn);
    }

    /**
     * Generated from protobuf field <code>optional uint32 max_dpn = 3;</code>
     *
     * @return $this
     */
    public function setMaxDpn(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->max_dpn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 npc_costume_id = 4;</code>
     *
     * @return int
     */
    public function getNpcCostumeId()
    {
        return isset($this->npc_costume_id) ? $this->npc_costume_id : 0;
    }

    public function hasNpcCostumeId()
    {
        return isset($this->npc_costume_id);
    }

    public function clearNpcCostumeId()
    {
        unset($this->npc_costume_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 npc_costume_id = 4;</code>
     *
     * @return $this
     */
    public function setNpcCostumeId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->npc_costume_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes npc_costume_flg = 5;</code>
     *
     * @return string
     */
    public function getNpcCostumeFlg()
    {
        return isset($this->npc_costume_flg) ? $this->npc_costume_flg : '';
    }

    public function hasNpcCostumeFlg()
    {
        return isset($this->npc_costume_flg);
    }

    public function clearNpcCostumeFlg()
    {
        unset($this->npc_costume_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes npc_costume_flg = 5;</code>
     *
     * @return $this
     */
    public function setNpcCostumeFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->npc_costume_flg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_1 = 6;</code>
     *
     * @return int
     */
    public function getLastSelectSpecial1()
    {
        return isset($this->last_select_special_1) ? $this->last_select_special_1 : 0;
    }

    public function hasLastSelectSpecial1()
    {
        return isset($this->last_select_special_1);
    }

    public function clearLastSelectSpecial1()
    {
        unset($this->last_select_special_1);
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_1 = 6;</code>
     *
     * @return $this
     */
    public function setLastSelectSpecial1(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_select_special_1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_2 = 7;</code>
     *
     * @return int
     */
    public function getLastSelectSpecial2()
    {
        return isset($this->last_select_special_2) ? $this->last_select_special_2 : 0;
    }

    public function hasLastSelectSpecial2()
    {
        return isset($this->last_select_special_2);
    }

    public function clearLastSelectSpecial2()
    {
        unset($this->last_select_special_2);
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_2 = 7;</code>
     *
     * @return $this
     */
    public function setLastSelectSpecial2(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_select_special_2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_3 = 8;</code>
     *
     * @return int
     */
    public function getLastSelectSpecial3()
    {
        return isset($this->last_select_special_3) ? $this->last_select_special_3 : 0;
    }

    public function hasLastSelectSpecial3()
    {
        return isset($this->last_select_special_3);
    }

    public function clearLastSelectSpecial3()
    {
        unset($this->last_select_special_3);
    }

    /**
     * Generated from protobuf field <code>optional uint32 last_select_special_3 = 8;</code>
     *
     * @return $this
     */
    public function setLastSelectSpecial3(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_select_special_3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes release_special_flg = 9;</code>
     *
     * @return string
     */
    public function getReleaseSpecialFlg()
    {
        return isset($this->release_special_flg) ? $this->release_special_flg : '';
    }

    public function hasReleaseSpecialFlg()
    {
        return isset($this->release_special_flg);
    }

    public function clearReleaseSpecialFlg()
    {
        unset($this->release_special_flg);
    }

    /**
     * Generated from protobuf field <code>optional bytes release_special_flg = 9;</code>
     *
     * @return $this
     */
    public function setReleaseSpecialFlg(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->release_special_flg = $var;

        return $this;
    }
}
