syntax = "proto2";

message BookKeepingRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required string update_date = 3;
  required uint32 credit_cost_1 = 4;
  required uint32 credit_cost_2 = 5;
  required uint32 credit_songs_1 = 6;
  required uint32 credit_songs_2 = 7;
  required uint32 all_play_cnt = 8;
  required uint32 service_sw_cnt = 9;
  required uint32 free_play_cnt = 10;
}

message BookKeepingResponse {
  required uint32 result = 1;
}

message GettelopRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required uint32 telop_id = 3;
}

message GettelopResponse {
  required uint32 result = 1;
  optional uint32 verup_no = 2;
  optional string start_datetime = 3;
  optional string end_datetime = 4;
  optional string telop = 5;
}

message HeartBeatRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
}

message HeartBeatResponse {
  required uint32 result = 1;
  required uint32 com_svr_stat = 2;
  required uint32 game_svr_stat = 3;
  required uint32 bnid_svr_stat = 4;
  required uint32 banacoin_stat = 5;
}

message GetfolderRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  repeated uint32 folder_id = 3;
}

message GetfolderResponse {
  message EventfolderData {
    optional uint32 folder_id = 1;
    optional uint32 verup_no = 2;
    repeated uint32 song_no = 3;
  }
  required uint32 result = 1;
  repeated GetfolderResponse.EventfolderData ary_eventfolder_data = 2;
}

message TaikojukuRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  repeated uint32 get_dan = 3;
}

message TaikojukuResponse {
  message JukupackData {
    message JukusongData {
      required uint32 song_no = 1;
      required uint32 level = 2;
    }
    required uint32 get_dan = 1;
    optional uint32 verup_no = 2;
    repeated TaikojukuResponse.JukupackData.JukusongData ary_jukusong_data = 3;
  }
  required uint32 result = 1;
  repeated TaikojukuResponse.JukupackData ary_jukupack_data = 2;
}

message InitialdatacheckRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
}

message InitialdatacheckResponse {
  message InformationData {
    required uint32 info_id = 1;
    required uint32 verup_no = 2;
  }
  required uint32 result = 1;
  optional uint32 song_hash_ver = 2;
  optional bytes hash_default_song_flg = 3;
  optional bytes hash_mainichidojo_all = 4;
  optional bytes hash_mainichidojo_rare = 5;
  repeated InitialdatacheckResponse.InformationData ary_telop_data = 6;
  repeated InitialdatacheckResponse.InformationData ary_eventfolder_data = 7;
  repeated InitialdatacheckResponse.InformationData ary_taikojuku_data = 8;
  repeated InitialdatacheckResponse.InformationData ary_itemshop_data = 9;
  optional bool is_danplay = 10;
  optional bool is_close = 11;
  optional bool is_itemshop = 12;
  repeated InitialdatacheckResponse.InformationData ary_legalterms_data = 13;
}

message TournamentcheckRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required uint32 kit_id = 3;
}

message TournamentcheckResponse {
  message GachainfoData {
    required bytes normal_gacha_flg = 1;
    required bytes rare_gacha_flg = 2;
  }
  required uint32 result = 1;
  optional uint32 rare_rate = 2;
  optional uint32 song_hash_ver = 3;
  repeated TournamentcheckResponse.GachainfoData ary_gacha_song_data = 4;
  repeated TournamentcheckResponse.GachainfoData ary_gacha_tone_data = 5;
  repeated TournamentcheckResponse.GachainfoData ary_gacha_costume_1_data = 6;
  repeated TournamentcheckResponse.GachainfoData ary_gacha_costume_2_data = 7;
  repeated TournamentcheckResponse.GachainfoData ary_gacha_costume_3_data = 8;
  repeated TournamentcheckResponse.GachainfoData ary_gacha_costume_4_data = 9;
  repeated TournamentcheckResponse.GachainfoData ary_gacha_costume_5_data = 10;
  repeated TournamentcheckResponse.GachainfoData ary_gacha_title_data = 11;
}

message CoinsettingRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required string setting_datetime = 3;
  required uint32 play_rates = 4;
}

message CoinsettingResponse {
  required uint32 result = 1;
}

message GetitemshopinfoRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
}

message GetitemshopinfoResponse {
  message ItemshopData {
    required uint32 item_no = 1;
    required uint32 item_type = 2;
    required uint32 item_id = 3;
    required uint32 item_price = 4;
  }
  required uint32 result = 1;
  optional uint32 verup_no = 2;
  optional uint32 season_id = 3;
  optional string telop = 4;
  repeated GetitemshopinfoResponse.ItemshopData ary_itemshop_data = 5;
}

message BAIDRequest {
  required uint32 device_type = 1;
  required string access_code = 2;
  required string chip_id = 3;
  required string chassis_id = 4;
  required string shop_id = 5;
  required string country_id = 6;
}

message BAIDResponse {
  message CostumeData {
    optional uint32 costume_1 = 1;
    optional uint32 costume_2 = 2;
    optional uint32 costume_3 = 3;
    optional uint32 costume_4 = 4;
    optional uint32 costume_5 = 5;
  }
  required uint32 result = 1;
  optional uint32 player_type = 2;
  optional uint32 com_svr_result = 3;
  optional uint32 mb_id = 4;
  optional uint32 baid = 5;
  optional string access_code = 6;
  optional bool is_publish = 7;
  optional uint32 card_own_num = 8;
  optional string reg_country_id = 9;
  optional uint32 purpose_id = 10;
  optional uint32 region_id = 11;
  optional string mydon_name = 12;
  optional string title = 13;
  optional uint32 titleplate_id = 14;
  optional uint32 color_face = 15;
  optional uint32 color_body = 16;
  optional uint32 color_limb = 17;
  optional BAIDResponse.CostumeData ary_costumedata = 18;
  repeated BAIDResponse.CostumeData ary_favorite_costumedata = 19;
  optional bytes costume_flg_1 = 20;
  optional bytes costume_flg_2 = 21;
  optional bytes costume_flg_3 = 22;
  optional bytes costume_flg_4 = 23;
  optional bytes costume_flg_5 = 24;
  optional uint32 total_get_donmedal = 25;
  optional uint32 total_use_donmedal = 26;
  optional uint32 total_get_katsumedal = 27;
  optional uint32 total_use_katsumedal = 28;
  optional uint32 itemshop_tutorial_flg = 29;
  optional bool is_auto_costume_on = 30;
  optional string last_play_datetime = 31;
  optional string update_datetime = 32;
  optional uint32 disp_dan_type = 33;
  optional uint32 got_dan_max = 34;
  optional bytes got_dan_flg = 35;
  optional bytes got_danextra_flg = 36;
  optional string accesstoken = 37;
  optional bytes content_info = 38;
  optional uint32 default_tone_setting = 39;
  optional string personid = 40;
}

message MydonEntryRequest {
  required uint32 device_type = 1;
  required string access_code = 2;
  required string chip_id = 3;
  required string chassis_id = 4;
  required string shop_id = 5;
  required string country_id = 6;
  required string mydon_name = 7;
}

message MydonEntryResponse {
  required uint32 result = 1;
  optional uint32 com_svr_result = 2;
  optional uint32 mb_id = 3;
  optional uint32 baid = 4;
  optional string access_code = 5;
  optional bool is_publish = 6;
  optional uint32 card_own_num = 7;
  optional string reg_country_id = 8;
  optional uint32 purpose_id = 9;
  optional uint32 region_id = 10;
  optional string mydon_name = 11;
  optional string accesstoken = 12;
  optional bytes content_info = 13;
  optional string personid = 14;
}

message UserDataRequest {
  required uint32 baid = 1;
  required string chassis_id = 2;
  required string shop_id = 3;
}

message UserDataResponse {
  message FriendInfo {
    required uint32 baid = 1;
    required string friend_name = 2;
  }
  required uint32 result = 1;
  optional bool is_explain = 2;
  repeated uint32 ary_favorite_song_no = 3;
  repeated uint32 ary_recent_song_no = 4;
  optional uint32 song_hash_ver = 5;
  optional bytes hash_release_song_flg = 6;
  optional bool is_devil = 7;
  optional uint32 disp_score_type = 8;
  repeated UserDataResponse.FriendInfo ary_friend_info = 9;
  optional uint32 disp_level_total = 10;
  optional uint32 disp_level_chassis = 11;
  optional bytes option_flg = 12;
  optional bytes tone_flg = 13;
  optional bytes title_flg = 14;
  optional uint32 categ_jpop_cnt = 15;
  optional uint32 categ_anime_cnt = 16;
  optional uint32 categ_doyo_cnt = 17;
  optional uint32 categ_variety_cnt = 18;
  optional uint32 categ_classic_cnt = 19;
  optional uint32 categ_game_cnt = 20;
  optional uint32 categ_namco_cnt = 21;
  optional uint32 categ_vocaloid_cnt = 22;
  optional uint32 song_pushed_cnt = 23;
  optional uint32 song_favorite_cnt = 24;
  optional uint32 song_recent_cnt = 25;
  optional uint32 total_credit_cnt = 26;
  optional uint32 prev_area_code = 27;
  optional uint32 consec_area_cnt = 28;
  optional uint32 recommend_song = 29;
  repeated uint32 recommend_best_song = 30;
  optional uint32 disp_level_self = 31;
  optional bytes default_option_setting = 32;
  optional bool default_shin_setting = 33;
  optional uint32 disp_taikojuku_dan = 34;
  optional uint32 difficulty_played_course = 35;
  optional uint32 difficulty_played_star = 36;
  optional uint32 tokkun_tutorial_flg = 37;
  optional bool is_challengecompe = 38;
  optional bool is_tojiru = 39;
}

message PlayResultRequest {
  message StageData {
    message ResultcompeData {
      required uint32 compe_id = 1;
      required uint32 track_no = 2;
    }
    required uint32 song_no = 1;
    required uint32 level = 2;
    required uint32 play_result = 3;
    required uint32 play_score = 4;
    repeated PlayResultRequest.StageData.ResultcompeData ary_challenge_id = 5;
    repeated PlayResultRequest.StageData.ResultcompeData ary_user_compe_id = 6;
    repeated PlayResultRequest.StageData.ResultcompeData ary_bng_compe_id = 7;
    required uint32 good_cnt = 8;
    required uint32 ok_cnt = 9;
    required uint32 ng_cnt = 10;
    required uint32 pound_cnt = 11;
    required uint32 combo_cnt = 12;
    required bytes option_flg = 13;
    required bytes tone_flg = 14;
    required uint32 music_categ = 15;
    required bool is_pushed = 16;
    required bool is_favorite = 17;
    required bool is_recent = 18;
    required bool is_papamama = 19;
    required uint32 play_dan = 20;
    optional uint32 soul_gauge = 21;
    optional uint32 hit_cnt = 22;
    required uint32 stage_mode = 23;
    required uint32 selected_folder_id = 24;
  }
  message CostumeData {
    optional uint32 costume_1 = 1;
    optional uint32 costume_2 = 2;
    optional uint32 costume_3 = 3;
    optional uint32 costume_4 = 4;
    optional uint32 costume_5 = 5;
  }
  message CollaboData {
    required uint32 collabo_select = 1;
    optional uint32 collabo_id = 2;
    optional uint32 collabo_result = 3;
  }
  message TokkunstageData {
    required string banacoin_datetime = 1;
    required uint32 tokkun_song_cnt = 2;
    repeated uint32 tookun_songno = 3;
    required uint32 tokkun_speedchange_cnt = 4;
    required uint32 tokkun_autoplay_cnt = 5;
    required uint32 tokkun_jump_cnt = 6;
  }
  required uint32 baid = 1;
  required string chassis_id = 2;
  required string shop_id = 3;
  required string play_datetime = 4;
  required bool is_right = 5;
  required uint32 card_type = 6;
  required bool is_two_players = 7;
  repeated PlayResultRequest.StageData ary_stage_info = 8;
  repeated uint32 release_song_no = 9;
  repeated uint32 get_tone_no = 10;
  repeated uint32 get_costume_no_1 = 11;
  repeated uint32 get_costume_no_2 = 12;
  repeated uint32 get_costume_no_3 = 13;
  repeated uint32 get_costume_no_4 = 14;
  repeated uint32 get_costume_no_5 = 15;
  repeated uint32 get_title_no = 16;
  required bool bonus_daily_flg = 17;
  required bool bonus_weekly_flg = 18;
  required bool bonus_monthly_flg = 19;
  required uint32 get_donmedal = 20;
  required uint32 get_katsumedal = 21;
  optional uint32 itemshop_tutorial_flg = 22;
  optional bool is_devil = 23;
  optional bool is_explain = 24;
  optional PlayResultRequest.CostumeData ary_play_costume = 25;
  optional PlayResultRequest.CostumeData ary_current_costume = 26;
  required uint32 gender_type = 27;
  required uint32 player_age = 28;
  required uint32 play_mode = 29;
  required uint32 area_code = 30;
  required bytes reserved = 31;
  optional uint32 lowerlimit_age = 32;
  optional uint32 upperlimit_age = 33;
  optional uint32 age_score = 34;
  optional uint32 estimation_count = 35;
  optional uint32 dan_result = 36;
  repeated PlayResultRequest.CollaboData ary_collabo_info = 37;
  optional uint32 tournament_mode = 38;
  optional string accesstoken = 39;
  optional bytes content_info = 40;
  optional uint32 difficulty_played_course = 41;
  optional uint32 difficulty_played_star = 42;
  optional uint32 payment_method = 43;
  optional uint32 tokkun_tutorial_flg = 44;
  optional PlayResultRequest.TokkunstageData ary_tokkunstage_info = 45;
}

message PlayResultResponse {
  required uint32 result = 1;
}

message SelfBestRequest {
  required uint32 baid = 1;
  required string chassis_id = 2;
  required string shop_id = 3;
  optional uint32 level = 4;
  repeated uint32 ary_song_no = 5;
}

message SelfBestResponse {
  message SelfBestData {
    required uint32 song_no = 1;
    required uint32 self_best_score = 2;
    required uint32 ura_best_score = 3;
  }
  required uint32 result = 1;
  optional uint32 level = 2;
  repeated SelfBestResponse.SelfBestData ary_selfbest_score = 3;
  repeated SelfBestResponse.SelfBestData ary_shin_selfbest_score = 4;
}

message RecommendRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required uint32 gender_type = 3;
  required uint32 player_age = 4;
}

message RecommendResponse {
  required uint32 result = 1;
  optional uint32 recommend_song = 2;
  repeated uint32 recommend_best_song = 3;
}

message CrownsDataRequest {
  required uint32 baid = 1;
  required string chassis_id = 2;
  required string shop_id = 3;
}

message CrownsDataResponse {
  required uint32 result = 1;
  optional uint32 song_hash_ver = 2;
  optional bytes hash_crown_flg = 3;
}

message HeadClerk2Request {
  message PlayData {
    required uint32 baid = 1;
    required string net_id = 2;
    required string played_at = 3;
    required bool is_right = 4;
    required string place_id = 5;
    optional uint32 type = 6;
    optional uint32 amount = 7;
  }
  required string chassis_id = 1;
  required string shop_id = 2;
  optional string current_place_id = 3;
  repeated HeadClerk2Request.PlayData ary_play_info = 4;
}

message HeadClerk2Response {
  required uint32 result = 1;
}

message GetreitaiRequest {
  required uint32 device_type = 1;
  required string access_code = 2;
  required string chip_id = 3;
  required string chassis_id = 4;
  required string shop_id = 5;
  required string country_id = 6;
}

message GetreitaiResponse {
  required uint32 result = 1;
}

message RewardcardcheckRequest {
  required uint32 device_type = 1;
  required string access_code = 2;
  required string chip_id = 3;
  required string chassis_id = 4;
  required string shop_id = 5;
  required string country_id = 6;
}

message RewardcardcheckResponse {
  required uint32 result = 1;
  optional uint32 baid = 2;
}

message RewardexecutionRequest {
  required uint32 baid = 1;
  required string chassis_id = 2;
  required string shop_id = 3;
  repeated uint32 release_song_no = 4;
  repeated uint32 get_tone_no = 5;
  repeated uint32 get_costume_no_1 = 6;
  repeated uint32 get_costume_no_2 = 7;
  repeated uint32 get_costume_no_3 = 8;
  repeated uint32 get_costume_no_4 = 9;
  repeated uint32 get_costume_no_5 = 10;
  repeated uint32 get_title_no = 11;
}

message RewardexecutionResponse {
  required uint32 result = 1;
}

message BalancecheckRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required string personid = 3;
}

message BalancecheckResponse {
  required uint32 result = 1;
  required string personid = 2;
  optional string bnid_result = 3;
  optional uint32 coin_coupon = 4;
}

message BanacoinpaymentRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required string shop_name = 3;
  required string personid = 4;
  required uint32 mode = 5;
  required uint32 banacoin_price = 6;
}

message BanacoinpaymentResponse {
  required uint32 result = 1;
  required string personid = 2;
  optional string bnid_result = 3;
  optional string chid = 4;
}

message BanacoinerrorlogRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required string shop_name = 3;
  required string personid = 4;
  required string timeout_datetime = 5;
}

message BanacoinerrorlogResponse {
  required uint32 result = 1;
}

message GetbanacoininfoRequest {
  required uint32 device_type = 1;
  required string access_code = 2;
  required string chip_id = 3;
  required string chassis_id = 4;
  required string shop_id = 5;
  required string country_id = 6;
}

message GetbanacoininfoResponse {
  required uint32 result = 1;
  optional uint32 player_type = 2;
  optional uint32 com_svr_result = 3;
  optional uint32 mb_id = 4;
  optional uint32 baid = 5;
  optional string access_code = 6;
  optional bool is_publish = 7;
  optional uint32 card_own_num = 8;
  optional string reg_country_id = 9;
  optional uint32 purpose_id = 10;
  optional uint32 region_id = 11;
  optional string personid = 12;
}

message ChallengeCompeRequest {
  required uint32 baid = 1;
  required string chassis_id = 2;
  required string shop_id = 3;
}

message ChallengeCompeResponse {
  message CompeData {
    message TracksData {
      required uint32 song_no = 1;
      required uint32 level = 2;
      required bytes option_flg = 3;
      required uint32 stage_mode = 4;
      required uint32 high_score = 5;
    }
    required uint32 compe_id = 1;
    repeated ChallengeCompeResponse.CompeData.TracksData ary_track_stat = 2;
  }
  required uint32 result = 1;
  repeated ChallengeCompeResponse.CompeData ary_challenge_stat = 2;
  repeated ChallengeCompeResponse.CompeData ary_user_compe_stat = 3;
  repeated ChallengeCompeResponse.CompeData ary_bng_compe_stat = 4;
}

message ItempurchaseRequest {
  required string chassis_id = 1;
  required string shop_id = 2;
  required uint32 baid = 3;
  required uint32 item_no = 4;
  optional uint32 item_type = 5;
  optional uint32 item_id = 6;
  optional uint32 item_price = 7;
}

message ItempurchaseResponse {
  required uint32 result = 1;
  optional uint32 total_get_donmedal = 2;
  optional uint32 total_use_donmedal = 3;
}
