<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko.proto

namespace App\GameProtocol\Proto\Sorairo\Taiko;

use App\GameProtocol\Proto\Sorairo\Metadata\Taiko;
use App\GameProtocol\Proto\Sorairo\Taiko\SelfBestResponse\SelfBestData;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>taiko.sorairo.SelfBestResponse</code>
 */
class SelfBestResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     */
    protected $level = null;

    /**
     * Generated from protobuf field <code>repeated .taiko.sorairo.SelfBestResponse.SelfBestData ary_selfbest_score = 3;</code>
     */
    private $ary_selfbest_score;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $level
     * @type \App\GameProtocol\Proto\Sorairo\Taiko\SelfBestResponse\SelfBestData[] $ary_selfbest_score
     *                                                                             }
     */
    public function __construct($data = null)
    {
        Taiko::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     *
     * @return int
     */
    public function getLevel()
    {
        return isset($this->level) ? $this->level : 0;
    }

    public function hasLevel()
    {
        return isset($this->level);
    }

    public function clearLevel()
    {
        unset($this->level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 level = 2;</code>
     *
     * @return $this
     */
    public function setLevel(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.sorairo.SelfBestResponse.SelfBestData ary_selfbest_score = 3;</code>
     *
     * @return RepeatedField<SelfBestData>
     */
    public function getArySelfbestScore()
    {
        return $this->ary_selfbest_score;
    }

    /**
     * Generated from protobuf field <code>repeated .taiko.sorairo.SelfBestResponse.SelfBestData ary_selfbest_score = 3;</code>
     *
     * @param  SelfBestData[]  $var
     * @return $this
     */
    public function setArySelfbestScore(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, SelfBestData::class);
        $this->ary_selfbest_score = $arr;

        return $this;
    }
}
