<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: taiko_sorairo.proto

namespace App\GameProtocol\Proto\Sorairo\Taiko;

use App\GameProtocol\Proto\Sorairo\Metadata\TaikoSorairo;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>taiko.sorairo.SonghashResponse</code>
 */
class SonghashResponse extends Message
{
    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     */
    protected $result = null;

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 2;</code>
     */
    protected $song_hash_ver = null;

    /**
     * Generated from protobuf field <code>optional bytes song_hash_tbl = 3;</code>
     */
    protected $song_hash_tbl = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type int $result
     * @type int $song_hash_ver
     * @type string $song_hash_tbl
     *              }
     */
    public function __construct($data = null)
    {
        TaikoSorairo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return int
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : 0;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>optional uint32 result = 1;</code>
     *
     * @return $this
     */
    public function setResult(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 2;</code>
     *
     * @return int
     */
    public function getSongHashVer()
    {
        return isset($this->song_hash_ver) ? $this->song_hash_ver : 0;
    }

    public function hasSongHashVer()
    {
        return isset($this->song_hash_ver);
    }

    public function clearSongHashVer()
    {
        unset($this->song_hash_ver);
    }

    /**
     * Generated from protobuf field <code>optional uint32 song_hash_ver = 2;</code>
     *
     * @return $this
     */
    public function setSongHashVer(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->song_hash_ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes song_hash_tbl = 3;</code>
     *
     * @return string
     */
    public function getSongHashTbl()
    {
        return isset($this->song_hash_tbl) ? $this->song_hash_tbl : '';
    }

    public function hasSongHashTbl()
    {
        return isset($this->song_hash_tbl);
    }

    public function clearSongHashTbl()
    {
        unset($this->song_hash_tbl);
    }

    /**
     * Generated from protobuf field <code>optional bytes song_hash_tbl = 3;</code>
     *
     * @return $this
     */
    public function setSongHashTbl(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->song_hash_tbl = $var;

        return $this;
    }
}
